import { quests } from '../place-in';

export const CENTRAL_QUESTS = [
  ...quests('paris', [
    [
      'vert-galant',
      'Square du Vert-Galant',
      'coast',
      48.8575,
      2.34,
      800,
      'The prow of the Île de la Cité, named after Henri IV, a notorious charmer. Quest: sit at the very tip.',
    ],
    [
      'canal-st-martin',
      'Canal Saint-Martin Locks',
      'coast',
      48.871,
      2.3655,
      900,
      'Napoleon dug the canal to bring fresh water to Paris. Quest: watch a barge pass a lock.',
    ],
    [
      'bassin-villette',
      'Bassin de la Villette',
      'coast',
      48.8885,
      2.377,
      400,
      'Paris’s largest stretch of open water, with summer swimming. Quest: find the twin cinemas.',
    ],
    [
      'lac-daumesnil',
      'Lac Daumesnil',
      'coast',
      48.8335,
      2.412,
      200,
      'Haussmann’s lake in the Bois de Vincennes, with a temple on an island. Quest: row out to the islands.',
    ],
    [
      'lac-inferieur',
      'Lac Inférieur, Bois de Boulogne',
      'coast',
      48.862,
      2.261,
      300,
      'Napoleon III wanted a London-style park. Quest: take the boat to the Chalet des Îles.',
    ],
    [
      'monceau',
      'Parc Monceau',
      'nature',
      48.8797,
      2.3088,
      500,
      'A duke’s folly garden with a mock Egyptian pyramid. Quest: find the pyramid.',
    ],
    [
      'sully',
      'Hôtel de Sully',
      'heritage',
      48.8547,
      2.3645,
      150,
      'A Marais mansion of 1625 with a secret passage to the Place des Vosges. Quest: walk through it.',
    ],
    [
      'vincennes',
      'Château de Vincennes',
      'heritage',
      48.8425,
      2.4355,
      200,
      'The tallest medieval keep in Europe, a royal prison for Diderot and Mirabeau. Quest: find the keep.',
    ],
    [
      'soubise',
      'Hôtel de Soubise',
      'heritage',
      48.86,
      2.3575,
      60,
      'A rococo palace that now keeps France’s national archives. Quest: find the princess’s oval salon.',
    ],
    [
      'carnavalet',
      'Musée Carnavalet',
      'culture',
      48.8575,
      2.3625,
      300,
      'The history of Paris in two Marais mansions. Quest: find Proust’s bedroom.',
    ],
    [
      'picasso',
      'Musée Picasso',
      'art',
      48.8598,
      2.3625,
      500,
      'Picasso’s own collection, in a salt-tax collector’s palace. Quest: find a guitar collage.',
    ],
    [
      'marmottan',
      'Musée Marmottan Monet',
      'art',
      48.8592,
      2.2675,
      200,
      'Home of “Impression, Sunrise”, the painting that named a movement. Quest: find it.',
    ],
    [
      'olympia',
      'L’Olympia',
      'music_events',
      48.8703,
      2.3283,
      600,
      'The music hall where Piaf, the Beatles and Brel played. Quest: photograph the red sign.',
    ],
    [
      'philharmonie',
      'Philharmonie de Paris',
      'music_events',
      48.8915,
      2.394,
      400,
      'Jean Nouvel’s hall clad in bird-shaped tiles. Quest: climb to the roof.',
    ],
    [
      'sunset-sunside',
      'Sunset-Sunside',
      'music_events',
      48.8595,
      2.3485,
      200,
      'Twin jazz clubs on the Rue des Lombards. Quest: catch a set downstairs.',
    ],
    [
      'bastille-opera',
      'Opéra Bastille',
      'music_events',
      48.8521,
      2.3696,
      300,
      'Built for the bicentenary of the Revolution, 1989. Quest: find the column of July.',
    ],
    [
      'cigale',
      'La Cigale',
      'music_events',
      48.8823,
      2.3405,
      300,
      'A cabaret of 1887, redesigned by Philippe Starck. Quest: catch a gig.',
    ],
    [
      'gare-du-nord',
      'Gare du Nord',
      'travel',
      48.8809,
      2.3553,
      900,
      'Europe’s busiest station, crowned with statues of northern cities. Quest: find Amsterdam’s statue.',
    ],
    [
      'alexandre-iii',
      'Pont Alexandre III',
      'travel',
      48.8639,
      2.3136,
      1500,
      'The most ornate bridge in Paris, built for the 1900 World’s Fair. Quest: find the gilded horses.',
    ],
    [
      'arts-et-metiers',
      'Arts et Métiers Station',
      'travel',
      48.8655,
      2.3565,
      200,
      'A metro platform clad in copper like Jules Verne’s Nautilus. Quest: find a porthole.',
    ],
    [
      'shakespeare',
      'Shakespeare and Company',
      'other',
      48.8526,
      2.3471,
      2000,
      'The bookshop where travelling writers sleep among the shelves. Quest: find the wishing well.',
    ],
    [
      'catacombs',
      'Catacombs of Paris',
      'other',
      48.8338,
      2.3324,
      1200,
      'Six million Parisians rest in old quarries. Quest: find the sign “Stop! This is the empire of death”.',
    ],
    [
      'je-taime',
      'Wall of I Love Yous',
      'other',
      48.8848,
      2.3387,
      1000,
      '“I love you” in 250 languages. Quest: find your language.',
    ],
    [
      'panoramas',
      'Passage des Panoramas',
      'other',
      48.871,
      2.342,
      300,
      'The oldest covered passage in Paris, 1799. Quest: find the engraver’s shop.',
    ],
    [
      'pere-lachaise',
      'Père Lachaise Cemetery',
      'other',
      48.8615,
      2.3935,
      900,
      'Oscar Wilde, Chopin and Jim Morrison lie here. Quest: find Wilde’s sphinx.',
    ],
  ]),

  ...quests('rome', [
    [
      'tiber-island',
      'Tiber Island',
      'coast',
      41.8905,
      12.4775,
      800,
      'Shaped like a ship, it has held a hospital since antiquity. Quest: find the stone prow.',
    ],
    [
      'borghese-lake',
      'Villa Borghese Lake',
      'coast',
      41.9135,
      12.4825,
      500,
      'A Temple of Aesculapius on an island. Quest: row around it.',
    ],
    [
      'eur-lake',
      'EUR Lake',
      'coast',
      41.832,
      12.472,
      200,
      'An artificial lake in Mussolini’s planned city, lined with Japanese cherries. Quest: come in April.',
    ],
    [
      'ponte-milvio',
      'Ponte Milvio',
      'coast',
      41.9355,
      12.467,
      300,
      'Where Constantine won Rome in 312. Quest: find a love padlock.',
    ],
    [
      'ponte-sisto',
      'Ponte Sisto',
      'coast',
      41.8925,
      12.4705,
      600,
      'A Renaissance bridge with an “eye” to warn of floods. Quest: find the round hole.',
    ],
    [
      'caffarella',
      'Caffarella Valley',
      'nature',
      41.864,
      12.515,
      150,
      'A rural valley inside Rome, with sheep and Roman ruins. Quest: find the nymphaeum of Egeria.',
    ],
    [
      'farnesina',
      'Villa Farnesina',
      'heritage',
      41.8935,
      12.467,
      150,
      'A banker’s villa painted by Raphael. Quest: find Galatea.',
    ],
    [
      'torlonia',
      'Villa Torlonia',
      'heritage',
      41.914,
      12.512,
      100,
      'A prince’s estate, later Mussolini’s home. Quest: find the House of Owls.',
    ],
    [
      'colonna',
      'Palazzo Colonna',
      'heritage',
      41.8985,
      12.4845,
      80,
      'A cannonball from 1849 is still lodged in its stairs. Quest: find the cannonball.',
    ],
    [
      'altemps',
      'Palazzo Altemps',
      'culture',
      41.901,
      12.4725,
      150,
      'Ancient statues in a Renaissance palace. Quest: find the Ludovisi Throne.',
    ],
    [
      'caracalla',
      'Baths of Caracalla',
      'culture',
      41.879,
      12.4925,
      600,
      'Baths for 1,600 Romans at a time. Quest: find a mosaic floor.',
    ],
    [
      'montemartini',
      'Centrale Montemartini',
      'art',
      41.8665,
      12.4785,
      100,
      'Roman statues among power-station turbines. Quest: find a statue beside a boiler.',
    ],
    [
      'maxxi',
      'MAXXI',
      'art',
      41.9285,
      12.4665,
      300,
      'Zaha Hadid’s museum of the 21st century. Quest: walk the black stairs.',
    ],
    [
      'auditorium',
      'Auditorium Parco della Musica',
      'music_events',
      41.9295,
      12.4745,
      400,
      'Renzo Piano’s three beetle-shaped halls. Quest: find the Roman villa found during building.',
    ],
    [
      'opera',
      'Teatro dell’Opera',
      'music_events',
      41.9005,
      12.495,
      300,
      'Tosca premiered here in 1900. Quest: find the opera’s poster.',
    ],
    [
      'alexanderplatz',
      'Alexanderplatz Jazz Club',
      'music_events',
      41.9095,
      12.4545,
      150,
      'Rome’s oldest jazz club, with signatures on the walls. Quest: find a famous name.',
    ],
    [
      'big-mama',
      'Big Mama',
      'music_events',
      41.8855,
      12.4715,
      150,
      'A Trastevere blues cellar since 1984. Quest: find the cellar.',
    ],
    [
      'argentina',
      'Teatro Argentina',
      'music_events',
      41.8955,
      12.4765,
      150,
      'The Barber of Seville premiered here, and flopped, in 1816. Quest: find the cats of Largo Argentina.',
    ],
    [
      'san-sebastiano',
      'Porta San Sebastiano',
      'travel',
      41.8735,
      12.5015,
      200,
      'The gate where the Appian Way leaves Rome. Quest: walk the old road south.',
    ],
    [
      'ponte-sant-angelo',
      'Ponte Sant’Angelo',
      'travel',
      41.9015,
      12.4665,
      2000,
      'Bernini’s angels line the bridge to Hadrian’s tomb. Quest: count the angels.',
    ],
    [
      'vatican-station',
      'Vatican Railway Station',
      'travel',
      41.901,
      12.451,
      50,
      'The smallest state railway in the world. Quest: see the station front.',
    ],
    [
      'bocca',
      'Mouth of Truth',
      'other',
      41.8881,
      12.4815,
      2000,
      'It bites the hands of liars, they say. Quest: put your hand in.',
    ],
    [
      'capuchin-crypt',
      'Capuchin Crypt',
      'other',
      41.9045,
      12.4885,
      400,
      'Chapels decorated with the bones of 3,700 friars. Quest: read the inscription.',
    ],
    [
      'giolitti',
      'Giolitti',
      'other',
      41.901,
      12.4775,
      1500,
      'Ice cream since 1900. Quest: order three flavours.',
    ],
    [
      'coppede',
      'Quartiere Coppedè',
      'other',
      41.9195,
      12.5025,
      100,
      'A fairytale quarter of the 1920s. Quest: find the frog fountain.',
    ],
    [
      'protestant-cemetery',
      'Non-Catholic Cemetery',
      'other',
      41.8765,
      12.479,
      200,
      'Keats and Shelley lie here among the cats. Quest: find Keats’s nameless stone.',
    ],
  ]),

  ...quests('florence', [
    [
      'arno-beach',
      'Arno Beach at Lungarno Serristori',
      'coast',
      43.7645,
      11.2595,
      300,
      'A summer beach on the river bank. Quest: watch the sunset over the Ponte Vecchio.',
    ],
    [
      'santa-trinita',
      'Ponte Santa Trinita',
      'coast',
      43.7695,
      11.25,
      800,
      'Rebuilt stone by stone after 1944, the statues fished from the Arno. Quest: find Spring’s missing head.',
    ],
    [
      'pescaia',
      'Pescaia di Santa Rosa',
      'coast',
      43.7705,
      11.2435,
      150,
      'An old weir where boats were hauled. Quest: watch the water spill.',
    ],
    [
      'san-niccolo',
      'San Niccolò Riverbank',
      'coast',
      43.7625,
      11.2665,
      200,
      'The medieval tower by the river. Quest: find the tower’s gate.',
    ],
    [
      'anconella',
      'Anconella Park',
      'coast',
      43.761,
      11.283,
      100,
      'A riverside park with canoe clubs. Quest: spot a rower.',
    ],
    [
      'petraia',
      'Villa La Petraia',
      'heritage',
      43.8065,
      11.234,
      80,
      'A Medici villa with a hanging garden. Quest: find Venus on the fountain.',
    ],
    [
      'castello',
      'Villa di Castello',
      'heritage',
      43.818,
      11.232,
      60,
      'The garden where Botticelli’s Venus once hung. Quest: find the grotto of animals.',
    ],
    [
      'davanzati',
      'Palazzo Davanzati',
      'heritage',
      43.7705,
      11.2525,
      100,
      'A merchant’s house of the 1300s. Quest: find the parrot room.',
    ],
    [
      'medici-chapels',
      'Medici Chapels',
      'culture',
      43.775,
      11.2535,
      500,
      'Michelangelo’s tombs for the Medici. Quest: find Night and Day.',
    ],
    [
      'san-marco',
      'San Marco Museum',
      'culture',
      43.778,
      11.259,
      300,
      'A convent where Fra Angelico painted every cell. Quest: find the Annunciation.',
    ],
    [
      'orsanmichele',
      'Orsanmichele',
      'art',
      43.7705,
      11.255,
      300,
      'A grain store turned church, ringed by guild statues. Quest: find Donatello’s Saint Mark.',
    ],
    [
      'brancacci',
      'Brancacci Chapel',
      'art',
      43.768,
      11.2435,
      200,
      'The frescoes that taught the Renaissance to paint. Quest: find Adam and Eve expelled.',
    ],
    [
      'maggio',
      'Teatro del Maggio',
      'music_events',
      43.7795,
      11.2365,
      200,
      'Home of Italy’s oldest festival. Quest: find the rooftop.',
    ],
    [
      'pergola',
      'Teatro della Pergola',
      'music_events',
      43.7735,
      11.262,
      150,
      'A theatre of 1656 where Verdi’s Macbeth premiered. Quest: find the stage door.',
    ],
    [
      'verdi',
      'Teatro Verdi',
      'music_events',
      43.769,
      11.26,
      150,
      'Built on the old Stinche prison. Quest: find the plaque.',
    ],
    [
      'murate',
      'Le Murate',
      'music_events',
      43.7705,
      11.2665,
      200,
      'A prison turned café and music space. Quest: find a cell.',
    ],
    [
      'st-marks',
      'St Mark’s English Church',
      'music_events',
      43.7665,
      11.2495,
      100,
      'Opera evenings in a Victorian church. Quest: hear an aria.',
    ],
    [
      'leopolda',
      'Stazione Leopolda',
      'travel',
      43.779,
      11.238,
      200,
      'Florence’s first railway station, 1848. Quest: find the iron columns.',
    ],
    [
      'porta-romana',
      'Porta Romana',
      'travel',
      43.76,
      11.244,
      300,
      'The gate of the road to Rome. Quest: find the giant statue.',
    ],
    [
      'carraia',
      'Ponte alla Carraia',
      'travel',
      43.771,
      11.2465,
      200,
      'The second bridge of Florence, 1220. Quest: watch the rowing teams.',
    ],
    [
      'wine-window',
      'Wine Window of Via delle Belle Donne',
      'other',
      43.7735,
      11.25,
      200,
      'Wine was sold through little windows during the plague. Quest: find one still pouring.',
    ],
    [
      'porcellino',
      'Il Porcellino',
      'other',
      43.7697,
      11.2537,
      1500,
      'Rub the boar’s nose and you will return. Quest: rub it.',
    ],
    [
      'mercato-centrale',
      'Mercato Centrale',
      'other',
      43.7765,
      11.2535,
      1000,
      'An iron market of 1874. Quest: eat a lampredotto.',
    ],
    [
      'profumo',
      'Officina Profumo Santa Maria Novella',
      'other',
      43.7735,
      11.2475,
      400,
      'A pharmacy run by friars since 1612. Quest: smell the Acqua della Regina.',
    ],
    [
      'santo-spirito',
      'Piazza Santo Spirito',
      'other',
      43.7665,
      11.247,
      600,
      'The square behind Brunelleschi’s plain church front. Quest: find the morning market.',
    ],
  ]),

  ...quests('amsterdam', [
    [
      'blijburg',
      'Blijburg Beach',
      'coast',
      52.354,
      5.005,
      300,
      'A city beach on new land in the IJmeer. Quest: dip your toes.',
    ],
    [
      'sloterplas',
      'Sloterplas',
      'coast',
      52.364,
      4.812,
      200,
      'A lake dug for the sand to raise the western suburbs. Quest: swim from the beach.',
    ],
    [
      'pllek',
      'Pllek Beach',
      'coast',
      52.4005,
      4.8885,
      300,
      'A beach of shipping containers at the old wharf. Quest: watch the ferries.',
    ],
    [
      'nieuwe-meer',
      'Nieuwe Meer',
      'coast',
      52.34,
      4.825,
      100,
      'A lake where locals swim in summer. Quest: find the jetty.',
    ],
    [
      'marineterrein',
      'Marineterrein Swimming',
      'coast',
      52.3735,
      4.918,
      200,
      'The old naval yard opened for swimming. Quest: jump in.',
    ],
    [
      'frankendael',
      'Frankendael Park',
      'nature',
      52.3505,
      4.929,
      100,
      'The last country house of the old polder estates. Quest: find the fountain.',
    ],
    [
      'attic',
      'Our Lord in the Attic',
      'heritage',
      52.375,
      4.9,
      300,
      'A secret church hidden in a canal house for Catholics. Quest: find the altar.',
    ],
    [
      'munttoren',
      'Munttoren',
      'heritage',
      52.3665,
      4.893,
      400,
      'A gate tower that minted coins in 1672. Quest: hear the carillon.',
    ],
    [
      'heads',
      'House with the Heads',
      'heritage',
      52.3755,
      4.8875,
      100,
      'Six heads guard the door; legend says they were burglars. Quest: count them.',
    ],
    [
      'van-loon',
      'Museum Van Loon',
      'culture',
      52.3635,
      4.8955,
      150,
      'A canal house of the East India Company family. Quest: find the coach house.',
    ],
    [
      'stedelijk',
      'Stedelijk Museum',
      'art',
      52.358,
      4.8795,
      600,
      'The “bathtub”. Quest: find a Mondrian.',
    ],
    [
      'foam',
      'Foam',
      'art',
      52.364,
      4.893,
      200,
      'A photography museum in a canal house. Quest: find the garden.',
    ],
    [
      'paradiso',
      'Paradiso',
      'music_events',
      52.3622,
      4.8838,
      500,
      'A church turned rock temple. Quest: find the stained glass.',
    ],
    [
      'melkweg',
      'Melkweg',
      'music_events',
      52.3645,
      4.881,
      400,
      'A dairy turned music club. Quest: find the old milk sign.',
    ],
    [
      'bimhuis',
      'Bimhuis',
      'music_events',
      52.3785,
      4.9125,
      200,
      'A black box of jazz over the IJ. Quest: find the window.',
    ],
    [
      'stopera',
      'Dutch National Opera',
      'music_events',
      52.3672,
      4.902,
      200,
      'The “Stopera”. Quest: find the NAP marker.',
    ],
    [
      'magere-brug',
      'Magere Brug',
      'travel',
      52.3632,
      4.9023,
      800,
      'A drawbridge of 1691. Quest: watch it open.',
    ],
    [
      'tram-museum',
      'Electric Museum Tramline',
      'travel',
      52.3485,
      4.858,
      50,
      'Historic trams from an old station. Quest: ride one.',
    ],
    [
      'seven-bridges',
      'Seven Bridges of Reguliersgracht',
      'travel',
      52.3635,
      4.899,
      600,
      'Seven arches in a row. Quest: count them.',
    ],
    [
      'albert-cuyp',
      'Albert Cuyp Market',
      'other',
      52.3555,
      4.8945,
      1500,
      'Europe’s busiest street market. Quest: eat a stroopwafel.',
    ],
    [
      'negen-straatjes',
      'De Negen Straatjes',
      'other',
      52.37,
      4.8845,
      800,
      'Nine little canal-side streets. Quest: find the cheese shop.',
    ],
    [
      'wynand-fockink',
      'Wynand Fockink',
      'other',
      52.3725,
      4.8945,
      300,
      'A tasting room since 1679. Quest: take the first sip bending.',
    ],
    [
      'electric-ladyland',
      'Electric Ladyland',
      'other',
      52.377,
      4.88,
      100,
      'The world’s first fluorescent art museum. Quest: glow.',
    ],
    [
      'houseboat',
      'Houseboat Museum',
      'other',
      52.371,
      4.881,
      300,
      'A 1914 cargo boat turned home. Quest: find the bed.',
    ],
  ]),

  ...quests('berlin', [
    [
      'plotzensee',
      'Plötzensee Lido',
      'coast',
      52.5445,
      13.329,
      200,
      'A lake beach in the city. Quest: swim.',
    ],
    [
      'badeschiff',
      'Badeschiff',
      'coast',
      52.4975,
      13.4525,
      300,
      'A pool in a barge on the Spree. Quest: swim with a view.',
    ],
    [
      'weissensee',
      'Weißensee Lido',
      'coast',
      52.5545,
      13.4665,
      150,
      'A lido of 1912. Quest: find the fountain.',
    ],
    [
      'rummelsburg',
      'Rummelsburger Bucht',
      'coast',
      52.4955,
      13.488,
      100,
      'A bay of houseboats. Quest: spot a floating home.',
    ],
    [
      'monbijou',
      'Monbijou Park Riverbank',
      'coast',
      52.5235,
      13.397,
      300,
      'A royal palace garden by the Spree. Quest: dance at the open-air tango.',
    ],
    [
      'friedrichshain',
      'Volkspark Friedrichshain',
      'nature',
      52.5285,
      13.433,
      200,
      'Berlin’s oldest public park, with hills of war rubble. Quest: climb the rubble hill.',
    ],
    [
      'schonhausen',
      'Schönhausen Palace',
      'heritage',
      52.5795,
      13.4045,
      40,
      'A queen’s summer palace, later the GDR’s guesthouse. Quest: find the GDR rooms.',
    ],
    [
      'ephraim',
      'Ephraim Palace',
      'heritage',
      52.5165,
      13.4085,
      80,
      'A rococo mansion rebuilt from stored stones. Quest: find the golden balconies.',
    ],
    [
      'bellevue',
      'Bellevue Palace',
      'heritage',
      52.517,
      13.3535,
      200,
      'The president’s white palace by the Spree. Quest: check if the flag flies.',
    ],
    [
      'jewish-museum',
      'Jewish Museum',
      'culture',
      52.502,
      13.3945,
      500,
      'Libeskind’s zig-zag building. Quest: find the Garden of Exile.',
    ],
    [
      'neue-nationalgalerie',
      'Neue Nationalgalerie',
      'art',
      52.507,
      13.3675,
      300,
      'Mies van der Rohe’s glass temple. Quest: find the sculpture garden.',
    ],
    [
      'boros',
      'Boros Collection',
      'art',
      52.5245,
      13.3855,
      100,
      'Contemporary art in a wartime bunker. Quest: book a tour.',
    ],
    [
      'philharmonie',
      'Berliner Philharmonie',
      'music_events',
      52.51,
      13.37,
      500,
      'Scharoun’s golden tent of sound. Quest: find the vineyard seats.',
    ],
    [
      'berghain',
      'Berghain',
      'music_events',
      52.5112,
      13.443,
      300,
      'A power station turned techno club. Quest: walk past the queue.',
    ],
    [
      'so36',
      'SO36',
      'music_events',
      52.5005,
      13.4215,
      200,
      'The punk club of West Berlin. Quest: find a poster.',
    ],
    [
      'staatsoper',
      'Staatsoper Unter den Linden',
      'music_events',
      52.517,
      13.395,
      300,
      'Frederick the Great’s opera house. Quest: find the dome.',
    ],
    [
      'clarchens',
      'Clärchens Ballhaus',
      'music_events',
      52.5265,
      13.397,
      200,
      'A dance hall since 1913. Quest: find the mirrored hall.',
    ],
    [
      'tempelhof-terminal',
      'Tempelhof Airport Terminal',
      'travel',
      52.484,
      13.388,
      300,
      'The airlift airport. Quest: find the eagle.',
    ],
    [
      'technikmuseum',
      'German Museum of Technology',
      'travel',
      52.4985,
      13.3775,
      300,
      'A raisin bomber on the roof. Quest: find the plane.',
    ],
    [
      'tranenpalast',
      'Palace of Tears',
      'travel',
      52.5205,
      13.387,
      200,
      'The border hall at Friedrichstraße. Quest: find the passport booth.',
    ],
    [
      'mauerpark',
      'Mauerpark',
      'other',
      52.5435,
      13.4025,
      1000,
      'Sunday karaoke on the death strip. Quest: sing.',
    ],
    [
      'konnopke',
      'Konnopke’s Imbiss',
      'other',
      52.5405,
      13.412,
      600,
      'Currywurst under the U-Bahn since 1930. Quest: order one.',
    ],
    [
      'checkpoint-charlie',
      'Checkpoint Charlie',
      'other',
      52.5075,
      13.3904,
      2000,
      'Tanks faced off here in 1961. Quest: find the sign.',
    ],
    [
      'fernsehturm',
      'Fernsehturm',
      'other',
      52.5208,
      13.4094,
      2000,
      'The TV tower. Quest: find the cross on the sphere.',
    ],
    [
      'molecule-man',
      'Molecule Man',
      'other',
      52.497,
      13.471,
      200,
      'Three giants in the Spree. Quest: photograph them.',
    ],
  ]),
];
