import { quests } from '../place-in';

// Culture's three everyday themes, one place each per city: food, markets and cafés; traditions
// and festivals; neighbourhood life. They stay in the Culture category (no new enum value).

export const CULTURE_THEME_QUESTS = [
  ...quests('sintra', [
    [
      'cafe-saudade',
      'Café Saudade',
      'culture',
      38.7998,
      -9.3818,
      70,
      'Once the Mathilde bakery, where Sintra’s queijadas were made for the day-trippers off the train. Quest: order one with a galão.',
    ],
    [
      'santa-eufemia',
      'Santa Eufémia Hermitage',
      'culture',
      38.7838,
      -9.3851,
      25,
      'A hilltop hermitage with a holy spring, where a pilgrimage and village festa have climbed every year for centuries. Quest: find the spring below the chapel.',
    ],
    [
      'almocageme',
      'Almoçageme Village Square',
      'culture',
      38.796,
      -9.473,
      15,
      'A village named after its running water, with a festival every October since 1758. Quest: find a stream coming down from the hills.',
    ],
  ]),
  ...quests('lisbon', [
    [
      'mercado-ribeira',
      'Mercado da Ribeira',
      'culture',
      38.7068,
      -9.1458,
      140,
      'Lisbon’s market hall since 1882: fish and flowers at dawn, chefs’ stalls by lunch. Quest: find the fruit sellers who still open first.',
    ],
    [
      'santo-antonio',
      'Santo António Church',
      'culture',
      38.7101,
      -9.1335,
      90,
      'Built where Lisbon’s favourite saint was born; on 13 June the city crowns him with sardines and basil pots. Quest: find the crypt of his birthplace.',
    ],
    [
      'mouraria',
      'Rua do Capelão, Mouraria',
      'culture',
      38.7158,
      -9.1352,
      35,
      'The lane where fado was born, in the old Moorish quarter. Quest: find the plaque to the singer Maria Severa.',
    ],
  ]),
  ...quests('porto', [
    [
      'bolhao',
      'Mercado do Bolhão',
      'culture',
      41.1488,
      -8.6075,
      120,
      'Porto’s market of 1914, reopened with its stallholders back in place. Quest: find a stall selling bread from Avintes.',
    ],
    [
      'fontainhas',
      'Fontainhas',
      'culture',
      41.143,
      -8.602,
      30,
      'The cliffside heart of São João: on 23 June the city parties here with leeks, hammers and grilled sardines. Quest: look down on the Dom Luís bridge from the terrace.',
    ],
    [
      'miragaia',
      'Miragaia',
      'culture',
      41.1425,
      -8.619,
      40,
      'Porto’s old riverside quarter of washing lines and arcades, older than the city walls. Quest: walk under the arches by the river.',
    ],
  ]),
  ...quests('evora', [
    [
      'quarta-feira',
      'Taberna Quarta-Feira',
      'culture',
      38.5735,
      -7.9063,
      25,
      'An Alentejo tavern where there is no menu: the cook decides. Quest: try the pork with clams or the açorda.',
    ],
    [
      'scala-coeli',
      'Scala Coeli Charterhouse',
      'culture',
      38.5803,
      -7.9244,
      15,
      'Carthusian monks kept their vow of silence here from 1598 until 2019, and their way of life still shapes the estate’s wine and bread. Quest: photograph the church front from the gate.',
    ],
    [
      'judiaria',
      'Judiaria Lanes',
      'culture',
      38.5703,
      -7.9112,
      20,
      'The old Jewish quarter around Rua dos Mercadores, now a quiet weave of lanes and doorsteps. Quest: find the street sign for Rua dos Mercadores.',
    ],
  ]),
  ...quests('aveiro', [
    [
      'manuel-firmino',
      'Mercado Manuel Firmino',
      'culture',
      40.6378,
      -8.6496,
      45,
      'Aveiro’s everyday market: eels, fruit, flowers and gossip. Quest: find a stall selling local salt.',
    ],
    [
      'arte-xavega',
      'Arte Xávega at Vagueira',
      'culture',
      40.559,
      -8.7685,
      30,
      'Fishermen still haul their nets up the beach the old way, with boats launched into the surf. Quest: watch a net come in (mornings, spring to autumn).',
    ],
    [
      'beira-mar',
      'Beira-Mar Quarter',
      'culture',
      40.6452,
      -8.6538,
      35,
      'The fishermen’s quarter between the canals, with tiled houses and front-door chats. Quest: find a house tiled in green.',
    ],
  ]),
];
