import { quests } from '../place-in';

// Genuine oddities, so every city keeps five or more Curiosities now that its bakeries, bars,
// cafés and markets count as Culture (food, markets and cafés). Aveiro's Canal das Pirâmides
// became a curiosity too, so a park keeps its Nature at five.

export const CURIOSITY_QUESTS = [
  ...quests('sintra', [
    [
      'capuchos',
      'Convent of the Capuchos',
      'other',
      38.784,
      -9.4365,
      40,
      'Friars lived here in tiny cells lined with cork, with doors so low you have to bow. Quest: find a cork-lined door.',
    ],
    [
      'vila-sassetti',
      'Vila Sassetti Path',
      'other',
      38.7937,
      -9.395,
      30,
      'A secret garden path that climbs from a hidden villa through boulders to the Moorish Castle. Quest: find the villa tower.',
    ],
  ]),
  ...quests('lisbon', [
    [
      'casa-dos-bicos',
      'Casa dos Bicos',
      'other',
      38.7088,
      -9.1323,
      60,
      'A house of 1523 covered in diamond-shaped stone spikes, with Roman fish-salting tanks in its basement. Quest: count the spikes in one row.',
    ],
    [
      'prazeres',
      'Prazeres Cemetery',
      'other',
      38.7135,
      -9.17,
      35,
      'A city of the dead: streets of family mausoleums, some with windows you can peer into. Quest: find a mausoleum with an angel on the roof.',
    ],
    [
      'cais-das-colunas',
      'Cais das Colunas',
      'other',
      38.7067,
      -9.1363,
      90,
      'Two marble columns and a stair into the Tagus, where kings and ambassadors once stepped ashore. Quest: photograph the columns with the river behind.',
    ],
    [
      'sao-roque',
      'São Roque Church',
      'other',
      38.7133,
      -9.1434,
      55,
      'A plain church hiding a chapel built in Rome from lapis lazuli and gold, blessed by the Pope and shipped to Lisbon in 1747. Quest: find the mosaic that looks like a painting.',
    ],
    [
      'sao-domingos',
      'São Domingos Church',
      'other',
      38.7148,
      -9.1374,
      70,
      'Gutted by fire in 1959 and reopened with its scorched columns and blackened walls left as they were. Quest: find a cracked column.',
    ],
  ]),
  ...quests('porto', [
    [
      'agramonte',
      'Agramonte Cemetery',
      'other',
      41.1561,
      -8.6305,
      20,
      'Art Nouveau tombs, mourning statues and family chapels, built after a cholera outbreak in 1855. Quest: find a weeping statue.',
    ],
    [
      'cedofeita',
      'Old Church of Cedofeita',
      'other',
      41.1546,
      -8.6189,
      25,
      'A tiny Romanesque church that may be the oldest in Porto, hidden behind its big modern namesake. Quest: find the carved animals on the doorway.',
    ],
    [
      'senhor-da-pedra',
      'Senhor da Pedra Chapel',
      'other',
      41.0723,
      -8.6631,
      45,
      'A white hexagonal chapel standing on a rock in the surf at Miramar beach. Quest: photograph it with the waves behind.',
    ],
    [
      'arrabida',
      'Arrábida Bridge',
      'other',
      41.1474,
      -8.6404,
      40,
      'When it opened in 1963 its arch was the longest concrete span in the world. Quest: spot the climbers on top of the arch.',
    ],
  ]),
  ...quests('evora', [
    [
      'arco-isabel',
      'Arch of Dona Isabel',
      'other',
      38.5737,
      -7.9113,
      20,
      'A Roman gateway still standing in the old city wall, with houses built around it. Quest: walk through it.',
    ],
    [
      'graca',
      'Graça Church Giants',
      'other',
      38.5687,
      -7.9068,
      25,
      'A church front guarded by four stone giants that locals call the Meninos da Graça, the Graça boys. Quest: count the giants.',
    ],
  ]),
  ...quests('aveiro', [
    [
      'santo-andre',
      'Santo André Museum Ship',
      'other',
      40.634,
      -8.7135,
      30,
      'A real cod-fishing trawler from 1948, now a museum ship you can walk through. Quest: find the cod hold.',
    ],
    [
      'baixa-santo-antonio',
      'Baixa de Santo António Park',
      'nature',
      40.6377,
      -8.6468,
      40,
      'A green valley of lawns, ponds and old trees running below the city centre. Quest: find a bench by the water.',
    ],
    [
      'senhor-das-barrocas',
      'Senhor das Barrocas Chapel',
      'other',
      40.6397,
      -8.6423,
      15,
      'A small Baroque chapel built on an eight-sided plan, rare in Portugal. Quest: count its sides from outside.',
    ],
    [
      'cais-do-bico',
      'Cais do Bico, Murtosa',
      'other',
      40.733,
      -8.654,
      20,
      'A quiet lagoon quay where painted moliceiro boats are still built and moored. Quest: find a prow with a cheeky painted joke.',
    ],
  ]),
];
