import { quests } from '../place-in';

export const DANUBE_ISLES_QUESTS = [
  ...quests('prague', [
    [
      'zlute-lazne',
      'Žluté lázně',
      'coast',
      50.0565,
      14.4145,
      300,
      'A riverside lido of the 1930s on the Vltava. Quest: rent a paddleboat.',
    ],
    [
      'naplavka',
      'Náplavka Embankment',
      'coast',
      50.0705,
      14.4145,
      800,
      'The old timber quay, now Prague’s Saturday farmers’ market. Quest: drink a beer on a moored boat.',
    ],
    [
      'kampa',
      'Kampa Island',
      'coast',
      50.0845,
      14.4085,
      900,
      'An island cut off by the Devil’s Stream, under Charles Bridge. Quest: find the giant crawling babies.',
    ],
    [
      'strelecky',
      'Střelecký Island',
      'coast',
      50.081,
      14.411,
      300,
      'Where archers and marksmen trained from the 1400s. Quest: find the steps down from the bridge.',
    ],
    [
      'slovansky',
      'Slovanský Island',
      'coast',
      50.0785,
      14.4135,
      200,
      'Where Liszt and Berlioz played in the island’s ballroom. Quest: hire a rowing boat.',
    ],
    [
      'vojan',
      'Vojan Gardens',
      'nature',
      50.0888,
      14.409,
      100,
      'A walled convent garden, the oldest in Prague. Quest: find the peacocks.',
    ],
    [
      'troja',
      'Troja Palace',
      'heritage',
      50.116,
      14.4115,
      60,
      'A baroque summer palace with a staircase of fighting giants. Quest: find the giants.',
    ],
    [
      'wallenstein',
      'Wallenstein Palace',
      'heritage',
      50.0895,
      14.406,
      200,
      'The general built it to rival the castle; the garden has a dripstone wall. Quest: find the hidden faces.',
    ],
    [
      'schwarzenberg',
      'Schwarzenberg Palace',
      'heritage',
      50.0885,
      14.3965,
      80,
      'Covered in sgraffito diamonds that look like stone. Quest: touch the flat wall.',
    ],
    [
      'strahov',
      'Strahov Library',
      'culture',
      50.086,
      14.3895,
      400,
      'The Philosophical and Theological halls of a monastery. Quest: find the narwhal tusk.',
    ],
    [
      'obecni-dum',
      'Municipal House',
      'culture',
      50.0875,
      14.428,
      600,
      'Art Nouveau where Czechoslovakia was declared in 1918. Quest: find the Mucha hall.',
    ],
    [
      'st-agnes',
      'Convent of St Agnes',
      'art',
      50.092,
      14.4245,
      100,
      'Medieval Bohemian painting in Prague’s first Gothic building. Quest: find the Master of Vyšší Brod.',
    ],
    [
      'veletrzni',
      'Veletržní Palace',
      'art',
      50.102,
      14.4335,
      150,
      'A functionalist trade-fair hall, now modern art. Quest: find the Slav Epic.',
    ],
    [
      'rudolfinum',
      'Rudolfinum',
      'music_events',
      50.09,
      14.4155,
      300,
      'Home of the Czech Philharmonic. Quest: find the composers on the roof.',
    ],
    [
      'state-opera',
      'State Opera',
      'music_events',
      50.079,
      14.4335,
      200,
      'Mahler conducted here. Quest: find the gilded ceiling.',
    ],
    [
      'reduta',
      'Reduta Jazz Club',
      'music_events',
      50.0815,
      14.4185,
      200,
      'Bill Clinton played the sax here in 1994. Quest: catch a set.',
    ],
    [
      'lucerna',
      'Lucerna Music Bar',
      'music_events',
      50.0815,
      14.4255,
      300,
      'A 1909 arcade. Quest: find the upside-down horse.',
    ],
    [
      'jazz-dock',
      'Jazz Dock',
      'music_events',
      50.0745,
      14.4105,
      200,
      'A glass club on the river. Quest: watch the boats.',
    ],
    [
      'tram-22',
      'Tram 22 at Malostranské náměstí',
      'culture',
      50.088,
      14.4035,
      500,
      'The tram that climbs to the castle. Quest: ride it up.',
    ],
    [
      'ntm',
      'National Technical Museum',
      'culture',
      50.0975,
      14.425,
      200,
      'Trains, cars and planes in one hall. Quest: find the presidential car.',
    ],
    [
      'masaryk',
      'Masaryk Station',
      'culture',
      50.089,
      14.4345,
      200,
      'Prague’s first station, 1845. Quest: find the old clock.',
    ],
    [
      'golden-lane',
      'Golden Lane',
      'other',
      50.092,
      14.4045,
      1500,
      'Tiny houses in the castle walls; Kafka wrote at No. 22. Quest: find No. 22.',
    ],
    [
      'u-fleku',
      'U Fleků',
      'other',
      50.0785,
      14.417,
      800,
      'A brewery since 1499. Quest: try the dark lager.',
    ],
    [
      'kafka-statue',
      'Kafka Statue',
      'other',
      50.0905,
      14.419,
      400,
      'Kafka riding an empty suit. Quest: find it.',
    ],
    [
      'piss',
      'Piss Sculpture',
      'other',
      50.088,
      14.41,
      300,
      'David Černý’s two men. Quest: send them a text message.',
    ],
    [
      'infant-jesus',
      'Infant Jesus of Prague',
      'other',
      50.0855,
      14.404,
      400,
      'A wax figure with a wardrobe of 100 robes. Quest: see today’s robe.',
    ],
  ]),

  ...quests('vienna', [
    [
      'gansehaufel',
      'Gänsehäufel',
      'coast',
      48.2235,
      16.437,
      300,
      'A lido on an island in the Alte Donau. Quest: swim.',
    ],
    [
      'copa-beach',
      'Copa Beach',
      'coast',
      48.235,
      16.4165,
      200,
      'The Danube’s city beach. Quest: find the steps into the water.',
    ],
    [
      'strandbar',
      'Strandbar Herrmann',
      'coast',
      48.2105,
      16.3845,
      300,
      'A sand beach on the Danube Canal. Quest: order a spritzer.',
    ],
    [
      'badeschiff',
      'Badeschiff Wien',
      'coast',
      48.2135,
      16.38,
      200,
      'A pool ship on the canal. Quest: swim.',
    ],
    [
      'krapfenwaldl',
      'Krapfenwaldlbad',
      'coast',
      48.262,
      16.329,
      100,
      'A pool in the Vienna Woods. Quest: see the city from the water.',
    ],
    [
      'lainzer',
      'Lainzer Tiergarten',
      'nature',
      48.17,
      16.24,
      150,
      'The emperors’ hunting park. Quest: spot a wild boar.',
    ],
    [
      'augarten',
      'Augarten',
      'nature',
      48.2245,
      16.3755,
      200,
      'A baroque park with flak towers. Quest: find a flak tower.',
    ],
    [
      'liechtenstein',
      'Liechtenstein Garden Palace',
      'heritage',
      48.2225,
      16.359,
      50,
      'A prince’s summer palace. Quest: find the Hercules hall.',
    ],
    [
      'hermesvilla',
      'Hermesvilla',
      'heritage',
      48.1735,
      16.26,
      60,
      'Franz Joseph’s gift to Sisi. Quest: find Sisi’s gym.',
    ],
    [
      'pallavicini',
      'Palais Pallavicini',
      'heritage',
      48.207,
      16.3675,
      40,
      'A baroque palace on Josefsplatz. Quest: find the caryatids.',
    ],
    [
      'freud',
      'Sigmund Freud Museum',
      'culture',
      48.2185,
      16.363,
      200,
      'Berggasse 19. Quest: find the waiting room.',
    ],
    [
      'haus-der-musik',
      'Haus der Musik',
      'culture',
      48.204,
      16.3745,
      300,
      'Conduct the Vienna Philharmonic virtually. Quest: conduct.',
    ],
    [
      'mak',
      'MAK',
      'art',
      48.2075,
      16.3815,
      200,
      'Applied arts. Quest: find the Klimt frieze cartoons.',
    ],
    [
      'kunsthaus',
      'Kunst Haus Wien',
      'art',
      48.211,
      16.3935,
      200,
      'Hundertwasser’s museum with uneven floors. Quest: feel the floor.',
    ],
    [
      'musikverein',
      'Musikverein',
      'music_events',
      48.2005,
      16.3725,
      500,
      'The Golden Hall of New Year’s Day. Quest: find the golden hall.',
    ],
    [
      'konzerthaus',
      'Konzerthaus',
      'music_events',
      48.201,
      16.3805,
      300,
      'An Art Nouveau concert house. Quest: catch a concert.',
    ],
    [
      'volksoper',
      'Volksoper',
      'music_events',
      48.2265,
      16.351,
      200,
      'Operetta’s home. Quest: catch a waltz.',
    ],
    [
      'porgy',
      'Porgy & Bess',
      'music_events',
      48.2055,
      16.377,
      200,
      'Vienna’s jazz club. Quest: catch a set.',
    ],
    [
      'hauptbahnhof',
      'Wien Hauptbahnhof',
      'culture',
      48.1855,
      16.376,
      400,
      'Diamond-shaped roof. Quest: count the diamonds.',
    ],
    [
      'remise',
      'Remise Transport Museum',
      'culture',
      48.2005,
      16.413,
      100,
      'Old trams in a depot. Quest: find the oldest tram.',
    ],
    [
      'hofpavillon',
      'Hofpavillon Hietzing',
      'culture',
      48.187,
      16.303,
      50,
      'Otto Wagner’s private station for the emperor. Quest: find the waiting room.',
    ],
    [
      'cafe-central',
      'Café Central',
      'other',
      48.2105,
      16.3655,
      1500,
      'Trotsky played chess here. Quest: find the poet’s statue.',
    ],
    [
      'zentralfriedhof',
      'Zentralfriedhof',
      'other',
      48.153,
      16.44,
      400,
      'Beethoven, Brahms and Falco lie here. Quest: find Beethoven.',
    ],
    [
      'figlmuller',
      'Figlmüller',
      'other',
      48.209,
      16.3755,
      1000,
      'Schnitzel bigger than the plate. Quest: finish one.',
    ],
  ]),

  ...quests('edinburgh', [
    [
      'cramond',
      'Cramond',
      'coast',
      55.98,
      -3.3,
      300,
      'A Roman fort village with a tidal island. Quest: check the tide times.',
    ],
    [
      'newhaven',
      'Newhaven Harbour',
      'coast',
      55.981,
      -3.196,
      200,
      'An old fishing village with a lighthouse. Quest: find the lighthouse.',
    ],
    [
      'joppa',
      'Joppa Rock Pools',
      'coast',
      55.948,
      -3.092,
      100,
      'Rock pools at the end of the promenade. Quest: find a crab.',
    ],
    [
      'silverknowes',
      'Silverknowes Promenade',
      'coast',
      55.979,
      -3.26,
      150,
      'A shore walk to Cramond. Quest: watch the Forth.',
    ],
    [
      'lauriston',
      'Lauriston Castle',
      'heritage',
      55.9715,
      -3.2795,
      50,
      'An Edwardian home in a 16th-century tower. Quest: find the Japanese garden.',
    ],
    [
      'craigmillar',
      'Craigmillar Castle',
      'heritage',
      55.9265,
      -3.1415,
      80,
      'Mary Queen of Scots stayed here. Quest: climb the tower.',
    ],
    [
      'duddingston',
      'Duddingston Kirk',
      'heritage',
      55.9418,
      -3.1495,
      40,
      'A Norman church with a watchtower against body snatchers. Quest: find the watchtower.',
    ],
    [
      'surgeons',
      'Surgeons’ Hall Museums',
      'culture',
      55.9465,
      -3.184,
      200,
      'Medicine’s grim past. Quest: find the Burke and Hare book.',
    ],
    [
      'georgian',
      'The Georgian House',
      'culture',
      55.952,
      -3.2075,
      100,
      'A New Town house as it was in 1800. Quest: find the kitchen.',
    ],
    [
      'portrait',
      'Scottish National Portrait Gallery',
      'art',
      55.9555,
      -3.1935,
      200,
      'A red sandstone palace. Quest: find the golden frieze.',
    ],
    [
      'dovecot',
      'Dovecot Studios',
      'art',
      55.9475,
      -3.186,
      100,
      'Tapestry weavers in an old swimming baths. Quest: watch the weavers.',
    ],
    [
      'usher',
      'Usher Hall',
      'music_events',
      55.9465,
      -3.2055,
      300,
      'Edinburgh’s great concert hall. Quest: catch a concert.',
    ],
    [
      'sandy-bells',
      'Sandy Bell’s',
      'music_events',
      55.9455,
      -3.1895,
      300,
      'A folk session every night. Quest: hear a reel.',
    ],
    [
      'queens-hall',
      'The Queen’s Hall',
      'music_events',
      55.9405,
      -3.1815,
      150,
      'A church turned concert hall. Quest: catch a gig.',
    ],
    [
      'leith-theatre',
      'Leith Theatre',
      'music_events',
      55.9705,
      -3.172,
      100,
      'A 1932 theatre reborn. Quest: catch a gig.',
    ],
    [
      'jazz-bar',
      'The Jazz Bar',
      'music_events',
      55.9483,
      -3.1872,
      200,
      'Live music every night. Quest: catch a set.',
    ],
    [
      'trams',
      'St Andrew Square Tram Stop',
      'culture',
      55.9545,
      -3.1925,
      300,
      'The tram line to the airport. Quest: ride one stop.',
    ],
    [
      'union-canal',
      'Union Canal at Edinburgh Quay',
      'culture',
      55.944,
      -3.208,
      150,
      'A canal of 1822. Quest: find the narrowboats.',
    ],
    [
      'scotsman-steps',
      'Scotsman Steps',
      'culture',
      55.951,
      -3.1895,
      300,
      'Marble steps from the station. Quest: count the colours.',
    ],
    [
      'greyfriars-bobby',
      'Greyfriars Bobby',
      'other',
      55.947,
      -3.1918,
      1500,
      'A loyal dog who guarded his master’s grave. Quest: find his statue.',
    ],
    [
      'camera-obscura',
      'Camera Obscura',
      'other',
      55.9488,
      -3.1962,
      800,
      'A Victorian camera that spies on the city. Quest: see the live view.',
    ],
    [
      'victoria-street',
      'Victoria Street',
      'other',
      55.948,
      -3.1935,
      1500,
      'A curving street of coloured shops. Quest: find the brush shop.',
    ],
    [
      'circus-lane',
      'Circus Lane',
      'other',
      55.9575,
      -3.2065,
      400,
      'A cobbled lane of mews houses. Quest: photograph the flowers.',
    ],
    [
      'dr-neils',
      'Dr Neil’s Garden',
      'other',
      55.942,
      -3.1435,
      50,
      'A secret garden by the loch. Quest: find the physic garden.',
    ],
    [
      'shore',
      'The Shore, Leith',
      'other',
      55.9755,
      -3.17,
      400,
      'Leith’s old harbour. Quest: find the Signal Tower.',
    ],
  ]),

  ...quests('budapest', [
    [
      'palatinus',
      'Palatinus Strand',
      'coast',
      47.53,
      19.0465,
      400,
      'An open-air bath on Margaret Island. Quest: ride the wave pool.',
    ],
    [
      'romai-part',
      'Római Part',
      'coast',
      47.577,
      19.051,
      300,
      'The Roman Bank, with fried fish by the Danube. Quest: eat a lángos.',
    ],
    [
      'dunakorzo',
      'Danube Promenade',
      'coast',
      47.495,
      19.048,
      1500,
      'The promenade with the little princess statue. Quest: find the princess.',
    ],
    [
      'kopaszi',
      'Kopaszi Dam',
      'coast',
      47.4605,
      19.0645,
      200,
      'A beach park on a Danube dam. Quest: watch the sunset.',
    ],
    [
      'feneketlen',
      'Bottomless Lake',
      'coast',
      47.4765,
      19.044,
      100,
      'A lake born in an old brick pit. Quest: walk around it.',
    ],
    [
      'japanese-garden',
      'Margaret Island Japanese Garden',
      'nature',
      47.532,
      19.048,
      300,
      'A garden fed by thermal springs. Quest: find the waterfall.',
    ],
    [
      'gellert-hill',
      'Gellért Hill',
      'nature',
      47.4865,
      19.0465,
      1000,
      'Named after a bishop rolled down it in a barrel. Quest: reach the Liberty Statue.',
    ],
    [
      'normafa',
      'Normafa',
      'nature',
      47.5065,
      18.9655,
      200,
      'A forest meadow where a soprano sang Norma. Quest: eat a strudel.',
    ],
    [
      'sas-hegy',
      'Sas-hegy',
      'nature',
      47.481,
      19.017,
      50,
      'A rocky nature reserve in the city. Quest: find the lookout.',
    ],
    [
      'varosliget',
      'City Park Lake',
      'nature',
      47.5145,
      19.0815,
      600,
      'A lake that freezes into a skating rink. Quest: find Vajdahunyad Castle.',
    ],
    [
      'buda-castle',
      'Buda Castle',
      'heritage',
      47.4962,
      19.0398,
      3000,
      'The royal palace on the hill. Quest: find the Turul bird.',
    ],
    [
      'sandor',
      'Sándor Palace',
      'heritage',
      47.4975,
      19.0355,
      200,
      'The president’s palace. Quest: watch the guard change.',
    ],
    [
      'wenckheim',
      'Wenckheim Palace',
      'heritage',
      47.4895,
      19.0625,
      50,
      'A count’s palace turned library. Quest: find the reading room.',
    ],
    [
      'festetics',
      'Festetics Palace',
      'heritage',
      47.4915,
      19.0685,
      30,
      'A neo-baroque palace with a grand stair. Quest: find the stair.',
    ],
    [
      'karolyi',
      'Károlyi Palace',
      'heritage',
      47.492,
      19.06,
      40,
      'A count’s palace with a garden. Quest: find the garden café.',
    ],
    [
      'parliament',
      'Hungarian Parliament',
      'culture',
      47.507,
      19.0457,
      3000,
      'A Gothic Revival giant. Quest: find the Holy Crown.',
    ],
    [
      'matthias',
      'Matthias Church',
      'culture',
      47.5019,
      19.034,
      2000,
      'Coronation church with a roof of Zsolnay tiles. Quest: photograph the roof.',
    ],
    [
      'national-museum',
      'Hungarian National Museum',
      'culture',
      47.491,
      19.062,
      300,
      'Where the 1848 revolution began. Quest: find the steps.',
    ],
    [
      'house-of-terror',
      'House of Terror',
      'culture',
      47.507,
      19.065,
      500,
      'The secret police headquarters. Quest: find the tank.',
    ],
    [
      'synagogue',
      'Dohány Street Synagogue',
      'culture',
      47.496,
      19.0605,
      1000,
      'Europe’s largest synagogue. Quest: find the weeping willow.',
    ],
    [
      'fine-arts',
      'Museum of Fine Arts',
      'art',
      47.516,
      19.077,
      400,
      'Old masters. Quest: find the Romanesque Hall.',
    ],
    [
      'vasarely',
      'Vasarely Museum',
      'art',
      47.541,
      19.045,
      100,
      'Op art by its inventor. Quest: find the zebra.',
    ],
    [
      'capa',
      'Robert Capa Centre',
      'art',
      47.5045,
      19.061,
      100,
      'Photography by Budapest’s famous son. Quest: find the D-Day photo.',
    ],
    [
      'ludwig',
      'Ludwig Museum',
      'art',
      47.4672,
      19.0705,
      100,
      'Modern art by the Danube. Quest: find a Warhol.',
    ],
    [
      'kiscelli',
      'Kiscelli Museum',
      'art',
      47.547,
      19.035,
      50,
      'Art in a ruined church. Quest: find the nave.',
    ],
    [
      'opera',
      'Hungarian State Opera',
      'music_events',
      47.5025,
      19.0585,
      600,
      'Mahler conducted here. Quest: find the sphinxes.',
    ],
    [
      'liszt',
      'Liszt Academy',
      'music_events',
      47.5035,
      19.0625,
      300,
      'Art Nouveau music academy. Quest: find Liszt.',
    ],
    [
      'a38',
      'A38 Ship',
      'music_events',
      47.4775,
      19.0645,
      300,
      'A Ukrainian stone carrier turned club. Quest: find the deck.',
    ],
    [
      'bjc',
      'Budapest Jazz Club',
      'music_events',
      47.5115,
      19.0565,
      150,
      'Jazz in a 1930s cinema. Quest: catch a set.',
    ],
    [
      'sziget',
      'Óbuda Island (Sziget)',
      'music_events',
      47.553,
      19.0515,
      500,
      'Home of the Sziget festival. Quest: find the festival gate.',
    ],
    [
      'chain-bridge',
      'Széchenyi Chain Bridge',
      'culture',
      47.499,
      19.0435,
      3000,
      'The first bridge over the Danube, 1849. Quest: find a lion without a tongue.',
    ],
    [
      'funicular',
      'Buda Castle Funicular',
      'culture',
      47.4975,
      19.0395,
      1000,
      'A funicular of 1870. Quest: ride it.',
    ],
    [
      'childrens-railway',
      'Children’s Railway',
      'culture',
      47.4935,
      18.972,
      200,
      'A railway run by children. Quest: buy a ticket from a child.',
    ],
    [
      'keleti',
      'Keleti Station',
      'culture',
      47.5,
      19.0835,
      300,
      'A grand station of 1884. Quest: find the steam engine statue.',
    ],
    [
      'millennium',
      'Millennium Underground',
      'culture',
      47.497,
      19.0505,
      400,
      'The continent’s oldest metro, 1896. Quest: ride the little yellow train.',
    ],
    [
      'szechenyi-bath',
      'Széchenyi Bath',
      'other',
      47.5185,
      19.082,
      3000,
      'Chess in hot water. Quest: play chess.',
    ],
    [
      'szimpla',
      'Szimpla Kert',
      'other',
      47.497,
      19.0635,
      2000,
      'The first ruin bar. Quest: find the bathtub seat.',
    ],
    [
      'shoes',
      'Shoes on the Danube Bank',
      'other',
      47.5045,
      19.045,
      2000,
      'A memorial to Jews shot at the river in 1944–45. Quest: pause.',
    ],
    [
      'market-hall',
      'Great Market Hall',
      'other',
      47.487,
      19.0585,
      2000,
      'A market with a tiled roof. Quest: buy paprika.',
    ],
    [
      'gul-baba',
      'Gül Baba’s Tomb',
      'other',
      47.5135,
      19.035,
      100,
      'An Ottoman dervish’s tomb. Quest: find the roses.',
    ],
    [
      'hospital-rock',
      'Hospital in the Rock',
      'other',
      47.501,
      19.031,
      20,
      'A secret hospital in the caves under the castle. Quest: find the entrance.',
      'hidden',
    ],
  ]),

  ...quests('dublin', [
    [
      'sandymount',
      'Sandymount Strand',
      'coast',
      53.332,
      -6.214,
      300,
      'Joyce set Ulysses here. Quest: walk the sand.',
    ],
    [
      'dollymount',
      'Dollymount Strand',
      'coast',
      53.37,
      -6.145,
      300,
      'A beach on Bull Island. Quest: find the statue of Mary.',
    ],
    [
      'forty-foot',
      'Forty Foot',
      'coast',
      53.2895,
      -6.114,
      400,
      'Swimmers jump in all year. Quest: jump in.',
    ],
    [
      'howth',
      'Howth Cliff Walk',
      'coast',
      53.378,
      -6.065,
      600,
      'Cliffs with seals and a lighthouse. Quest: spot a seal.',
    ],
    [
      'dun-laoghaire',
      'Dún Laoghaire Pier',
      'coast',
      53.2985,
      -6.13,
      400,
      'A granite pier. Quest: walk to the lighthouse.',
    ],
    [
      'phoenix',
      'Phoenix Park',
      'nature',
      53.356,
      -6.33,
      1000,
      'Deer roam a royal park. Quest: spot a deer.',
    ],
    [
      'stephens-green',
      'St Stephen’s Green',
      'nature',
      53.3382,
      -6.2591,
      1500,
      'A Victorian park. Quest: find the ducks.',
    ],
    [
      'iveagh',
      'Iveagh Gardens',
      'nature',
      53.3355,
      -6.262,
      200,
      'A secret garden with a waterfall. Quest: find the maze.',
    ],
    [
      'botanic',
      'National Botanic Gardens',
      'nature',
      53.372,
      -6.272,
      300,
      'Curvilinear glasshouses. Quest: find the palm house.',
    ],
    [
      'war-memorial',
      'War Memorial Gardens',
      'nature',
      53.3445,
      -6.327,
      100,
      'Lutyens’s gardens. Quest: find the rose garden.',
    ],
    [
      'casino-marino',
      'Casino at Marino',
      'heritage',
      53.37,
      -6.233,
      50,
      'A tiny temple with 16 rooms. Quest: find the chimneys disguised as urns.',
    ],
    [
      'farmleigh',
      'Farmleigh House',
      'heritage',
      53.364,
      -6.361,
      50,
      'The Guinness family’s house. Quest: find the clock tower.',
    ],
    [
      'rathfarnham',
      'Rathfarnham Castle',
      'heritage',
      53.2995,
      -6.284,
      40,
      'An Elizabethan castle. Quest: find the corner towers.',
    ],
    [
      'malahide',
      'Malahide Castle',
      'heritage',
      53.443,
      -6.165,
      200,
      'A castle held by one family for 800 years. Quest: find Puck the ghost.',
    ],
    [
      'dublin-castle',
      'Dublin Castle',
      'heritage',
      53.3429,
      -6.2674,
      800,
      'Seat of British rule till 1922. Quest: find Justice with her back to the city.',
    ],
    [
      'long-room',
      'Trinity Long Room',
      'culture',
      53.3438,
      -6.2546,
      2000,
      'The great library. Quest: find the harp.',
    ],
    [
      'kilmainham',
      'Kilmainham Gaol',
      'culture',
      53.3419,
      -6.3095,
      800,
      'The prison of the rebels. Quest: find the stonebreakers’ yard.',
    ],
    [
      'christ-church',
      'Christ Church Cathedral',
      'culture',
      53.3435,
      -6.271,
      600,
      'A cathedral with a mummified cat and rat. Quest: find them.',
    ],
    [
      'epic',
      'EPIC Emigration Museum',
      'culture',
      53.3485,
      -6.2475,
      300,
      'Ten million emigrants. Quest: find a famous one.',
    ],
    [
      'marsh',
      'Marsh’s Library',
      'culture',
      53.3395,
      -6.2705,
      100,
      'Readers were locked in cages. Quest: find the cages.',
    ],
    [
      'national-gallery',
      'National Gallery of Ireland',
      'art',
      53.3409,
      -6.2524,
      500,
      'Caravaggio’s Taking of Christ. Quest: find it.',
    ],
    [
      'imma',
      'IMMA',
      'art',
      53.343,
      -6.3005,
      200,
      'Modern art in a soldiers’ hospital. Quest: find the formal garden.',
    ],
    [
      'hugh-lane',
      'Hugh Lane Gallery',
      'art',
      53.3545,
      -6.2645,
      200,
      'Francis Bacon’s studio, moved from London. Quest: find the studio.',
    ],
    [
      'rha',
      'Royal Hibernian Academy',
      'art',
      53.3365,
      -6.2525,
      100,
      'Contemporary art. Quest: find the current show.',
    ],
    [
      'wilde',
      'Oscar Wilde Statue',
      'art',
      53.3405,
      -6.2495,
      400,
      'Wilde in a jade jacket. Quest: find his house.',
    ],
    [
      'whelans',
      'Whelan’s',
      'music_events',
      53.3365,
      -6.2655,
      400,
      'A gig venue since 1989. Quest: catch a gig.',
    ],
    [
      'cobblestone',
      'The Cobblestone',
      'music_events',
      53.349,
      -6.278,
      300,
      'Trad sessions every night. Quest: hear a session.',
    ],
    [
      'nch',
      'National Concert Hall',
      'music_events',
      53.3345,
      -6.259,
      200,
      'Concerts in the old university. Quest: catch a concert.',
    ],
    [
      '3arena',
      '3Arena',
      'music_events',
      53.3475,
      -6.2285,
      300,
      'Dublin’s big arena. Quest: catch a show.',
    ],
    [
      'gaiety',
      'Gaiety Theatre',
      'music_events',
      53.3405,
      -6.2615,
      300,
      'A Victorian theatre. Quest: find the stars on the pavement.',
    ],
    [
      'hapenny',
      'Ha’penny Bridge',
      'culture',
      53.3463,
      -6.2631,
      2000,
      'The toll was a halfpenny. Quest: walk across.',
    ],
    [
      'beckett',
      'Samuel Beckett Bridge',
      'culture',
      53.347,
      -6.2415,
      500,
      'A bridge shaped like a harp. Quest: find the strings.',
    ],
    [
      'heuston',
      'Heuston Station',
      'culture',
      53.3465,
      -6.293,
      300,
      'A station of 1846. Quest: find the clock.',
    ],
    [
      'jeanie-johnston',
      'Jeanie Johnston',
      'culture',
      53.3475,
      -6.245,
      200,
      'A famine ship. Quest: go below deck.',
    ],
    [
      'grand-canal-dock',
      'Grand Canal Dock',
      'culture',
      53.3395,
      -6.2375,
      300,
      'Old docks turned plaza. Quest: find the red light poles.',
    ],
    [
      'guinness',
      'Guinness Storehouse',
      'other',
      53.3419,
      -6.2867,
      3000,
      'A 9,000-year lease. Quest: find the lease.',
    ],
    [
      'temple-bar',
      'The Temple Bar Pub',
      'other',
      53.3455,
      -6.264,
      2000,
      'Dublin’s most famous pub. Quest: find the whiskey wall.',
    ],
    [
      'brazen-head',
      'The Brazen Head',
      'other',
      53.345,
      -6.276,
      800,
      'Ireland’s oldest pub, 1198. Quest: find the courtyard.',
    ],
    [
      'molly-malone',
      'Molly Malone Statue',
      'other',
      53.3436,
      -6.26,
      2000,
      'The fishmonger of the song. Quest: sing the song.',
    ],
    [
      'st-michans',
      'St Michan’s Crypt',
      'other',
      53.3475,
      -6.276,
      200,
      'Mummies in the vaults. Quest: find the crusader.',
    ],
    [
      'hungry-tree',
      'Hungry Tree',
      'other',
      53.3535,
      -6.2715,
      10,
      'A tree swallowing a bench at King’s Inns. Quest: find the bench.',
      'hidden',
    ],
  ]),
];
