import { quests } from '../place-in';

// Side quests written as a travelling historian would brief you: a line of history, then what to
// go and find. Heritage leans on the quieter palaces and quintas rather than the famous queues.

export const IBERIA_QUESTS = [
  ...quests('sintra', [
    [
      'praia-macas',
      'Praia das Maçãs',
      'coast',
      38.8262,
      -9.47,
      900,
      'Where Lisbon’s Belle Époque day-trippers stepped off the tram. Quest: find the tidal sea pool at the north end.',
    ],
    [
      'praia-ursa',
      'Praia da Ursa',
      'coast',
      38.7893,
      -9.495,
      60,
      'A wild cove under Cabo da Roca, reached only on foot. Quest: spot the rock the fishermen named the She-Bear.',
    ],
    [
      'monserrate-ferns',
      'Monserrate Fern Valley',
      'nature',
      38.7934,
      -9.4218,
      300,
      'Francis Cook’s Victorian plant collectors filled this ravine with tree ferns. Quest: stand beneath the tallest frond.',
    ],
    [
      'quinta-relogio',
      'Quinta do Relógio',
      'heritage',
      38.7972,
      -9.3936,
      15,
      'A neo-Moorish quinta of 1860 where King Carlos spent his honeymoon. Quest: photograph its horseshoe arches from the road.',
    ],
    [
      'penha-verde',
      'Quinta da Penha Verde',
      'heritage',
      38.7925,
      -9.4078,
      12,
      'Estate of the viceroy João de Castro, planted with India’s first trees in Europe. Quest: find his chapels in the wood.',
    ],
    [
      'chalet-biester',
      'Chalet Biester',
      'heritage',
      38.795,
      -9.3978,
      25,
      'A Gothic-Revival chalet of the 1880s, painted inside by Luigi Manini. Quest: frame its slate turrets through the trees.',
    ],
    [
      'santa-maria',
      'Santa Maria Church',
      'culture',
      38.796,
      -9.386,
      60,
      'Founded after Afonso Henriques took Sintra in 1147, with a Manueline portal. Quest: find the tomb slabs in the floor.',
    ],
    [
      'natural-history',
      'Sintra Natural History Museum',
      'culture',
      38.7995,
      -9.388,
      80,
      'Fossils and minerals in a 19th-century house on the old square. Quest: find the dinosaur egg.',
    ],
    [
      'fonte-pipa',
      'Fonte da Pipa',
      'art',
      38.7948,
      -9.3898,
      40,
      'An azulejo-clad fountain where villagers once filled their jugs. Quest: read the date painted in its tiles.',
    ],
    [
      'volta-duche',
      'Volta do Duche Tile Benches',
      'art',
      38.7997,
      -9.3848,
      150,
      'The Romantic promenade into town, lined with tiled benches. Quest: find a bench with a view of the Moorish walls.',
    ],
    [
      'olga-cadaval',
      'Olga Cadaval Cultural Centre',
      'music_events',
      38.7999,
      -9.3786,
      400,
      'Named after the duchess who brought Europe’s musicians to Sintra. Quest: catch a concert or the festival poster.',
    ],
    [
      'casa-teatro',
      'Casa de Teatro de Sintra',
      'music_events',
      38.7976,
      -9.383,
      80,
      'A small theatre company’s home in Estefânia. Quest: find out what’s on tonight.',
    ],
    [
      'feira-merces',
      'Feira das Mercês',
      'music_events',
      38.7835,
      -9.316,
      120,
      'Sintra’s oldest country fair, held around a hilltop chapel every autumn. Quest: find the chapel on the fairground.',
    ],
    [
      'colares-adega',
      'Adega Regional de Colares',
      'music_events',
      38.7995,
      -9.4475,
      90,
      'Cellars of the Ramisco vines that survived phylloxera in sand. Quest: join a harvest-time tasting or event.',
    ],
    [
      'tram-banzao',
      'Banzão Tram Stop',
      'travel',
      38.8128,
      -9.4505,
      70,
      'The 1904 tram still rattles through the vineyards here. Quest: wait for the bell and photograph the car.',
    ],
    [
      'tram-galamares',
      'Galamares Tram Stop',
      'travel',
      38.8003,
      -9.4155,
      40,
      'A halt on the old line from the hills to the sea. Quest: ride one stop towards the coast.',
    ],
    [
      'portela-station',
      'Portela de Sintra Station',
      'travel',
      38.802,
      -9.3667,
      200,
      'Where the Lisbon line meets the town’s new quarter. Quest: find the tile panel in the hall.',
    ],
    [
      'piriquita',
      'Piriquita Bakery',
      'other',
      38.7978,
      -9.3925,
      1500,
      'Bakers since 1862, said to have named the queijada for a king. Quest: order a travesseiro, still warm.',
    ],
    [
      'sao-pedro-fair',
      'São Pedro Fair',
      'other',
      38.788,
      -9.377,
      300,
      'A market held on the 2nd and 4th Sunday since the Middle Ages. Quest: find something old and something edible.',
    ],
    [
      'azoia',
      'Azóia Village',
      'other',
      38.766,
      -9.479,
      50,
      'The westernmost village of mainland Europe. Quest: find the café the lighthouse keepers used.',
    ],
    [
      'janas-chapel',
      'Round Chapel of Janas',
      'other',
      38.8125,
      -9.4215,
      30,
      'A circular chapel where farmers still bless their animals each August. Quest: walk once around it.',
    ],
    [
      'dino-footprints',
      'Praia Grande Dinosaur Footprints',
      'other',
      38.813,
      -9.479,
      200,
      'Tracks left 120 million years ago on a cliff that was once a beach. Quest: find the trackway at the south end.',
    ],
  ]),

  ...quests('lisbon', [
    [
      'carcavelos',
      'Carcavelos Beach',
      'coast',
      38.679,
      -9.3365,
      3000,
      'Lisbon’s surf beach beneath the star-shaped fort of São Julião. Quest: watch a set roll in by the fort.',
    ],
    [
      'praia-caxias',
      'Caxias Beach',
      'coast',
      38.6997,
      -9.2765,
      200,
      'A small beach by the old royal estate. Quest: spot the lighthouse on the Bugio fort offshore.',
    ],
    [
      'caparica',
      'Costa da Caparica',
      'coast',
      38.644,
      -9.2395,
      2500,
      'Fishermen hauled nets here long before the surfers came. Quest: catch the little beach train south.',
    ],
    [
      'ribeira-das-naus',
      'Ribeira das Naus',
      'coast',
      38.7066,
      -9.142,
      1500,
      'The royal shipyard that built the fleets of the Discoveries. Quest: sit on the river steps at sunset.',
    ],
    [
      'paco-de-arcos',
      'Paço de Arcos Beach',
      'coast',
      38.6925,
      -9.293,
      150,
      'A fishing village beach below a 15th-century royal house. Quest: find the old pier.',
    ],
    [
      'tapada-necessidades',
      'Tapada das Necessidades',
      'nature',
      38.7105,
      -9.1665,
      120,
      'A royal walled garden with a cactus garden and a round greenhouse. Quest: find the cactus garden.',
    ],
    [
      'queluz',
      'Queluz National Palace',
      'heritage',
      38.7505,
      -9.2545,
      900,
      'The pink rococo palace of the Braganzas, Portugal’s little Versailles. Quest: walk the azulejo-lined canal.',
    ],
    [
      'paco-caxias',
      'Caxias Royal Palace',
      'heritage',
      38.7012,
      -9.2738,
      20,
      'A royal summer house with cascading gardens and a grotto. Quest: find the waterfall of statues.',
    ],
    [
      'fronteira',
      'Fronteira Palace',
      'heritage',
      38.7405,
      -9.1835,
      60,
      'A 17th-century hunting palace with the finest azulejo gardens in Lisbon. Quest: find the Gallery of Kings.',
    ],
    [
      'ajuda',
      'Ajuda National Palace',
      'heritage',
      38.7075,
      -9.1985,
      300,
      'The unfinished royal palace, left as it was in 1910. Quest: find the room of Saxony porcelain.',
    ],
    [
      'necessidades',
      'Necessidades Palace',
      'heritage',
      38.708,
      -9.1695,
      40,
      'The pink palace the last king fled from in 1910, now the Foreign Ministry. Quest: photograph its obelisk fountain.',
    ],
    [
      'pombal-oeiras',
      'Marquis of Pombal Palace, Oeiras',
      'heritage',
      38.694,
      -9.312,
      30,
      'Country seat of the man who rebuilt Lisbon after 1755. Quest: find the waterfall in the gardens.',
    ],
    [
      'museu-lisboa',
      'Lisbon Museum – Pimenta Palace',
      'culture',
      38.757,
      -9.157,
      150,
      'The city’s story told in a palace where peacocks roam. Quest: find the model of Lisbon before the earthquake.',
    ],
    [
      'oriente',
      'Museu do Oriente',
      'culture',
      38.7038,
      -9.1735,
      200,
      'Portugal’s Asian encounters, in an old salt-cod warehouse. Quest: find the Chinese opera masks.',
    ],
    [
      'mnaa',
      'National Museum of Ancient Art',
      'art',
      38.705,
      -9.161,
      500,
      'Portugal’s greatest paintings, in the palace of the counts of Alvor. Quest: find Bosch’s Temptations.',
    ],
    [
      'pomar',
      'Júlio Pomar Studio Museum',
      'art',
      38.7108,
      -9.1527,
      90,
      'A warehouse turned studio by one of Portugal’s great modern painters. Quest: find a portrait of Fernando Pessoa.',
    ],
    [
      'coliseu',
      'Coliseu dos Recreios',
      'music_events',
      38.7155,
      -9.1405,
      600,
      'A 1890 iron-domed hall that has hosted circuses, opera and rock. Quest: look up at the dome.',
    ],
    [
      'hot-clube',
      'Hot Clube de Portugal',
      'music_events',
      38.7195,
      -9.145,
      150,
      'One of Europe’s oldest jazz clubs, since 1948. Quest: catch a late set.',
    ],
    [
      'sao-carlos',
      'São Carlos National Theatre',
      'music_events',
      38.7095,
      -9.1418,
      200,
      'An opera house of 1793 built by merchants in three months. Quest: find the square where Pessoa was born.',
    ],
    [
      'casa-independente',
      'Casa Independente',
      'music_events',
      38.7195,
      -9.136,
      150,
      'A faded palace with gigs in its courtyard. Quest: find the courtyard bar.',
    ],
    [
      'bica',
      'Elevador da Bica',
      'travel',
      38.7086,
      -9.147,
      800,
      'A funicular of 1892 climbing a steep, washing-hung street. Quest: photograph it with the river behind.',
    ],
    [
      'gloria',
      'Elevador da Glória',
      'travel',
      38.7155,
      -9.144,
      900,
      'The funicular from Restauradores to the São Pedro de Alcântara viewpoint. Quest: ride it up, walk down.',
    ],
    [
      'pilar-7',
      'Pillar 7 Bridge Experience',
      'travel',
      38.6945,
      -9.1755,
      300,
      'Inside a pillar of the 25 de Abril bridge. Quest: stand on the glass deck as the trains pass.',
    ],
    [
      'pasteis-belem',
      'Pastéis de Belém',
      'other',
      38.6975,
      -9.2032,
      4000,
      'The custard tarts of the Jerónimos monks, made to a secret recipe since 1837. Quest: eat one with cinnamon.',
    ],
    [
      'feira-ladra',
      'Feira da Ladra',
      'other',
      38.715,
      -9.127,
      800,
      'The Thieves’ Market, held since the 13th century. Quest: find an old azulejo tile.',
    ],
    [
      'aqueduct',
      'Águas Livres Aqueduct',
      'other',
      38.73,
      -9.168,
      300,
      'Its arches survived the 1755 earthquake that flattened the city. Quest: walk along the top.',
    ],
    [
      'ginjinha',
      'A Ginjinha',
      'other',
      38.714,
      -9.138,
      1200,
      'A doorway bar pouring cherry liqueur since 1840. Quest: ask for it “com elas”, with the cherries.',
    ],
    [
      'pink-street',
      'Pink Street',
      'other',
      38.7068,
      -9.144,
      900,
      'Once the sailors’ red-light street, now painted pink. Quest: find a bar named after an old brothel.',
    ],
  ]),

  ...quests('porto', [
    [
      'matosinhos',
      'Matosinhos Beach',
      'coast',
      41.176,
      -8.69,
      2000,
      'Porto’s fishing harbour beach, under Janet Echelman’s giant net sculpture. Quest: find “She Changes”.',
    ],
    [
      'homem-do-leme',
      'Homem do Leme Beach',
      'coast',
      41.16,
      -8.683,
      400,
      'Named for the statue of a helmsman steering towards the Atlantic. Quest: find the helmsman.',
    ],
    [
      'ingleses',
      'Praia dos Ingleses',
      'coast',
      41.1545,
      -8.68,
      200,
      'Where the English port merchants bathed in the 19th century. Quest: find the beach’s little pergola.',
    ],
    [
      'afurada',
      'Afurada Fishing Village',
      'coast',
      41.143,
      -8.65,
      300,
      'A fishing village where washing still dries in public tanks. Quest: find the communal laundry.',
    ],
    [
      'botanic',
      'Porto Botanic Garden',
      'nature',
      41.153,
      -8.643,
      150,
      'The garden of the Andresen family, where the poet Sophia grew up. Quest: find the cactus house.',
    ],
    [
      'freixo',
      'Freixo Palace',
      'heritage',
      41.145,
      -8.585,
      40,
      'A baroque riverside palace by Nasoni, architect of the Clérigos tower. Quest: see it from the river path.',
    ],
    [
      'serra-pilar',
      'Serra do Pilar Monastery',
      'heritage',
      41.1385,
      -8.6085,
      500,
      'A round monastery church that Wellington used to cross the Douro in 1809. Quest: walk the cloister.',
    ],
    [
      'macieirinha',
      'Quinta da Macieirinha',
      'heritage',
      41.147,
      -8.628,
      30,
      'Where an exiled Sardinian king died in 1849, now the Romantic Museum. Quest: find the king’s bedroom.',
    ],
    [
      'cpf',
      'Portuguese Centre of Photography',
      'culture',
      41.144,
      -8.617,
      300,
      'Photographs in the old jail where the writer Camilo Castelo Branco was locked up. Quest: find his cell.',
    ],
    [
      'santa-clara',
      'Santa Clara Church',
      'culture',
      41.1418,
      -8.6082,
      80,
      'A plain front hiding one of the richest gilded interiors in Portugal. Quest: step in and look up.',
    ],
    [
      'almas',
      'Chapel of the Souls',
      'art',
      41.1497,
      -8.6065,
      900,
      'Covered in 15,947 blue-and-white tiles of saints’ lives. Quest: find Saint Francis.',
    ],
    [
      'carmo',
      'Carmo Church Tile Wall',
      'art',
      41.1475,
      -8.6165,
      700,
      'A whole side wall of azulejos telling the story of the Carmelites. Quest: find the hidden house between two churches.',
    ],
    [
      'casa-musica',
      'Casa da Música',
      'music_events',
      41.1588,
      -8.6307,
      600,
      'Rem Koolhaas’s faceted concert hall of 2005. Quest: find the tiled room inside.',
    ],
    [
      'tnsj',
      'São João National Theatre',
      'music_events',
      41.143,
      -8.6075,
      200,
      'A neo-classical theatre of 1920 on the Batalha square. Quest: find the masks on its front.',
    ],
    [
      'maus-habitos',
      'Maus Hábitos',
      'music_events',
      41.1488,
      -8.6045,
      150,
      'A rooftop arts club on the fourth floor of a garage building. Quest: find the terrace.',
    ],
    [
      'rivoli',
      'Rivoli Theatre',
      'music_events',
      41.149,
      -8.611,
      300,
      'An art deco theatre of 1932 on the Praça D. João I. Quest: find its deco lettering.',
    ],
    [
      'casa-guitarra',
      'Casa da Guitarra',
      'music_events',
      41.1415,
      -8.6115,
      150,
      'A guitar shop where fado is played at night. Quest: hear the Portuguese guitar.',
    ],
    [
      'maria-pia',
      'Maria Pia Bridge',
      'travel',
      41.1395,
      -8.597,
      150,
      'Eiffel’s company spanned the Douro with this iron arch in 1877. Quest: photograph the arch from the river.',
    ],
    [
      'tram-museum',
      'Porto Tram Museum',
      'travel',
      41.147,
      -8.6345,
      200,
      'Old trams in a former power station. Quest: find the oldest car.',
    ],
    [
      'gaia-cable-car',
      'Gaia Cable Car',
      'travel',
      41.1375,
      -8.607,
      600,
      'A short glide over the port lodges. Quest: count the lodge roofs you can read.',
    ],
    [
      'majestic',
      'Majestic Café',
      'other',
      41.1468,
      -8.6065,
      2000,
      'A Belle Époque café of 1921, all mirrors and carved wood. Quest: order a rabanada.',
    ],
    [
      'santiago',
      'Café Santiago',
      'other',
      41.148,
      -8.603,
      800,
      'Locals queue here for the francesinha, Porto’s monstrous sandwich. Quest: finish one.',
    ],
    [
      'grahams',
      'Graham’s Port Lodge',
      'other',
      41.1365,
      -8.624,
      400,
      'A lodge of 1890 with a view over the whole Ribeira. Quest: taste a tawny.',
    ],
    [
      'codecal',
      'Codeçal Steps',
      'other',
      41.1408,
      -8.607,
      60,
      'A steep stair beside the old city wall. Quest: count the steps.',
    ],
    [
      'galerias-paris',
      'Rua Galeria de Paris',
      'other',
      41.1468,
      -8.6135,
      400,
      'A street of old shops turned bars, busiest after midnight. Quest: find the bar full of old toys.',
    ],
  ]),
];
