import { quests } from '../place-in';

// Side quests written as a travelling historian would brief you: a line of history, then what to
// go and find. Heritage leans on the quieter palaces and quintas rather than the famous queues.

export const IBERIA_QUESTS = [
  ...quests('sintra', [
    [
      'praia-macas',
      'Praia das Maçãs',
      'coast',
      38.8262,
      -9.47,
      900,
      'Where Lisbon’s Belle Époque day-trippers stepped off the tram. Quest: find the tidal sea pool at the north end.',
    ],
    [
      'praia-ursa',
      'Praia da Ursa',
      'coast',
      38.7893,
      -9.495,
      60,
      'A wild cove under Cabo da Roca, reached only on foot. Quest: spot the rock the fishermen named the She-Bear.',
    ],
    [
      'monserrate-ferns',
      'Monserrate Fern Valley',
      'nature',
      38.7934,
      -9.4218,
      300,
      'Francis Cook’s Victorian plant collectors filled this ravine with tree ferns. Quest: stand beneath the tallest frond.',
    ],
    [
      'quinta-relogio',
      'Quinta do Relógio',
      'heritage',
      38.7972,
      -9.3936,
      15,
      'A neo-Moorish quinta of 1860 where King Carlos spent his honeymoon. Quest: photograph its horseshoe arches from the road.',
    ],
    [
      'penha-verde',
      'Quinta da Penha Verde',
      'heritage',
      38.7925,
      -9.4078,
      12,
      'Estate of the viceroy João de Castro, planted with India’s first trees in Europe. Quest: find his chapels in the wood.',
    ],
    [
      'chalet-biester',
      'Chalet Biester',
      'heritage',
      38.795,
      -9.3978,
      25,
      'A Gothic-Revival chalet of the 1880s, painted inside by Luigi Manini. Quest: frame its slate turrets through the trees.',
    ],
    [
      'santa-maria',
      'Santa Maria Church',
      'culture',
      38.796,
      -9.386,
      60,
      'Founded after Afonso Henriques took Sintra in 1147, with a Manueline portal. Quest: find the tomb slabs in the floor.',
    ],
    [
      'natural-history',
      'Sintra Natural History Museum',
      'culture',
      38.7995,
      -9.388,
      80,
      'Fossils and minerals in a 19th-century house on the old square. Quest: find the dinosaur egg.',
    ],
    [
      'fonte-pipa',
      'Fonte da Pipa',
      'art',
      38.7948,
      -9.3898,
      40,
      'An azulejo-clad fountain where villagers once filled their jugs. Quest: read the date painted in its tiles.',
    ],
    [
      'volta-duche',
      'Volta do Duche Tile Benches',
      'art',
      38.7997,
      -9.3848,
      150,
      'The Romantic promenade into town, lined with tiled benches. Quest: find a bench with a view of the Moorish walls.',
    ],
    [
      'olga-cadaval',
      'Olga Cadaval Cultural Centre',
      'music_events',
      38.7999,
      -9.3786,
      400,
      'Named after the duchess who brought Europe’s musicians to Sintra. Quest: catch a concert or the festival poster.',
    ],
    [
      'casa-teatro',
      'Casa de Teatro de Sintra',
      'music_events',
      38.7976,
      -9.383,
      80,
      'A small theatre company’s home in Estefânia. Quest: find out what’s on tonight.',
    ],
    [
      'feira-merces',
      'Feira das Mercês',
      'music_events',
      38.7835,
      -9.316,
      120,
      'Sintra’s oldest country fair, held around a hilltop chapel every autumn. Quest: find the chapel on the fairground.',
    ],
    [
      'colares-adega',
      'Adega Regional de Colares',
      'music_events',
      38.7995,
      -9.4475,
      90,
      'Cellars of the Ramisco vines that survived phylloxera in sand. Quest: join a harvest-time tasting or event.',
    ],
    [
      'tram-banzao',
      'Banzão Tram Stop',
      'travel',
      38.8128,
      -9.4505,
      70,
      'The 1904 tram still rattles through the vineyards here. Quest: wait for the bell and photograph the car.',
    ],
    [
      'tram-galamares',
      'Galamares Tram Stop',
      'travel',
      38.8003,
      -9.4155,
      40,
      'A halt on the old line from the hills to the sea. Quest: ride one stop towards the coast.',
    ],
    [
      'portela-station',
      'Portela de Sintra Station',
      'travel',
      38.802,
      -9.3667,
      200,
      'Where the Lisbon line meets the town’s new quarter. Quest: find the tile panel in the hall.',
    ],
    [
      'piriquita',
      'Piriquita Bakery',
      'other',
      38.7978,
      -9.3925,
      1500,
      'Bakers since 1862, said to have named the queijada for a king. Quest: order a travesseiro, still warm.',
    ],
    [
      'sao-pedro-fair',
      'São Pedro Fair',
      'other',
      38.788,
      -9.377,
      300,
      'A market held on the 2nd and 4th Sunday since the Middle Ages. Quest: find something old and something edible.',
    ],
    [
      'azoia',
      'Azóia Village',
      'other',
      38.766,
      -9.479,
      50,
      'The westernmost village of mainland Europe. Quest: find the café the lighthouse keepers used.',
    ],
    [
      'janas-chapel',
      'Round Chapel of Janas',
      'other',
      38.8125,
      -9.4215,
      30,
      'A circular chapel where farmers still bless their animals each August. Quest: walk once around it.',
    ],
    [
      'dino-footprints',
      'Praia Grande Dinosaur Footprints',
      'other',
      38.813,
      -9.479,
      200,
      'Tracks left 120 million years ago on a cliff that was once a beach. Quest: find the trackway at the south end.',
    ],
  ]),

  ...quests('lisbon', [
    [
      'carcavelos',
      'Carcavelos Beach',
      'coast',
      38.679,
      -9.3365,
      3000,
      'Lisbon’s surf beach beneath the star-shaped fort of São Julião. Quest: watch a set roll in by the fort.',
    ],
    [
      'praia-caxias',
      'Caxias Beach',
      'coast',
      38.6997,
      -9.2765,
      200,
      'A small beach by the old royal estate. Quest: spot the lighthouse on the Bugio fort offshore.',
    ],
    [
      'caparica',
      'Costa da Caparica',
      'coast',
      38.644,
      -9.2395,
      2500,
      'Fishermen hauled nets here long before the surfers came. Quest: catch the little beach train south.',
    ],
    [
      'ribeira-das-naus',
      'Ribeira das Naus',
      'coast',
      38.7066,
      -9.142,
      1500,
      'The royal shipyard that built the fleets of the Discoveries. Quest: sit on the river steps at sunset.',
    ],
    [
      'paco-de-arcos',
      'Paço de Arcos Beach',
      'coast',
      38.6925,
      -9.293,
      150,
      'A fishing village beach below a 15th-century royal house. Quest: find the old pier.',
    ],
    [
      'tapada-necessidades',
      'Tapada das Necessidades',
      'nature',
      38.7105,
      -9.1665,
      120,
      'A royal walled garden with a cactus garden and a round greenhouse. Quest: find the cactus garden.',
    ],
    [
      'queluz',
      'Queluz National Palace',
      'heritage',
      38.7505,
      -9.2545,
      900,
      'The pink rococo palace of the Braganzas, Portugal’s little Versailles. Quest: walk the azulejo-lined canal.',
    ],
    [
      'paco-caxias',
      'Caxias Royal Palace',
      'heritage',
      38.7012,
      -9.2738,
      20,
      'A royal summer house with cascading gardens and a grotto. Quest: find the waterfall of statues.',
    ],
    [
      'fronteira',
      'Fronteira Palace',
      'heritage',
      38.7405,
      -9.1835,
      60,
      'A 17th-century hunting palace with the finest azulejo gardens in Lisbon. Quest: find the Gallery of Kings.',
    ],
    [
      'ajuda',
      'Ajuda National Palace',
      'heritage',
      38.7075,
      -9.1985,
      300,
      'The unfinished royal palace, left as it was in 1910. Quest: find the room of Saxony porcelain.',
    ],
    [
      'necessidades',
      'Necessidades Palace',
      'heritage',
      38.708,
      -9.1695,
      40,
      'The pink palace the last king fled from in 1910, now the Foreign Ministry. Quest: photograph its obelisk fountain.',
    ],
    [
      'pombal-oeiras',
      'Marquis of Pombal Palace, Oeiras',
      'heritage',
      38.694,
      -9.312,
      30,
      'Country seat of the man who rebuilt Lisbon after 1755. Quest: find the waterfall in the gardens.',
    ],
    [
      'museu-lisboa',
      'Lisbon Museum – Pimenta Palace',
      'culture',
      38.757,
      -9.157,
      150,
      'The city’s story told in a palace where peacocks roam. Quest: find the model of Lisbon before the earthquake.',
    ],
    [
      'oriente',
      'Museu do Oriente',
      'culture',
      38.7038,
      -9.1735,
      200,
      'Portugal’s Asian encounters, in an old salt-cod warehouse. Quest: find the Chinese opera masks.',
    ],
    [
      'mnaa',
      'National Museum of Ancient Art',
      'art',
      38.705,
      -9.161,
      500,
      'Portugal’s greatest paintings, in the palace of the counts of Alvor. Quest: find Bosch’s Temptations.',
    ],
    [
      'pomar',
      'Júlio Pomar Studio Museum',
      'art',
      38.7108,
      -9.1527,
      90,
      'A warehouse turned studio by one of Portugal’s great modern painters. Quest: find a portrait of Fernando Pessoa.',
    ],
    [
      'coliseu',
      'Coliseu dos Recreios',
      'music_events',
      38.7155,
      -9.1405,
      600,
      'A 1890 iron-domed hall that has hosted circuses, opera and rock. Quest: look up at the dome.',
    ],
    [
      'hot-clube',
      'Hot Clube de Portugal',
      'music_events',
      38.7195,
      -9.145,
      150,
      'One of Europe’s oldest jazz clubs, since 1948. Quest: catch a late set.',
    ],
    [
      'sao-carlos',
      'São Carlos National Theatre',
      'music_events',
      38.7095,
      -9.1418,
      200,
      'An opera house of 1793 built by merchants in three months. Quest: find the square where Pessoa was born.',
    ],
    [
      'casa-independente',
      'Casa Independente',
      'music_events',
      38.7195,
      -9.136,
      150,
      'A faded palace with gigs in its courtyard. Quest: find the courtyard bar.',
    ],
    [
      'bica',
      'Elevador da Bica',
      'travel',
      38.7086,
      -9.147,
      800,
      'A funicular of 1892 climbing a steep, washing-hung street. Quest: photograph it with the river behind.',
    ],
    [
      'gloria',
      'Elevador da Glória',
      'travel',
      38.7155,
      -9.144,
      900,
      'The funicular from Restauradores to the São Pedro de Alcântara viewpoint. Quest: ride it up, walk down.',
    ],
    [
      'pilar-7',
      'Pillar 7 Bridge Experience',
      'travel',
      38.6945,
      -9.1755,
      300,
      'Inside a pillar of the 25 de Abril bridge. Quest: stand on the glass deck as the trains pass.',
    ],
    [
      'pasteis-belem',
      'Pastéis de Belém',
      'other',
      38.6975,
      -9.2032,
      4000,
      'The custard tarts of the Jerónimos monks, made to a secret recipe since 1837. Quest: eat one with cinnamon.',
    ],
    [
      'feira-ladra',
      'Feira da Ladra',
      'other',
      38.715,
      -9.127,
      800,
      'The Thieves’ Market, held since the 13th century. Quest: find an old azulejo tile.',
    ],
    [
      'aqueduct',
      'Águas Livres Aqueduct',
      'other',
      38.73,
      -9.168,
      300,
      'Its arches survived the 1755 earthquake that flattened the city. Quest: walk along the top.',
    ],
    [
      'ginjinha',
      'A Ginjinha',
      'other',
      38.714,
      -9.138,
      1200,
      'A doorway bar pouring cherry liqueur since 1840. Quest: ask for it “com elas”, with the cherries.',
    ],
    [
      'pink-street',
      'Pink Street',
      'other',
      38.7068,
      -9.144,
      900,
      'Once the sailors’ red-light street, now painted pink. Quest: find a bar named after an old brothel.',
    ],
  ]),

  ...quests('porto', [
    [
      'matosinhos',
      'Matosinhos Beach',
      'coast',
      41.176,
      -8.69,
      2000,
      'Porto’s fishing harbour beach, under Janet Echelman’s giant net sculpture. Quest: find “She Changes”.',
    ],
    [
      'homem-do-leme',
      'Homem do Leme Beach',
      'coast',
      41.16,
      -8.683,
      400,
      'Named for the statue of a helmsman steering towards the Atlantic. Quest: find the helmsman.',
    ],
    [
      'ingleses',
      'Praia dos Ingleses',
      'coast',
      41.1545,
      -8.68,
      200,
      'Where the English port merchants bathed in the 19th century. Quest: find the beach’s little pergola.',
    ],
    [
      'afurada',
      'Afurada Fishing Village',
      'coast',
      41.143,
      -8.65,
      300,
      'A fishing village where washing still dries in public tanks. Quest: find the communal laundry.',
    ],
    [
      'botanic',
      'Porto Botanic Garden',
      'nature',
      41.153,
      -8.643,
      150,
      'The garden of the Andresen family, where the poet Sophia grew up. Quest: find the cactus house.',
    ],
    [
      'freixo',
      'Freixo Palace',
      'heritage',
      41.145,
      -8.585,
      40,
      'A baroque riverside palace by Nasoni, architect of the Clérigos tower. Quest: see it from the river path.',
    ],
    [
      'serra-pilar',
      'Serra do Pilar Monastery',
      'heritage',
      41.1385,
      -8.6085,
      500,
      'A round monastery church that Wellington used to cross the Douro in 1809. Quest: walk the cloister.',
    ],
    [
      'macieirinha',
      'Quinta da Macieirinha',
      'heritage',
      41.147,
      -8.628,
      30,
      'Where an exiled Sardinian king died in 1849, now the Romantic Museum. Quest: find the king’s bedroom.',
    ],
    [
      'cpf',
      'Portuguese Centre of Photography',
      'culture',
      41.144,
      -8.617,
      300,
      'Photographs in the old jail where the writer Camilo Castelo Branco was locked up. Quest: find his cell.',
    ],
    [
      'santa-clara',
      'Santa Clara Church',
      'culture',
      41.1418,
      -8.6082,
      80,
      'A plain front hiding one of the richest gilded interiors in Portugal. Quest: step in and look up.',
    ],
    [
      'almas',
      'Chapel of the Souls',
      'art',
      41.1497,
      -8.6065,
      900,
      'Covered in 15,947 blue-and-white tiles of saints’ lives. Quest: find Saint Francis.',
    ],
    [
      'carmo',
      'Carmo Church Tile Wall',
      'art',
      41.1475,
      -8.6165,
      700,
      'A whole side wall of azulejos telling the story of the Carmelites. Quest: find the hidden house between two churches.',
    ],
    [
      'casa-musica',
      'Casa da Música',
      'music_events',
      41.1588,
      -8.6307,
      600,
      'Rem Koolhaas’s faceted concert hall of 2005. Quest: find the tiled room inside.',
    ],
    [
      'tnsj',
      'São João National Theatre',
      'music_events',
      41.143,
      -8.6075,
      200,
      'A neo-classical theatre of 1920 on the Batalha square. Quest: find the masks on its front.',
    ],
    [
      'maus-habitos',
      'Maus Hábitos',
      'music_events',
      41.1488,
      -8.6045,
      150,
      'A rooftop arts club on the fourth floor of a garage building. Quest: find the terrace.',
    ],
    [
      'rivoli',
      'Rivoli Theatre',
      'music_events',
      41.149,
      -8.611,
      300,
      'An art deco theatre of 1932 on the Praça D. João I. Quest: find its deco lettering.',
    ],
    [
      'casa-guitarra',
      'Casa da Guitarra',
      'music_events',
      41.1415,
      -8.6115,
      150,
      'A guitar shop where fado is played at night. Quest: hear the Portuguese guitar.',
    ],
    [
      'maria-pia',
      'Maria Pia Bridge',
      'travel',
      41.1395,
      -8.597,
      150,
      'Eiffel’s company spanned the Douro with this iron arch in 1877. Quest: photograph the arch from the river.',
    ],
    [
      'tram-museum',
      'Porto Tram Museum',
      'travel',
      41.147,
      -8.6345,
      200,
      'Old trams in a former power station. Quest: find the oldest car.',
    ],
    [
      'gaia-cable-car',
      'Gaia Cable Car',
      'travel',
      41.1375,
      -8.607,
      600,
      'A short glide over the port lodges. Quest: count the lodge roofs you can read.',
    ],
    [
      'majestic',
      'Majestic Café',
      'other',
      41.1468,
      -8.6065,
      2000,
      'A Belle Époque café of 1921, all mirrors and carved wood. Quest: order a rabanada.',
    ],
    [
      'santiago',
      'Café Santiago',
      'other',
      41.148,
      -8.603,
      800,
      'Locals queue here for the francesinha, Porto’s monstrous sandwich. Quest: finish one.',
    ],
    [
      'grahams',
      'Graham’s Port Lodge',
      'other',
      41.1365,
      -8.624,
      400,
      'A lodge of 1890 with a view over the whole Ribeira. Quest: taste a tawny.',
    ],
    [
      'codecal',
      'Codeçal Steps',
      'other',
      41.1408,
      -8.607,
      60,
      'A steep stair beside the old city wall. Quest: count the steps.',
    ],
    [
      'galerias-paris',
      'Rua Galeria de Paris',
      'other',
      41.1468,
      -8.6135,
      400,
      'A street of old shops turned bars, busiest after midnight. Quest: find the bar full of old toys.',
    ],
  ]),

  ...quests('madrid', [
    [
      'retiro-pond',
      'Retiro Great Pond',
      'coast',
      40.418,
      -3.683,
      2000,
      'Philip IV staged mock sea battles here. Quest: row past the Alfonso XII monument.',
    ],
    [
      'madrid-rio-beach',
      'Madrid Río Urban Beach',
      'coast',
      40.4045,
      -3.72,
      600,
      'Fountains and sand along the reclaimed Manzanares. Quest: cool off in the spray.',
    ],
    [
      'juan-carlos-lake',
      'Juan Carlos I Park Lake',
      'coast',
      40.463,
      -3.608,
      300,
      'A park with a lake and an olive grove on a former airfield. Quest: walk around the lake.',
    ],
    [
      'segovia-bridge',
      'Segovia Bridge',
      'coast',
      40.415,
      -3.721,
      150,
      'Philip II’s granite bridge over the Manzanares. Quest: photograph it from the riverbank.',
    ],
    [
      'toledo-bridge',
      'Toledo Bridge',
      'coast',
      40.404,
      -3.713,
      150,
      'A baroque bridge with statues of Madrid’s patron saints. Quest: find San Isidro.',
    ],
    [
      'capricho',
      'El Capricho Park',
      'nature',
      40.456,
      -3.599,
      200,
      'The Duchess of Osuna’s 18th-century romantic garden. Quest: find the hermit’s house.',
    ],
    [
      'liria',
      'Liria Palace',
      'heritage',
      40.428,
      -3.713,
      40,
      'The Duke of Alba’s private palace, with Goyas and Titians. Quest: see the facade from Calle Princesa.',
    ],
    [
      'descalzas',
      'Descalzas Reales Monastery',
      'heritage',
      40.4185,
      -3.706,
      150,
      'A convent for royal princesses, full of treasures. Quest: find the Rubens tapestries.',
    ],
    [
      'linares',
      'Linares Palace',
      'heritage',
      40.4195,
      -3.6925,
      60,
      'A palace of the 1870s said to be haunted. Quest: find the Casa de América sign.',
    ],
    [
      'cerralbo',
      'Cerralbo Museum',
      'culture',
      40.424,
      -3.7145,
      120,
      'A marquis’s palace left exactly as he furnished it. Quest: find the ballroom.',
    ],
    [
      'sorolla',
      'Sorolla Museum',
      'culture',
      40.4355,
      -3.6925,
      200,
      'The painter’s house and Andalusian garden. Quest: find his studio.',
    ],
    [
      'florida',
      'San Antonio de la Florida',
      'art',
      40.4252,
      -3.727,
      150,
      'Goya painted its dome in 1798 and is buried beneath it. Quest: find his tomb.',
    ],
    [
      'lazaro-galdiano',
      'Lázaro Galdiano Museum',
      'art',
      40.4405,
      -3.6855,
      120,
      'A collector’s mansion of Bosch, Goya and enamels. Quest: find Goya’s witches.',
    ],
    [
      'cafe-central',
      'Café Central',
      'music_events',
      40.4145,
      -3.7005,
      300,
      'A jazz café in an old glass shop. Quest: catch a set.',
    ],
    [
      'corral-moreria',
      'Corral de la Morería',
      'music_events',
      40.4128,
      -3.7145,
      400,
      'A flamenco tablao since 1956. Quest: watch the zapateado.',
    ],
    [
      'zarzuela',
      'Teatro de la Zarzuela',
      'music_events',
      40.4175,
      -3.6965,
      200,
      'Built in 1856 for Spain’s own light opera. Quest: find out what’s on.',
    ],
    [
      'wizink',
      'WiZink Center',
      'music_events',
      40.4235,
      -3.6715,
      500,
      'Madrid’s big indoor arena. Quest: catch a concert.',
    ],
    [
      'las-ventas',
      'Las Ventas',
      'music_events',
      40.432,
      -3.6635,
      400,
      'A neo-Mudéjar ring of 1931 that also hosts concerts. Quest: photograph the tilework.',
    ],
    [
      'chamberi',
      'Chamberí Ghost Station',
      'travel',
      40.4325,
      -3.701,
      200,
      'A metro station closed in 1966 and left as it was. Quest: find the old adverts.',
    ],
    [
      'principe-pio',
      'Príncipe Pío Station',
      'travel',
      40.421,
      -3.72,
      300,
      'An iron station of 1881 turned into a shopping hall. Quest: find the old platform roof.',
    ],
    [
      'railway-museum',
      'Railway Museum (Delicias)',
      'travel',
      40.3985,
      -3.693,
      150,
      'Steam engines in an iron station of 1880. Quest: find the oldest locomotive.',
    ],
    [
      'rastro',
      'El Rastro',
      'other',
      40.4085,
      -3.7075,
      1500,
      'A Sunday flea market for 500 years. Quest: find an old map.',
    ],
    [
      'botin',
      'Sobrino de Botín',
      'other',
      40.4142,
      -3.7085,
      800,
      'The oldest restaurant in the world, says Guinness. Quest: find the old wood oven.',
    ],
    [
      'oso-madrono',
      'Bear and Strawberry Tree',
      'other',
      40.417,
      -3.7035,
      2000,
      'The statue of the city’s coat of arms. Quest: touch the bear.',
    ],
    [
      'lhardy',
      'Lhardy',
      'other',
      40.4163,
      -3.7013,
      400,
      'Since 1839 the consommé is poured from a silver samovar. Quest: pour your own cup.',
    ],
  ]),

  ...quests('barcelona', [
    [
      'bogatell',
      'Bogatell Beach',
      'coast',
      41.3945,
      2.2055,
      800,
      'Built for the 1992 Olympics on old factory land. Quest: walk to the breakwater.',
    ],
    [
      'nova-icaria',
      'Nova Icària Beach',
      'coast',
      41.3905,
      2.2015,
      900,
      'Named for a 19th-century utopian commune. Quest: find the Olympic Port.',
    ],
    [
      'mar-bella',
      'Mar Bella Beach',
      'coast',
      41.399,
      2.2115,
      400,
      'Barcelona’s sporty beach. Quest: watch the sailing boats.',
    ],
    [
      'sant-sebastia',
      'Sant Sebastià Beach',
      'coast',
      41.371,
      2.188,
      800,
      'The city’s oldest beach, by the sail-shaped hotel. Quest: find the old baths.',
    ],
    [
      'ciutadella-lake',
      'Ciutadella Park Cascade',
      'nature',
      41.3895,
      2.1885,
      800,
      'A fountain on which young Gaudí worked. Quest: find the griffins.',
    ],
    [
      'pedralbes',
      'Pedralbes Monastery',
      'heritage',
      41.3955,
      2.1125,
      150,
      'A Gothic convent founded by a queen in 1327. Quest: find the queen’s tomb.',
    ],
    [
      'sant-pau',
      'Sant Pau Recinte Modernista',
      'heritage',
      41.4115,
      2.1745,
      300,
      'Domènech i Montaner’s hospital, a city of pavilions. Quest: find the tunnels.',
    ],
    [
      'palau-guell',
      'Palau Güell',
      'heritage',
      41.379,
      2.1745,
      400,
      'Gaudí’s first great work, with a rooftop of chimneys. Quest: find the red chimney.',
    ],
    [
      'santa-maria-mar',
      'Santa Maria del Mar',
      'culture',
      41.3837,
      2.182,
      1000,
      'The church built by the porters of the port. Quest: find the porter carvings.',
    ],
    [
      'els-quatre-gats',
      'Els Quatre Gats',
      'culture',
      41.3855,
      2.1735,
      600,
      'The café where young Picasso had his first show. Quest: order a coffee.',
    ],
    [
      'tapies',
      'Fundació Antoni Tàpies',
      'art',
      41.3915,
      2.1635,
      200,
      'Tàpies crowned the building with a tangle of wire. Quest: photograph the cloud.',
    ],
    [
      'mnac',
      'MNAC',
      'art',
      41.3685,
      2.1535,
      500,
      'Romanesque murals rescued from Pyrenean churches. Quest: find Christ in Majesty.',
    ],
    [
      'razzmatazz',
      'Razzmatazz',
      'music_events',
      41.3975,
      2.191,
      400,
      'A warehouse club with five rooms. Quest: find the smallest room.',
    ],
    [
      'sala-apolo',
      'Sala Apolo',
      'music_events',
      41.3745,
      2.169,
      300,
      'A ballroom of 1943. Quest: find the balcony.',
    ],
    [
      'magic-fountain',
      'Magic Fountain of Montjuïc',
      'music_events',
      41.371,
      2.1517,
      2000,
      'Fountains that dance to music since 1929. Quest: catch the show.',
    ],
    [
      'jamboree',
      'Jamboree Jazz Club',
      'music_events',
      41.3805,
      2.175,
      300,
      'A cellar jazz club on Plaça Reial since 1960. Quest: find the cellar steps.',
    ],
    [
      'franca',
      'Estació de França',
      'travel',
      41.3845,
      2.1855,
      200,
      'An iron and glass station of 1929. Quest: look up at the roof.',
    ],
    [
      'tramvia-blau',
      'Tramvia Blau',
      'travel',
      41.4115,
      2.1365,
      150,
      'Barcelona’s blue tram climbing to Tibidabo. Quest: find the tram stop.',
    ],
    [
      'funicular-montjuic',
      'Montjuïc Funicular',
      'travel',
      41.375,
      2.168,
      300,
      'A hidden funicular inside the hill. Quest: ride to the top.',
    ],
    [
      'boqueria',
      'La Boqueria',
      'other',
      41.3817,
      2.1717,
      4000,
      'A market since 1217. Quest: find the egg stall.',
    ],
    [
      'sant-felip-neri',
      'Plaça de Sant Felip Neri',
      'other',
      41.3832,
      2.1745,
      600,
      'A quiet square whose church walls still bear 1938 shrapnel scars. Quest: find the marks.',
    ],
    [
      'marsella',
      'Bar Marsella',
      'other',
      41.3785,
      2.172,
      400,
      'Absinthe served the old way since 1820. Quest: watch the sugar cube melt.',
    ],
    [
      'walden',
      'Walden 7',
      'other',
      41.375,
      2.0565,
      50,
      'Ricardo Bofill’s red tower block. Quest: photograph the courtyard.',
    ],
    [
      'sant-antoni',
      'Sant Antoni Market',
      'other',
      41.3785,
      2.162,
      600,
      'An iron market of 1882 with a Sunday book fair. Quest: find an old comic.',
    ],
  ]),

  ...quests('basque', [
    [
      'concha',
      'La Concha Beach',
      'coast',
      43.3175,
      -1.986,
      3000,
      'The shell-shaped bay the royal family made fashionable in the 1880s. Quest: walk the railings.',
    ],
    [
      'zurriola',
      'Zurriola Beach',
      'coast',
      43.3255,
      -1.974,
      1000,
      'San Sebastián’s surf beach. Quest: watch the surfers at sunset.',
    ],
    [
      'gaztelugatxe',
      'San Juan de Gaztelugatxe',
      'coast',
      43.447,
      -2.7845,
      2000,
      'A hermitage on an islet up 241 steps. Quest: ring the bell three times.',
    ],
    [
      'zarautz',
      'Zarautz Beach',
      'coast',
      43.285,
      -2.17,
      600,
      'A long surf beach. Quest: find the old palace on the seafront.',
    ],
    [
      'sopelana',
      'Sopelana Cliffs',
      'coast',
      43.3875,
      -2.9965,
      300,
      'Surf beaches below flysch cliffs. Quest: find the folded rock layers.',
    ],
    [
      'urdaibai',
      'Urdaibai Marshes',
      'nature',
      43.36,
      -2.68,
      200,
      'A biosphere reserve. Quest: spot a heron.',
    ],
    [
      'igueldo',
      'Mount Igueldo',
      'nature',
      43.3095,
      -2.0085,
      800,
      'An old funfair on a hilltop. Quest: ride the old roller coaster.',
    ],
    [
      'urgull',
      'Mount Urgull',
      'nature',
      43.3265,
      -1.9865,
      600,
      'A castle hill with English soldiers’ graves. Quest: find the cemetery.',
    ],
    [
      'artxanda',
      'Mount Artxanda',
      'nature',
      43.2725,
      -2.9225,
      400,
      'Bilbao’s viewpoint hill. Quest: find the giant fork.',
    ],
    [
      'pagasarri',
      'Pagasarri',
      'nature',
      43.225,
      -2.935,
      200,
      'The Bilbaínos’ Sunday hill. Quest: reach the refuge.',
    ],
    [
      'miramar',
      'Miramar Palace',
      'heritage',
      43.3145,
      -1.995,
      100,
      'A royal summer palace of 1893. Quest: walk its lawns.',
    ],
    [
      'gernika-tree',
      'Tree of Gernika',
      'heritage',
      43.3148,
      -2.6785,
      400,
      'Under the oak the Basque assemblies met. Quest: find the old trunk.',
    ],
    [
      'aiete',
      'Aiete Palace',
      'heritage',
      43.3075,
      -1.98,
      30,
      'A summer palace of 1878 where Spanish queens and, later, Franco stayed. Quest: find the pond in its park.',
    ],
    [
      'butron',
      'Butrón Castle',
      'heritage',
      43.3555,
      -2.8515,
      30,
      'A fairytale castle rebuilt in the 19th century. Quest: photograph the towers.',
    ],
    [
      'arteaga',
      'Arteaga Castle',
      'heritage',
      43.3505,
      -2.651,
      20,
      'Napoleon III built it for Empress Eugénie. Quest: find the eagle.',
    ],
    [
      'guggenheim',
      'Guggenheim Bilbao',
      'culture',
      43.2687,
      -2.934,
      4000,
      'Gehry’s titanium ship. Quest: find Puppy.',
    ],
    [
      'san-telmo',
      'San Telmo Museum',
      'culture',
      43.3245,
      -1.983,
      300,
      'A convent turned museum. Quest: find the giant murals.',
    ],
    [
      'euskal-museoa',
      'Basque Museum',
      'culture',
      43.2585,
      -2.9235,
      150,
      'Basque life and the old stone idol. Quest: find the idol of Mikeldi.',
    ],
    [
      'ribera-market',
      'Ribera Market',
      'culture',
      43.2565,
      -2.924,
      400,
      'A deco market on the river. Quest: find the stained glass.',
    ],
    [
      'chillida-leku',
      'Chillida Leku',
      'culture',
      43.279,
      -1.988,
      200,
      'Chillida’s sculpture garden. Quest: find a giant iron.',
    ],
    [
      'peine-viento',
      'Comb of the Wind',
      'art',
      43.3215,
      -2.0055,
      1000,
      'Chillida’s iron claws at the end of the bay. Quest: feel the blowholes.',
    ],
    [
      'bellas-artes',
      'Bilbao Fine Arts Museum',
      'art',
      43.2665,
      -2.9375,
      300,
      'From El Greco to Basque modernism. Quest: find a Zuloaga.',
    ],
    [
      'tabakalera',
      'Tabakalera',
      'art',
      43.3175,
      -1.976,
      200,
      'A tobacco factory turned art centre. Quest: find the rooftop.',
    ],
    [
      'maman',
      'Maman',
      'art',
      43.2685,
      -2.9365,
      1500,
      'Louise Bourgeois’s giant spider. Quest: stand beneath her.',
    ],
    [
      'azkuna',
      'Azkuna Zentroa',
      'art',
      43.2595,
      -2.9395,
      300,
      'A wine warehouse on 43 columns. Quest: find the glass-bottomed pool.',
    ],
    [
      'kursaal',
      'Kursaal',
      'music_events',
      43.3245,
      -1.9785,
      400,
      'Moneo’s two glass cubes. Quest: find the cube in the sea.',
    ],
    [
      'euskalduna',
      'Euskalduna Palace',
      'music_events',
      43.2665,
      -2.9475,
      200,
      'A concert hall shaped like a ship. Quest: find the shipyard crane.',
    ],
    [
      'arriaga',
      'Arriaga Theatre',
      'music_events',
      43.2585,
      -2.9255,
      200,
      'An opera house named after the Basque Mozart. Quest: find the bust.',
    ],
    [
      'bbk-live',
      'Kobetamendi',
      'music_events',
      43.2575,
      -2.9555,
      300,
      'The hill that hosts BBK Live festival. Quest: find the stage.',
    ],
    [
      'jazzaldia',
      'Jazzaldia at Trinidad Square',
      'music_events',
      43.3245,
      -1.9855,
      300,
      'Europe’s oldest jazz festival. Quest: find the square.',
    ],
    [
      'vizcaya-bridge',
      'Vizcaya Bridge',
      'travel',
      43.3235,
      -3.017,
      600,
      'The world’s oldest transporter bridge, 1893. Quest: ride the gondola.',
    ],
    [
      'abando',
      'Abando Station',
      'travel',
      43.2605,
      -2.9265,
      300,
      'A station with a stained-glass window. Quest: find the window.',
    ],
    [
      'igueldo-funicular',
      'Igueldo Funicular',
      'travel',
      43.3075,
      -2.0035,
      600,
      'A funicular of 1912. Quest: ride it.',
    ],
    [
      'zubizuri',
      'Zubizuri Bridge',
      'travel',
      43.2675,
      -2.9285,
      500,
      'Calatrava’s white bridge. Quest: walk across.',
    ],
    [
      'larreineta',
      'Larreineta Funicular',
      'travel',
      43.255,
      -3.0475,
      100,
      'A miners’ funicular. Quest: ride it.',
    ],
    [
      'parte-vieja',
      'Parte Vieja Pintxos',
      'other',
      43.3235,
      -1.985,
      2000,
      'The pintxo bars of San Sebastián. Quest: try a gilda.',
    ],
    [
      'bretxa',
      'La Bretxa Market',
      'other',
      43.3225,
      -1.9835,
      300,
      'Market on the breach the British blew in the walls in 1813. Quest: find the fish hall.',
    ],
    [
      'casco-viejo',
      'Siete Calles',
      'other',
      43.2575,
      -2.9225,
      800,
      'Bilbao’s Seven Streets. Quest: walk all seven.',
    ],
    [
      'gernika-market',
      'Gernika Market',
      'other',
      43.3165,
      -2.676,
      100,
      'A Monday market. Quest: buy a cheese.',
    ],
    [
      'ondarreta',
      'Ondarreta Beach',
      'other',
      43.3185,
      -2.0005,
      400,
      'The quiet end of the bay. Quest: find the tamarinds.',
    ],
    [
      'mallona',
      'Calzadas de Mallona',
      'other',
      43.2585,
      -2.9205,
      5,
      'The 300-odd steps pilgrims climbed from the old town to Begoña. Quest: count them on the way up.',
      'hidden',
    ],
  ]),
];
