import { quests } from '../place-in';

export const NORTH_QUESTS = [
  ...quests('cork', [
    [
      'cobh',
      'Cobh Waterfront',
      'coast',
      51.85,
      -8.295,
      600,
      'The last port of call of the Titanic, and the quay of a million emigrants. Quest: find Annie Moore’s statue.',
    ],
    [
      'crosshaven',
      'Crosshaven',
      'coast',
      51.8025,
      -8.297,
      200,
      'Home of the world’s oldest yacht club, 1720. Quest: count the masts.',
    ],
    [
      'myrtleville',
      'Myrtleville Beach',
      'coast',
      51.784,
      -8.301,
      150,
      'A sheltered cove where locals swim all year. Quest: dip in.',
    ],
    [
      'fountainstown',
      'Fountainstown Beach',
      'coast',
      51.779,
      -8.3105,
      100,
      'A strand at the mouth of the harbour. Quest: spot Roche’s Point lighthouse.',
    ],
    [
      'marina',
      'Marina Park and the Atlantic Pond',
      'coast',
      51.8975,
      -8.4385,
      200,
      'The riverside walk where rowing clubs train. Quest: watch an eight row by.',
    ],
    [
      'fitzgerald',
      'Fitzgerald Park',
      'nature',
      51.8965,
      -8.493,
      400,
      'A park built for the 1902 International Exhibition. Quest: find the Shakey Bridge.',
    ],
    [
      'lee-fields',
      'Lee Fields',
      'nature',
      51.8945,
      -8.515,
      150,
      'Riverside meadows west of the city. Quest: walk to the weir.',
    ],
    [
      'fota-wildlife',
      'Fota Wildlife Park',
      'nature',
      51.892,
      -8.311,
      600,
      'Cheetahs run free on an island estate. Quest: spot a cheetah.',
    ],
    [
      'the-lough',
      'The Lough',
      'nature',
      51.889,
      -8.49,
      150,
      'A lake with a legend of a drowned city. Quest: feed the swans.',
    ],
    [
      'ballincollig',
      'Ballincollig Regional Park',
      'nature',
      51.889,
      -8.585,
      100,
      'A park around old gunpowder mills. Quest: find a mill ruin.',
    ],
    [
      'blarney',
      'Blarney Castle',
      'heritage',
      51.9291,
      -8.5709,
      2000,
      'Kiss the stone for the gift of the gab. Quest: lean back and kiss it.',
    ],
    [
      'fota-house',
      'Fota House',
      'heritage',
      51.8955,
      -8.306,
      80,
      'A Regency house of the Smith-Barrys. Quest: find the servants’ bells.',
    ],
    [
      'blackrock-castle',
      'Blackrock Castle',
      'heritage',
      51.9,
      -8.4025,
      200,
      'A castle built against pirates, now an observatory. Quest: look through a telescope.',
    ],
    [
      'elizabeth-fort',
      'Elizabeth Fort',
      'heritage',
      51.895,
      -8.479,
      150,
      'A star fort of 1601. Quest: walk the ramparts.',
    ],
    [
      'spike-island',
      'Spike Island',
      'heritage',
      51.837,
      -8.287,
      200,
      'A fortress prison called Ireland’s Alcatraz. Quest: find the punishment cells.',
    ],
    [
      'fin-barre',
      'St Fin Barre’s Cathedral',
      'culture',
      51.8945,
      -8.481,
      400,
      'Burges’s Gothic cathedral with a golden angel. Quest: find the cannonball.',
    ],
    [
      'city-gaol',
      'Cork City Gaol',
      'culture',
      51.9,
      -8.4975,
      300,
      'A castle-like prison of 1824. Quest: find the radio studio.',
    ],
    [
      'shandon',
      'Shandon Bells',
      'culture',
      51.903,
      -8.4765,
      600,
      'Ring the bells of St Anne’s. Quest: play a tune.',
    ],
    [
      'titanic',
      'Titanic Experience Cobh',
      'culture',
      51.8492,
      -8.2925,
      400,
      'The White Star Line office. Quest: find your passenger’s fate.',
    ],
    [
      'nano-nagle',
      'Nano Nagle Place',
      'culture',
      51.8945,
      -8.477,
      100,
      'A convent of the lantern lady. Quest: find the garden.',
    ],
    [
      'crawford',
      'Crawford Art Gallery',
      'art',
      51.8995,
      -8.471,
      400,
      'Casts from the Vatican. Quest: find the sculpture gallery.',
    ],
    [
      'glucksman',
      'Glucksman Gallery',
      'art',
      51.8935,
      -8.4915,
      150,
      'A tree-house gallery. Quest: find the river view.',
    ],
    [
      'ogham',
      'Ogham Stone Corridor',
      'art',
      51.8935,
      -8.49,
      50,
      'Ireland’s first writing. Quest: read a name.',
    ],
    [
      'sirius',
      'Sirius Arts Centre',
      'art',
      51.8505,
      -8.3005,
      50,
      'An arts centre in the old yacht club. Quest: find the harbour view.',
    ],
    [
      'rory-gallagher',
      'Rory Gallagher Place',
      'art',
      51.8995,
      -8.4745,
      200,
      'A sculpture for the guitar hero. Quest: find the guitar.',
    ],
    [
      'opera-house',
      'Cork Opera House',
      'music_events',
      51.9005,
      -8.473,
      300,
      'The city’s stage since 1855. Quest: catch a show.',
    ],
    ['sin-e', 'Sin É', 'music_events', 51.903, -8.472, 200, 'A trad pub. Quest: hear a session.'],
    [
      'cyprus-avenue',
      'Cyprus Avenue',
      'music_events',
      51.8975,
      -8.4705,
      150,
      'A gig venue upstairs. Quest: catch a gig.',
    ],
    [
      'st-lukes',
      'Live at St Luke’s',
      'music_events',
      51.9055,
      -8.4625,
      100,
      'Gigs in a church. Quest: find the stained glass.',
    ],
    [
      'everyman',
      'Everyman Theatre',
      'music_events',
      51.8995,
      -8.4655,
      150,
      'A Victorian theatre. Quest: find the dome.',
    ],
    [
      'kent-station',
      'Kent Station',
      'travel',
      51.9015,
      -8.458,
      200,
      'A steam engine of 1848 waits in the hall. Quest: find No. 36.',
    ],
    [
      'fota-station',
      'Fota Station',
      'travel',
      51.896,
      -8.3175,
      50,
      'A halt in the estuary. Quest: watch the harbour train.',
    ],
    [
      'passage-ferry',
      'Passage West Ferry',
      'travel',
      51.827,
      -8.328,
      50,
      'A car ferry across the harbour. Quest: ride it.',
    ],
    [
      'blackrock-greenway',
      'Blackrock Railway Greenway',
      'travel',
      51.898,
      -8.4155,
      100,
      'The old Passage railway, now a path. Quest: find the old station.',
    ],
    [
      'deepwater-quay',
      'Deepwater Quay',
      'travel',
      51.8505,
      -8.2985,
      100,
      'Where Lusitania survivors landed. Quest: find the memorial.',
    ],
    [
      'english-market',
      'English Market',
      'other',
      51.8978,
      -8.474,
      1500,
      'A market since 1788. Quest: try drisheen.',
    ],
    [
      'franciscan-well',
      'Franciscan Well',
      'other',
      51.901,
      -8.4825,
      300,
      'A brewery on a holy well. Quest: find the well.',
    ],
    [
      'deck-of-cards',
      'Deck of Cards, Cobh',
      'other',
      51.852,
      -8.2985,
      300,
      'A row of colourful houses. Quest: photograph them with the cathedral.',
    ],
    [
      'coal-quay',
      'Coal Quay Market',
      'other',
      51.9,
      -8.477,
      100,
      'A Saturday market. Quest: buy something.',
    ],
    [
      'oliver-plunkett',
      'Oliver Plunkett Street',
      'other',
      51.898,
      -8.4675,
      300,
      'A street of shops. Quest: find the umbrellas.',
    ],
    [
      'red-abbey',
      'Red Abbey Tower',
      'other',
      51.8955,
      -8.47,
      10,
      'The last medieval building in Cork. Quest: find it in its courtyard.',
      'hidden',
    ],
  ]),

  ...quests('stockholm', [
    [
      'langholmen',
      'Långholmen Beach',
      'coast',
      59.321,
      18.028,
      300,
      'A prison island’s beach. Quest: swim.',
    ],
    [
      'smedsudden',
      'Smedsuddsbadet',
      'coast',
      59.324,
      18.013,
      300,
      'A city beach. Quest: see City Hall from the water.',
    ],
    [
      'fjaderholmarna',
      'Fjäderholmarna',
      'coast',
      59.326,
      18.17,
      300,
      'The nearest archipelago islands. Quest: eat smoked fish.',
    ],
    [
      'hellasgarden',
      'Hellasgården',
      'coast',
      59.2915,
      18.164,
      200,
      'A lake with a winter sauna. Quest: take a winter dip.',
    ],
    [
      'vinterviken',
      'Vinterviken',
      'coast',
      59.315,
      17.996,
      100,
      'A bay where Nobel tested dynamite. Quest: find the factory.',
    ],
    [
      'haga',
      'Hagaparken',
      'nature',
      59.357,
      18.038,
      300,
      'Gustav III’s English park. Quest: find the copper tents.',
    ],
    [
      'skinnarvik',
      'Skinnarviksberget',
      'nature',
      59.3205,
      18.045,
      300,
      'A rock in the middle of town. Quest: watch the sunset.',
    ],
    [
      'rosendal-garden',
      'Rosendal Garden',
      'nature',
      59.327,
      18.125,
      300,
      'An organic garden café. Quest: eat a bun.',
    ],
    [
      'judarskogen',
      'Judarskogen',
      'nature',
      59.342,
      17.93,
      100,
      'A forest lake. Quest: walk around it.',
    ],
    [
      'monteliusvagen',
      'Monteliusvägen',
      'nature',
      59.32,
      18.064,
      600,
      'A cliff path. Quest: find the bench.',
    ],
    [
      'drottningholm',
      'Drottningholm Palace',
      'heritage',
      59.3217,
      17.886,
      600,
      'The royal family’s home. Quest: find the Chinese Pavilion.',
    ],
    [
      'ulriksdal',
      'Ulriksdal Palace',
      'heritage',
      59.3805,
      18.017,
      60,
      'A royal summer palace. Quest: find the orangery.',
    ],
    [
      'rosendal-palace',
      'Rosendal Palace',
      'heritage',
      59.3275,
      18.118,
      60,
      'Karl XIV Johan’s pleasure palace. Quest: find the porphyry vase.',
    ],
    [
      'gustav-pavilion',
      'Gustav III’s Pavilion',
      'heritage',
      59.36,
      18.0345,
      40,
      'A tiny neoclassical pavilion. Quest: find the mirrors.',
    ],
    [
      'royal-palace',
      'Stockholm Palace',
      'heritage',
      59.3268,
      18.0717,
      2000,
      'One of Europe’s largest palaces. Quest: watch the guard change.',
    ],
    [
      'vasa',
      'Vasa Museum',
      'culture',
      59.328,
      18.0915,
      3000,
      'A warship that sank on its maiden voyage. Quest: find the lion.',
    ],
    [
      'skansen',
      'Skansen',
      'culture',
      59.326,
      18.1035,
      1500,
      'The first open-air museum. Quest: find a bakery.',
    ],
    [
      'nobel',
      'Nobel Prize Museum',
      'culture',
      59.325,
      18.0705,
      500,
      'The old stock exchange. Quest: find the signed chairs.',
    ],
    [
      'nordic',
      'Nordic Museum',
      'culture',
      59.329,
      18.0935,
      300,
      'A castle-like museum. Quest: find Gustav Vasa.',
    ],
    [
      'city-hall',
      'Stockholm City Hall',
      'culture',
      59.3275,
      18.0545,
      800,
      'The Nobel banquet hall. Quest: find the Golden Hall.',
    ],
    [
      'moderna',
      'Moderna Museet',
      'art',
      59.326,
      18.085,
      500,
      'Modern art on Skeppsholmen. Quest: find the goat.',
    ],
    [
      'fotografiska',
      'Fotografiska',
      'art',
      59.3178,
      18.0855,
      500,
      'Photography in a customs house. Quest: find the view.',
    ],
    [
      'millesgarden',
      'Millesgården',
      'art',
      59.36,
      18.1205,
      150,
      'Carl Milles’s sculpture garden. Quest: find the hand of God.',
    ],
    [
      'waldemarsudde',
      'Prins Eugens Waldemarsudde',
      'art',
      59.3225,
      18.108,
      200,
      'A painter prince’s villa. Quest: find his studio.',
    ],
    [
      't-centralen',
      'T-Centralen Blue Cave',
      'art',
      59.3313,
      18.0597,
      600,
      'A metro station painted blue. Quest: find the vines.',
    ],
    [
      'abba',
      'ABBA The Museum',
      'music_events',
      59.3255,
      18.096,
      1000,
      'Sing with ABBA. Quest: call the phone.',
    ],
    [
      'opera',
      'Royal Swedish Opera',
      'music_events',
      59.3295,
      18.0705,
      300,
      'Gustav III was shot at a masked ball here. Quest: find the stair.',
    ],
    [
      'konserthuset',
      'Konserthuset',
      'music_events',
      59.3355,
      18.063,
      300,
      'The blue concert hall of the Nobel Prize. Quest: find Orpheus.',
    ],
    [
      'fasching',
      'Fasching',
      'music_events',
      59.3345,
      18.0545,
      200,
      'A jazz club. Quest: catch a set.',
    ],
    [
      'grona-lund',
      'Gröna Lund',
      'music_events',
      59.3235,
      18.0965,
      600,
      'An amusement park with summer concerts. Quest: ride the old rollercoaster.',
    ],
    [
      'katarinahissen',
      'Katarina Elevator',
      'travel',
      59.3195,
      18.073,
      400,
      'A lift with a view. Quest: find the bridge.',
    ],
    [
      'slussen-ferry',
      'Djurgården Ferry at Slussen',
      'travel',
      59.32,
      18.078,
      600,
      'A ferry across the harbour. Quest: ride it.',
    ],
    [
      'djurgardsbron',
      'Djurgårdsbron',
      'travel',
      59.3315,
      18.095,
      300,
      'A bridge to the royal park. Quest: find the gods.',
    ],
    [
      'central',
      'Stockholm Central Station',
      'travel',
      59.33,
      18.058,
      500,
      'The station hall of 1871. Quest: find the clock.',
    ],
    [
      'af-chapman',
      'Af Chapman',
      'travel',
      59.3255,
      18.0805,
      200,
      'A tall ship turned hostel. Quest: sleep on board.',
    ],
    [
      'trotzig',
      'Mårten Trotzigs Gränd',
      'other',
      59.3225,
      18.072,
      800,
      'Stockholm’s narrowest lane, 90 cm wide. Quest: walk it.',
    ],
    [
      'ostermalm',
      'Östermalms Saluhall',
      'other',
      59.336,
      18.079,
      500,
      'A market hall of 1888. Quest: eat a shrimp sandwich.',
    ],
    [
      'saturnus',
      'Café Saturnus',
      'other',
      59.341,
      18.07,
      300,
      'Cinnamon buns as big as plates. Quest: eat one.',
    ],
    [
      'kaknas',
      'Kaknästornet',
      'other',
      59.335,
      18.127,
      200,
      'A TV tower. Quest: see the archipelago.',
    ],
    [
      'skogskyrkogarden',
      'Skogskyrkogården',
      'other',
      59.276,
      18.1,
      100,
      'A forest cemetery. Quest: find Greta Garbo.',
    ],
    [
      'fafangan',
      'Fåfängan',
      'other',
      59.314,
      18.1,
      10,
      'A hilltop café with a secret view. Quest: find the view.',
      'hidden',
    ],
  ]),

  ...quests('copenhagen', [
    [
      'amager-strand',
      'Amager Strandpark',
      'coast',
      55.655,
      12.648,
      600,
      'A city beach. Quest: walk the pier.',
    ],
    [
      'islands-brygge',
      'Islands Brygge Harbour Bath',
      'coast',
      55.664,
      12.577,
      600,
      'Swim in the harbour. Quest: jump in.',
    ],
    [
      'bellevue',
      'Bellevue Beach',
      'coast',
      55.7705,
      12.588,
      400,
      'Arne Jacobsen’s beach. Quest: find the lifeguard tower.',
    ],
    [
      'svanemollen',
      'Svanemøllen Beach',
      'coast',
      55.721,
      12.581,
      300,
      'A city beach. Quest: swim.',
    ],
    [
      'kastrup',
      'Kastrup Sea Bath',
      'coast',
      55.639,
      12.655,
      300,
      'A wooden snail in the sea. Quest: dive.',
    ],
    [
      'kings-garden',
      'King’s Garden',
      'nature',
      55.6845,
      12.5815,
      800,
      'The oldest royal garden. Quest: find H.C. Andersen.',
    ],
    [
      'botanical',
      'Botanical Garden',
      'nature',
      55.6875,
      12.5735,
      600,
      'A palm house of 1874. Quest: climb the spiral stairs.',
    ],
    [
      'frederiksberg-gardens',
      'Frederiksberg Gardens',
      'nature',
      55.6735,
      12.524,
      400,
      'A romantic garden. Quest: see the elephants next door.',
    ],
    [
      'the-lakes',
      'The Lakes',
      'nature',
      55.687,
      12.5605,
      600,
      'Three lakes. Quest: walk around one.',
    ],
    [
      'amager-faelled',
      'Amager Fælled',
      'nature',
      55.655,
      12.59,
      100,
      'A wild common. Quest: spot a deer.',
    ],
    [
      'rosenborg',
      'Rosenborg Castle',
      'heritage',
      55.6858,
      12.5773,
      600,
      'The crown jewels. Quest: find the crown.',
    ],
    [
      'amalienborg',
      'Amalienborg',
      'heritage',
      55.684,
      12.593,
      1000,
      'Four palaces around a square. Quest: watch the guard change.',
    ],
    [
      'kastellet',
      'Kastellet',
      'heritage',
      55.6915,
      12.5945,
      500,
      'A star fortress. Quest: find the windmill.',
    ],
    [
      'frederiksberg-palace',
      'Frederiksberg Palace',
      'heritage',
      55.673,
      12.526,
      60,
      'A hilltop palace. Quest: find the view.',
    ],
    [
      'christiansborg',
      'Christiansborg',
      'heritage',
      55.6765,
      12.5805,
      800,
      'Parliament on old palace ruins. Quest: climb the tower.',
    ],
    [
      'national-museum',
      'National Museum of Denmark',
      'culture',
      55.6745,
      12.5745,
      500,
      'The Sun Chariot. Quest: find the chariot.',
    ],
    [
      'round-tower',
      'Round Tower',
      'culture',
      55.6814,
      12.5757,
      800,
      'A tower with a spiral ramp. Quest: walk the ramp.',
    ],
    [
      'design-museum',
      'Designmuseum Danmark',
      'culture',
      55.6885,
      12.5975,
      300,
      'Danish chairs. Quest: find the egg chair.',
    ],
    [
      'black-diamond',
      'The Black Diamond',
      'culture',
      55.673,
      12.583,
      300,
      'A library by the harbour. Quest: find the view.',
    ],
    [
      'marble-church',
      'Marble Church',
      'culture',
      55.685,
      12.5895,
      600,
      'A dome over the city. Quest: climb the dome.',
    ],
    [
      'glyptotek',
      'Ny Carlsberg Glyptotek',
      'art',
      55.6725,
      12.5725,
      500,
      'A winter garden of sculptures. Quest: find the palm house.',
    ],
    ['smk', 'SMK', 'art', 55.689, 12.5785, 400, 'The national gallery. Quest: find a Hammershøi.'],
    [
      'copenhagen-contemporary',
      'Copenhagen Contemporary',
      'art',
      55.6935,
      12.608,
      200,
      'Art in a welding hall. Quest: find the installation.',
    ],
    [
      'superkilen',
      'Superkilen',
      'art',
      55.7005,
      12.542,
      200,
      'A park of objects from 60 countries. Quest: find the Moroccan fountain.',
    ],
    [
      'thorvaldsens',
      'Thorvaldsens Museum',
      'art',
      55.677,
      12.5775,
      200,
      'A sculptor’s museum. Quest: find his tomb.',
    ],
    [
      'opera',
      'Royal Danish Opera',
      'music_events',
      55.682,
      12.6005,
      300,
      'An opera house on the water. Quest: find the lamp.',
    ],
    [
      'tivoli',
      'Tivoli Gardens',
      'music_events',
      55.6737,
      12.5681,
      3000,
      'Pleasure gardens since 1843. Quest: ride the old rollercoaster.',
    ],
    [
      'jazzhouse',
      'Jazzhouse',
      'music_events',
      55.679,
      12.5785,
      200,
      'A jazz club. Quest: catch a set.',
    ],
    [
      'vega',
      'Vega',
      'music_events',
      55.6675,
      12.5435,
      300,
      'A union house turned venue. Quest: catch a gig.',
    ],
    [
      'dr-koncerthuset',
      'DR Koncerthuset',
      'music_events',
      55.6585,
      12.589,
      200,
      'Jean Nouvel’s blue cube. Quest: find the hall.',
    ],
    [
      'nyhavn',
      'Nyhavn',
      'travel',
      55.6798,
      12.5907,
      3000,
      'A canal of old ships. Quest: find Andersen’s house.',
    ],
    [
      'central',
      'Copenhagen Central Station',
      'travel',
      55.6727,
      12.5647,
      400,
      'A station of 1911. Quest: find the clock.',
    ],
    [
      'cykelslangen',
      'Cykelslangen',
      'travel',
      55.6655,
      12.5765,
      300,
      'A snake bridge for bikes. Quest: ride it.',
    ],
    [
      'inderhavnsbroen',
      'Inderhavnsbroen',
      'travel',
      55.68,
      12.596,
      300,
      'The kissing bridge. Quest: walk across.',
    ],
    [
      'knippelsbro',
      'Knippelsbro',
      'travel',
      55.674,
      12.5895,
      200,
      'A bascule bridge. Quest: watch it open.',
    ],
    [
      'little-mermaid',
      'The Little Mermaid',
      'other',
      55.6929,
      12.5993,
      3000,
      'Andersen’s mermaid. Quest: photograph her.',
    ],
    [
      'christiania',
      'Christiania',
      'other',
      55.6735,
      12.6,
      1000,
      'A free town. Quest: find the sign.',
    ],
    [
      'torvehallerne',
      'Torvehallerne',
      'other',
      55.684,
      12.5695,
      600,
      'A market hall. Quest: eat a smørrebrød.',
    ],
    [
      'reffen',
      'Reffen',
      'other',
      55.6935,
      12.611,
      400,
      'Street food in shipping containers. Quest: eat.',
    ],
    [
      'assistens',
      'Assistens Cemetery',
      'other',
      55.6915,
      12.549,
      300,
      'Andersen and Kierkegaard. Quest: find Andersen.',
    ],
    [
      'nyboder',
      'Nyboder',
      'other',
      55.6875,
      12.5875,
      10,
      'Rows of yellow sailors’ houses. Quest: find the museum house.',
      'hidden',
    ],
  ]),

  ...quests('warsaw', [
    [
      'poniatowka',
      'Poniatówka Beach',
      'coast',
      52.232,
      21.045,
      300,
      'A Vistula beach. Quest: see the stadium.',
    ],
    [
      'bulwary',
      'Vistula Boulevards',
      'coast',
      52.244,
      21.028,
      600,
      'The riverside promenade. Quest: find the mermaid.',
    ],
    [
      'saska',
      'Saska Kępa Beach',
      'coast',
      52.228,
      21.062,
      200,
      'A wild river beach. Quest: watch the sunset.',
    ],
    [
      'czerniakowskie',
      'Czerniakowskie Lake',
      'coast',
      52.189,
      21.067,
      100,
      'A lake with a beach. Quest: swim.',
    ],
    [
      'kamionkowskie',
      'Kamionkowskie Lake',
      'coast',
      52.24,
      21.065,
      100,
      'An oxbow lake. Quest: find the swans.',
    ],
    [
      'lazienki',
      'Łazienki Park',
      'nature',
      52.217,
      21.027,
      1000,
      'Chopin concerts in summer. Quest: find the Chopin monument.',
    ],
    [
      'saxon',
      'Saxon Garden',
      'nature',
      52.241,
      21.008,
      500,
      'The oldest public park. Quest: find the Tomb of the Unknown Soldier.',
    ],
    [
      'buw',
      'University Library Rooftop Garden',
      'nature',
      52.2425,
      21.025,
      300,
      'A garden on a library roof. Quest: find the bridge.',
    ],
    [
      'pole-mokotowskie',
      'Pole Mokotowskie',
      'nature',
      52.212,
      20.997,
      300,
      'A park on an old airfield. Quest: find the pond.',
    ],
    [
      'kabaty',
      'Kabaty Forest',
      'nature',
      52.135,
      21.05,
      100,
      'A forest at the end of the metro. Quest: walk the path.',
    ],
    [
      'wilanow',
      'Wilanów Palace',
      'heritage',
      52.165,
      21.09,
      600,
      'A baroque palace of King Jan III Sobieski. Quest: find the sundial.',
    ],
    [
      'palace-isle',
      'Palace on the Isle',
      'heritage',
      52.215,
      21.035,
      600,
      'A king’s bathhouse turned palace. Quest: find the peacocks.',
    ],
    [
      'krasinski',
      'Krasiński Palace',
      'heritage',
      52.249,
      21.004,
      100,
      'A baroque palace. Quest: find the garden.',
    ],
    [
      'royal-castle',
      'Royal Castle',
      'heritage',
      52.2479,
      21.0152,
      1500,
      'Rebuilt from rubble. Quest: find the Canaletto room.',
    ],
    [
      'belweder',
      'Belweder Palace',
      'heritage',
      52.2095,
      21.029,
      50,
      'A palace on the escarpment. Quest: see it from the park.',
    ],
    [
      'polin',
      'POLIN',
      'culture',
      52.2495,
      20.993,
      500,
      'A thousand years of Polish Jews. Quest: find the synagogue roof.',
    ],
    [
      'uprising',
      'Warsaw Uprising Museum',
      'culture',
      52.2322,
      20.981,
      800,
      'The 1944 uprising. Quest: find the bomber.',
    ],
    [
      'palace-culture',
      'Palace of Culture and Science',
      'culture',
      52.2318,
      21.006,
      1500,
      'Stalin’s gift. Quest: reach the terrace.',
    ],
    [
      'copernicus',
      'Copernicus Science Centre',
      'culture',
      52.242,
      21.029,
      600,
      'Science to touch. Quest: find the planetarium.',
    ],
    [
      'old-town',
      'Old Town Market Square',
      'culture',
      52.2497,
      21.0122,
      2000,
      'Rebuilt after 1945. Quest: find the mermaid.',
    ],
    [
      'zacheta',
      'Zachęta',
      'art',
      52.239,
      21.011,
      300,
      'A gallery of 1900. Quest: find the bullet marks.',
    ],
    [
      'national-museum',
      'National Museum',
      'art',
      52.232,
      21.025,
      300,
      'Polish painting. Quest: find the Battle of Grunwald.',
    ],
    [
      'krolikarnia',
      'Królikarnia',
      'art',
      52.1865,
      21.023,
      100,
      'Sculpture in a hunting palace. Quest: find Dunikowski.',
    ],
    [
      'neon-museum',
      'Neon Museum',
      'art',
      52.251,
      21.056,
      300,
      'Communist neon signs. Quest: find the volleyball player.',
    ],
    [
      'ujazdow',
      'Ujazdów Castle CCA',
      'art',
      52.221,
      21.03,
      200,
      'Contemporary art in a castle. Quest: find the cinema.',
    ],
    [
      'chopin-museum',
      'Chopin Museum',
      'music_events',
      52.2365,
      21.023,
      400,
      'Chopin’s piano. Quest: find his death mask.',
    ],
    [
      'grand-theatre',
      'Grand Theatre',
      'music_events',
      52.2435,
      21.01,
      300,
      'The national opera. Quest: find the chariot.',
    ],
    [
      'philharmonic',
      'Warsaw Philharmonic',
      'music_events',
      52.2335,
      21.011,
      200,
      'Home of the Chopin Competition. Quest: find the hall.',
    ],
    [
      'hydrozagadka',
      'Hydrozagadka',
      'music_events',
      52.256,
      21.042,
      100,
      'A Praga club. Quest: catch a gig.',
    ],
    ['tygmont', 'Tygmont', 'music_events', 52.237, 21.016, 100, 'A jazz club. Quest: catch a set.'],
    [
      'central-station',
      'Warsaw Central',
      'travel',
      52.2285,
      21.003,
      400,
      'A modernist station. Quest: find the clock.',
    ],
    [
      'swietokrzyski',
      'Świętokrzyski Bridge',
      'travel',
      52.242,
      21.038,
      200,
      'A cable-stayed bridge. Quest: walk across.',
    ],
    [
      'railway-museum',
      'Railway Museum',
      'travel',
      52.229,
      20.99,
      200,
      'Steam engines in an old station. Quest: find the armoured train.',
    ],
    [
      'vistula-ferry',
      'Vistula Ferry',
      'travel',
      52.219,
      21.06,
      100,
      'A summer ferry across the river. Quest: cross.',
    ],
    [
      'tram-museum',
      'Tram Depot Museum',
      'travel',
      52.26,
      21.051,
      50,
      'Old trams in Praga. Quest: find a horse tram.',
    ],
    [
      'syrenka',
      'Mermaid on the Vistula',
      'other',
      52.244,
      21.031,
      600,
      'Warsaw’s mermaid. Quest: find her sword.',
    ],
    [
      'vodka-museum',
      'Polish Vodka Museum',
      'other',
      52.2515,
      21.045,
      300,
      'In the old Koneser distillery. Quest: taste a vodka.',
    ],
    [
      'prasowy',
      'Bar Prasowy',
      'other',
      52.2215,
      21.016,
      400,
      'A milk bar of 1954. Quest: eat pierogi.',
    ],
    ['koszyki', 'Hala Koszyki', 'other', 52.2225, 21.013, 600, 'A market hall reborn. Quest: eat.'],
    [
      'keret-house',
      'Keret House',
      'other',
      52.2365,
      20.996,
      100,
      'The world’s narrowest house. Quest: measure it.',
    ],
    [
      'little-insurgent',
      'Little Insurgent',
      'other',
      52.2483,
      21.0115,
      10,
      'A statue of a child fighter of 1944. Quest: find the helmet.',
      'hidden',
    ],
  ]),

  ...quests('gdansk', [
    [
      'brzezno',
      'Brzeźno Beach',
      'coast',
      54.4115,
      18.628,
      400,
      'A Baltic beach with a pier. Quest: walk the pier.',
    ],
    [
      'sopot-pier',
      'Sopot Pier',
      'coast',
      54.4465,
      18.571,
      1500,
      'Europe’s longest wooden pier. Quest: walk to the end.',
    ],
    [
      'jelitkowo',
      'Jelitkowo',
      'coast',
      54.4245,
      18.599,
      300,
      'A fishing village beach. Quest: buy smoked fish.',
    ],
    [
      'stogi',
      'Stogi Beach',
      'coast',
      54.378,
      18.728,
      200,
      'A wide beach with dunes. Quest: find the dunes.',
    ],
    [
      'gorki',
      'Górki Zachodnie',
      'coast',
      54.37,
      18.77,
      100,
      'A bird reserve by the river mouth. Quest: spot a seal.',
    ],
    [
      'oliwa-park',
      'Oliwa Park',
      'nature',
      54.4115,
      18.56,
      500,
      'A palace park with a whispering grotto. Quest: whisper.',
    ],
    [
      'pacholek',
      'Pachołek Hill',
      'nature',
      54.4185,
      18.545,
      200,
      'A viewpoint tower. Quest: climb it.',
    ],
    [
      'gradowa',
      'Gradowa Hill',
      'nature',
      54.3555,
      18.638,
      200,
      'A fort on a hill. Quest: find the cross.',
    ],
    [
      'jaskowa',
      'Jaśkowa Dolina',
      'nature',
      54.38,
      18.585,
      100,
      'A wooded valley. Quest: find the stream.',
    ],
    [
      'orunski',
      'Oruński Park',
      'nature',
      54.3245,
      18.6295,
      100,
      'A park with ponds. Quest: find the manor.',
    ],
    [
      'artus',
      'Artus Court',
      'heritage',
      54.3485,
      18.654,
      800,
      'The merchants’ hall. Quest: find the giant stove.',
    ],
    [
      'abbots-palace',
      'Abbots’ Palace, Oliwa',
      'heritage',
      54.41,
      18.5585,
      100,
      'A rococo palace. Quest: find the museum.',
    ],
    [
      'uphagen',
      'Uphagen House',
      'heritage',
      54.3485,
      18.6495,
      200,
      'A merchant’s house of 1775. Quest: find the insect room.',
    ],
    [
      'westerplatte',
      'Westerplatte',
      'heritage',
      54.4067,
      18.6696,
      600,
      'Where WWII began. Quest: find the monument.',
    ],
    [
      'golden-gate',
      'Golden Gate',
      'heritage',
      54.349,
      18.648,
      800,
      'The gate of the Royal Way. Quest: find the virtues.',
    ],
    [
      'ecs',
      'European Solidarity Centre',
      'culture',
      54.361,
      18.6495,
      500,
      'The birthplace of Solidarity. Quest: find the shipyard gate.',
    ],
    [
      'ww2-museum',
      'Museum of WWII',
      'culture',
      54.356,
      18.66,
      600,
      'A tilting tower. Quest: find the tank.',
    ],
    [
      'st-mary',
      'St Mary’s Basilica',
      'culture',
      54.3497,
      18.6533,
      1000,
      'One of the largest brick churches. Quest: find the clock.',
    ],
    [
      'post-office',
      'Polish Post Office',
      'culture',
      54.353,
      18.653,
      200,
      'The post office defended in 1939. Quest: find the plaque.',
    ],
    [
      'amber-museum',
      'Amber Museum',
      'culture',
      54.3502,
      18.6475,
      400,
      'Amber in a prison tower. Quest: find the insect.',
    ],
    [
      'national-museum',
      'National Museum Gdańsk',
      'art',
      54.344,
      18.656,
      300,
      'Memling’s Last Judgment. Quest: find the scales.',
    ],
    [
      'laznia',
      'Łaźnia CCA',
      'art',
      54.346,
      18.661,
      100,
      'Art in a bathhouse. Quest: find the show.',
    ],
    [
      'zaspa',
      'Zaspa Murals',
      'art',
      54.388,
      18.608,
      200,
      'Murals on tower blocks. Quest: find the Pope.',
    ],
    [
      'wyspa',
      'Wyspa Institute of Art',
      'art',
      54.364,
      18.649,
      100,
      'Art in the shipyard. Quest: find the cranes.',
    ],
    [
      'sopot-gallery',
      'Sopot State Art Gallery',
      'art',
      54.4455,
      18.569,
      100,
      'A gallery by the pier. Quest: find the show.',
    ],
    [
      'philharmonic',
      'Polish Baltic Philharmonic',
      'music_events',
      54.353,
      18.66,
      200,
      'In an old power station. Quest: find the chimney.',
    ],
    [
      'oliwa-organ',
      'Oliwa Cathedral Organ',
      'music_events',
      54.411,
      18.5615,
      300,
      'An organ with moving angels. Quest: hear a recital.',
    ],
    [
      'forest-opera',
      'Forest Opera, Sopot',
      'music_events',
      54.437,
      18.547,
      300,
      'An open-air amphitheatre. Quest: find the stage.',
    ],
    [
      'shakespeare',
      'Gdańsk Shakespeare Theatre',
      'music_events',
      54.347,
      18.655,
      200,
      'A theatre with an opening roof. Quest: watch the roof open.',
    ],
    [
      'ergo-arena',
      'Ergo Arena',
      'music_events',
      54.425,
      18.581,
      200,
      'An arena on the city border. Quest: catch a gig.',
    ],
    [
      'zuraw',
      'Żuraw',
      'travel',
      54.3505,
      18.6575,
      1000,
      'A medieval port crane. Quest: find the treadwheel.',
    ],
    [
      'main-station',
      'Gdańsk Main Station',
      'travel',
      54.3555,
      18.644,
      300,
      'A station of 1900. Quest: find the clock tower.',
    ],
    [
      'soldek',
      'SS Sołdek',
      'travel',
      54.351,
      18.661,
      200,
      'A museum ship. Quest: find the engine room.',
    ],
    [
      'shipyard-cranes',
      'Shipyard Cranes',
      'travel',
      54.364,
      18.656,
      300,
      'The shipyard’s giant cranes. Quest: photograph them.',
    ],
    [
      'brzezno-pier',
      'Brzeźno Pier',
      'travel',
      54.412,
      18.6315,
      200,
      'A pier by the beach. Quest: walk to the end.',
    ],
    [
      'mariacka',
      'Mariacka Street',
      'other',
      54.3495,
      18.6555,
      1500,
      'Amber shops and gargoyles. Quest: find a dragon.',
    ],
    [
      'crooked-house',
      'Crooked House, Sopot',
      'other',
      54.444,
      18.5675,
      600,
      'A building that melts. Quest: photograph it.',
    ],
    [
      'hala-targowa',
      'Hala Targowa',
      'other',
      54.3505,
      18.6505,
      400,
      'A market hall. Quest: buy something.',
    ],
    [
      'oliwa-zoo',
      'Oliwa Zoo',
      'other',
      54.4115,
      18.532,
      400,
      'A zoo in a forest valley. Quest: find the giraffes.',
    ],
    [
      'nowy-port-lighthouse',
      'Nowy Port Lighthouse',
      'other',
      54.4075,
      18.662,
      100,
      'The lighthouse that fired the first shot of WWII. Quest: climb it.',
    ],
    [
      'biskupia-gorka',
      'Biskupia Górka',
      'other',
      54.346,
      18.64,
      10,
      'A fort hill with old houses. Quest: find the view.',
      'hidden',
    ],
  ]),
];
