import { quests } from '../place-in';

// Side quests written as a travelling historian would brief you: a line of history, then what to
// go and find. Heritage leans on the quieter palaces and quintas rather than the famous queues.

export const PORTUGAL_QUESTS = [
  ...quests('sintra', [
    [
      'praia-macas',
      'Praia das Maçãs',
      'coast',
      38.8262,
      -9.47,
      900,
      'Where Lisbon’s Belle Époque day-trippers stepped off the tram. Quest: find the tidal sea pool at the north end.',
    ],
    [
      'praia-ursa',
      'Praia da Ursa',
      'coast',
      38.7893,
      -9.495,
      60,
      'A wild cove under Cabo da Roca, reached only on foot. Quest: spot the rock the fishermen named the She-Bear.',
    ],
    [
      'monserrate-ferns',
      'Monserrate Fern Valley',
      'nature',
      38.7934,
      -9.4218,
      300,
      'Francis Cook’s Victorian plant collectors filled this ravine with tree ferns. Quest: stand beneath the tallest frond.',
    ],
    [
      'quinta-relogio',
      'Quinta do Relógio',
      'heritage',
      38.7972,
      -9.3936,
      15,
      'A neo-Moorish quinta of 1860 where King Carlos spent his honeymoon. Quest: photograph its horseshoe arches from the road.',
    ],
    [
      'penha-verde',
      'Quinta da Penha Verde',
      'heritage',
      38.7925,
      -9.4078,
      12,
      'Estate of the viceroy João de Castro, planted with India’s first trees in Europe. Quest: find his chapels in the wood.',
    ],
    [
      'chalet-biester',
      'Chalet Biester',
      'heritage',
      38.795,
      -9.3978,
      25,
      'A Gothic-Revival chalet of the 1880s, painted inside by Luigi Manini. Quest: frame its slate turrets through the trees.',
    ],
    [
      'santa-maria',
      'Santa Maria Church',
      'culture',
      38.796,
      -9.386,
      60,
      'Founded after Afonso Henriques took Sintra in 1147, with a Manueline portal. Quest: find the tomb slabs in the floor.',
    ],
    [
      'natural-history',
      'Sintra Natural History Museum',
      'culture',
      38.7995,
      -9.388,
      80,
      'Fossils and minerals in a 19th-century house on the old square. Quest: find the dinosaur egg.',
    ],
    [
      'fonte-pipa',
      'Fonte da Pipa',
      'art',
      38.7948,
      -9.3898,
      40,
      'An azulejo-clad fountain where villagers once filled their jugs. Quest: read the date painted in its tiles.',
    ],
    [
      'volta-duche',
      'Volta do Duche Tile Benches',
      'art',
      38.7997,
      -9.3848,
      150,
      'The Romantic promenade into town, lined with tiled benches. Quest: find a bench with a view of the Moorish walls.',
    ],
    [
      'olga-cadaval',
      'Olga Cadaval Cultural Centre',
      'music_events',
      38.7999,
      -9.3786,
      400,
      'Named after the duchess who brought Europe’s musicians to Sintra. Quest: catch a concert or the festival poster.',
    ],
    [
      'casa-teatro',
      'Casa de Teatro de Sintra',
      'music_events',
      38.7976,
      -9.383,
      80,
      'A small theatre company’s home in Estefânia. Quest: find out what’s on tonight.',
    ],
    [
      'feira-merces',
      'Feira das Mercês',
      'music_events',
      38.7835,
      -9.316,
      120,
      'Sintra’s oldest country fair, held around a hilltop chapel every autumn. Quest: find the chapel on the fairground.',
    ],
    [
      'colares-adega',
      'Adega Regional de Colares',
      'music_events',
      38.7995,
      -9.4475,
      90,
      'Cellars of the Ramisco vines that survived phylloxera in sand. Quest: join a harvest-time tasting or event.',
    ],
    [
      'tram-banzao',
      'Banzão Tram Stop',
      'culture',
      38.8128,
      -9.4505,
      70,
      'The 1904 tram still rattles through the vineyards here. Quest: wait for the bell and photograph the car.',
    ],
    [
      'tram-galamares',
      'Galamares Tram Stop',
      'culture',
      38.8003,
      -9.4155,
      40,
      'A halt on the old line from the hills to the sea. Quest: ride one stop towards the coast.',
    ],
    [
      'portela-station',
      'Portela de Sintra Station',
      'culture',
      38.802,
      -9.3667,
      200,
      'Where the Lisbon line meets the town’s new quarter. Quest: find the tile panel in the hall.',
    ],
    [
      'piriquita',
      'Piriquita Bakery',
      'culture',
      38.7978,
      -9.3925,
      1500,
      'Bakers since 1862, said to have named the queijada for a king. Quest: order a travesseiro, still warm.',
    ],
    [
      'sao-pedro-fair',
      'São Pedro Fair',
      'culture',
      38.788,
      -9.377,
      300,
      'A market held on the 2nd and 4th Sunday since the Middle Ages. Quest: find something old and something edible.',
    ],
    [
      'azoia',
      'Azóia Village',
      'other',
      38.766,
      -9.479,
      50,
      'The westernmost village of mainland Europe. Quest: find the café the lighthouse keepers used.',
    ],
    [
      'janas-chapel',
      'Round Chapel of Janas',
      'other',
      38.8125,
      -9.4215,
      30,
      'A circular chapel where farmers still bless their animals each August. Quest: walk once around it.',
    ],
    [
      'dino-footprints',
      'Praia Grande Dinosaur Footprints',
      'other',
      38.813,
      -9.479,
      200,
      'Tracks left 120 million years ago on a cliff that was once a beach. Quest: find the trackway at the south end.',
    ],
  ]),

  ...quests('lisbon', [
    [
      'carcavelos',
      'Carcavelos Beach',
      'coast',
      38.679,
      -9.3365,
      3000,
      'Lisbon’s surf beach beneath the star-shaped fort of São Julião. Quest: watch a set roll in by the fort.',
    ],
    [
      'praia-caxias',
      'Caxias Beach',
      'coast',
      38.6997,
      -9.2765,
      200,
      'A small beach by the old royal estate. Quest: spot the lighthouse on the Bugio fort offshore.',
    ],
    [
      'caparica',
      'Costa da Caparica',
      'coast',
      38.644,
      -9.2395,
      2500,
      'Fishermen hauled nets here long before the surfers came. Quest: catch the little beach train south.',
    ],
    [
      'ribeira-das-naus',
      'Ribeira das Naus',
      'coast',
      38.7066,
      -9.142,
      1500,
      'The royal shipyard that built the fleets of the Discoveries. Quest: sit on the river steps at sunset.',
    ],
    [
      'paco-de-arcos',
      'Paço de Arcos Beach',
      'coast',
      38.6925,
      -9.293,
      150,
      'A fishing village beach below a 15th-century royal house. Quest: find the old pier.',
    ],
    [
      'tapada-necessidades',
      'Tapada das Necessidades',
      'nature',
      38.7105,
      -9.1665,
      120,
      'A royal walled garden with a cactus garden and a round greenhouse. Quest: find the cactus garden.',
    ],
    [
      'queluz',
      'Queluz National Palace',
      'heritage',
      38.7505,
      -9.2545,
      900,
      'The pink rococo palace of the Braganzas, Portugal’s little Versailles. Quest: walk the azulejo-lined canal.',
    ],
    [
      'paco-caxias',
      'Caxias Royal Palace',
      'heritage',
      38.7012,
      -9.2738,
      20,
      'A royal summer house with cascading gardens and a grotto. Quest: find the waterfall of statues.',
    ],
    [
      'fronteira',
      'Fronteira Palace',
      'heritage',
      38.7405,
      -9.1835,
      60,
      'A 17th-century hunting palace with the finest azulejo gardens in Lisbon. Quest: find the Gallery of Kings.',
    ],
    [
      'ajuda',
      'Ajuda National Palace',
      'heritage',
      38.7075,
      -9.1985,
      300,
      'The unfinished royal palace, left as it was in 1910. Quest: find the room of Saxony porcelain.',
    ],
    [
      'necessidades',
      'Necessidades Palace',
      'heritage',
      38.708,
      -9.1695,
      40,
      'The pink palace the last king fled from in 1910, now the Foreign Ministry. Quest: photograph its obelisk fountain.',
    ],
    [
      'pombal-oeiras',
      'Marquis of Pombal Palace, Oeiras',
      'heritage',
      38.694,
      -9.312,
      30,
      'Country seat of the man who rebuilt Lisbon after 1755. Quest: find the waterfall in the gardens.',
    ],
    [
      'museu-lisboa',
      'Lisbon Museum – Pimenta Palace',
      'culture',
      38.757,
      -9.157,
      150,
      'The city’s story told in a palace where peacocks roam. Quest: find the model of Lisbon before the earthquake.',
    ],
    [
      'oriente',
      'Museu do Oriente',
      'culture',
      38.7038,
      -9.1735,
      200,
      'Portugal’s Asian encounters, in an old salt-cod warehouse. Quest: find the Chinese opera masks.',
    ],
    [
      'mnaa',
      'National Museum of Ancient Art',
      'art',
      38.705,
      -9.161,
      500,
      'Portugal’s greatest paintings, in the palace of the counts of Alvor. Quest: find Bosch’s Temptations.',
    ],
    [
      'pomar',
      'Júlio Pomar Studio Museum',
      'art',
      38.7108,
      -9.1527,
      90,
      'A warehouse turned studio by one of Portugal’s great modern painters. Quest: find a portrait of Fernando Pessoa.',
    ],
    [
      'coliseu',
      'Coliseu dos Recreios',
      'music_events',
      38.7155,
      -9.1405,
      600,
      'A 1890 iron-domed hall that has hosted circuses, opera and rock. Quest: look up at the dome.',
    ],
    [
      'hot-clube',
      'Hot Clube de Portugal',
      'music_events',
      38.7195,
      -9.145,
      150,
      'One of Europe’s oldest jazz clubs, since 1948. Quest: catch a late set.',
    ],
    [
      'sao-carlos',
      'São Carlos National Theatre',
      'music_events',
      38.7095,
      -9.1418,
      200,
      'An opera house of 1793 built by merchants in three months. Quest: find the square where Pessoa was born.',
    ],
    [
      'casa-independente',
      'Casa Independente',
      'music_events',
      38.7195,
      -9.136,
      150,
      'A faded palace with gigs in its courtyard. Quest: find the courtyard bar.',
    ],
    [
      'bica',
      'Elevador da Bica',
      'culture',
      38.7086,
      -9.147,
      800,
      'A funicular of 1892 climbing a steep, washing-hung street. Quest: photograph it with the river behind.',
    ],
    [
      'gloria',
      'Elevador da Glória',
      'culture',
      38.7155,
      -9.144,
      900,
      'The funicular from Restauradores to the São Pedro de Alcântara viewpoint. Quest: ride it up, walk down.',
    ],
    [
      'pilar-7',
      'Pillar 7 Bridge Experience',
      'culture',
      38.6945,
      -9.1755,
      300,
      'Inside a pillar of the 25 de Abril bridge. Quest: stand on the glass deck as the trains pass.',
    ],
    [
      'pasteis-belem',
      'Pastéis de Belém',
      'culture',
      38.6975,
      -9.2032,
      4000,
      'The custard tarts of the Jerónimos monks, made to a secret recipe since 1837. Quest: eat one with cinnamon.',
    ],
    [
      'feira-ladra',
      'Feira da Ladra',
      'culture',
      38.715,
      -9.127,
      800,
      'The Thieves’ Market, held since the 13th century. Quest: find an old azulejo tile.',
    ],
    [
      'aqueduct',
      'Águas Livres Aqueduct',
      'other',
      38.73,
      -9.168,
      300,
      'Its arches survived the 1755 earthquake that flattened the city. Quest: walk along the top.',
    ],
    [
      'ginjinha',
      'A Ginjinha',
      'culture',
      38.714,
      -9.138,
      1200,
      'A doorway bar pouring cherry liqueur since 1840. Quest: ask for it “com elas”, with the cherries.',
    ],
    [
      'pink-street',
      'Pink Street',
      'culture',
      38.7068,
      -9.144,
      900,
      'Once the sailors’ red-light street, now painted pink. Quest: find a bar named after an old brothel.',
    ],
    [
      'recolhimento',
      'Miradouro do Recolhimento',
      'other',
      38.7118,
      -9.133,
      5,
      'A walled garden viewpoint below the castle that few people find. Quest: find the gate.',
      'hidden',
    ],
  ]),

  ...quests('porto', [
    [
      'matosinhos',
      'Matosinhos Beach',
      'coast',
      41.176,
      -8.69,
      2000,
      'Porto’s fishing harbour beach, under Janet Echelman’s giant net sculpture. Quest: find “She Changes”.',
    ],
    [
      'homem-do-leme',
      'Homem do Leme Beach',
      'coast',
      41.16,
      -8.683,
      400,
      'Named for the statue of a helmsman steering towards the Atlantic. Quest: find the helmsman.',
    ],
    [
      'ingleses',
      'Praia dos Ingleses',
      'coast',
      41.1545,
      -8.68,
      200,
      'Where the English port merchants bathed in the 19th century. Quest: find the beach’s little pergola.',
    ],
    [
      'afurada',
      'Afurada Fishing Village',
      'coast',
      41.143,
      -8.65,
      300,
      'A fishing village where washing still dries in public tanks. Quest: find the communal laundry.',
    ],
    [
      'botanic',
      'Porto Botanic Garden',
      'nature',
      41.153,
      -8.643,
      150,
      'The garden of the Andresen family, where the poet Sophia grew up. Quest: find the cactus house.',
    ],
    [
      'freixo',
      'Freixo Palace',
      'heritage',
      41.145,
      -8.585,
      40,
      'A baroque riverside palace by Nasoni, architect of the Clérigos tower. Quest: see it from the river path.',
    ],
    [
      'serra-pilar',
      'Serra do Pilar Monastery',
      'heritage',
      41.1385,
      -8.6085,
      500,
      'A round monastery church that Wellington used to cross the Douro in 1809. Quest: walk the cloister.',
    ],
    [
      'macieirinha',
      'Quinta da Macieirinha',
      'heritage',
      41.147,
      -8.628,
      30,
      'Where an exiled Sardinian king died in 1849, now the Romantic Museum. Quest: find the king’s bedroom.',
    ],
    [
      'cpf',
      'Portuguese Centre of Photography',
      'culture',
      41.144,
      -8.617,
      300,
      'Photographs in the old jail where the writer Camilo Castelo Branco was locked up. Quest: find his cell.',
    ],
    [
      'santa-clara',
      'Santa Clara Church',
      'culture',
      41.1418,
      -8.6082,
      80,
      'A plain front hiding one of the richest gilded interiors in Portugal. Quest: step in and look up.',
    ],
    [
      'almas',
      'Chapel of the Souls',
      'art',
      41.1497,
      -8.6065,
      900,
      'Covered in 15,947 blue-and-white tiles of saints’ lives. Quest: find Saint Francis.',
    ],
    [
      'carmo',
      'Carmo Church Tile Wall',
      'art',
      41.1475,
      -8.6165,
      700,
      'A whole side wall of azulejos telling the story of the Carmelites. Quest: find the hidden house between two churches.',
    ],
    [
      'casa-musica',
      'Casa da Música',
      'music_events',
      41.1588,
      -8.6307,
      600,
      'Rem Koolhaas’s faceted concert hall of 2005. Quest: find the tiled room inside.',
    ],
    [
      'tnsj',
      'São João National Theatre',
      'music_events',
      41.143,
      -8.6075,
      200,
      'A neo-classical theatre of 1920 on the Batalha square. Quest: find the masks on its front.',
    ],
    [
      'maus-habitos',
      'Maus Hábitos',
      'music_events',
      41.1488,
      -8.6045,
      150,
      'A rooftop arts club on the fourth floor of a garage building. Quest: find the terrace.',
    ],
    [
      'rivoli',
      'Rivoli Theatre',
      'music_events',
      41.149,
      -8.611,
      300,
      'An art deco theatre of 1932 on the Praça D. João I. Quest: find its deco lettering.',
    ],
    [
      'casa-guitarra',
      'Casa da Guitarra',
      'music_events',
      41.1415,
      -8.6115,
      150,
      'A guitar shop where fado is played at night. Quest: hear the Portuguese guitar.',
    ],
    [
      'maria-pia',
      'Maria Pia Bridge',
      'culture',
      41.1395,
      -8.597,
      150,
      'Eiffel’s company spanned the Douro with this iron arch in 1877. Quest: photograph the arch from the river.',
    ],
    [
      'tram-museum',
      'Porto Tram Museum',
      'culture',
      41.147,
      -8.6345,
      200,
      'Old trams in a former power station. Quest: find the oldest car.',
    ],
    [
      'gaia-cable-car',
      'Gaia Cable Car',
      'culture',
      41.1375,
      -8.607,
      600,
      'A short glide over the port lodges. Quest: count the lodge roofs you can read.',
    ],
    [
      'majestic',
      'Majestic Café',
      'culture',
      41.1468,
      -8.6065,
      2000,
      'A Belle Époque café of 1921, all mirrors and carved wood. Quest: order a rabanada.',
    ],
    [
      'santiago',
      'Café Santiago',
      'culture',
      41.148,
      -8.603,
      800,
      'Locals queue here for the francesinha, Porto’s monstrous sandwich. Quest: finish one.',
    ],
    [
      'grahams',
      'Graham’s Port Lodge',
      'culture',
      41.1365,
      -8.624,
      400,
      'A lodge of 1890 with a view over the whole Ribeira. Quest: taste a tawny.',
    ],
    [
      'codecal',
      'Codeçal Steps',
      'other',
      41.1408,
      -8.607,
      60,
      'A steep stair beside the old city wall. Quest: count the steps.',
    ],
    [
      'galerias-paris',
      'Rua Galeria de Paris',
      'culture',
      41.1468,
      -8.6135,
      400,
      'A street of old shops turned bars, busiest after midnight. Quest: find the bar full of old toys.',
    ],
    [
      'vitoria',
      'Miradouro da Vitória',
      'other',
      41.144,
      -8.614,
      5,
      'A hidden terrace in the old Jewish quarter, looking over the Sé. Quest: find the stairway in.',
      'hidden',
    ],
  ]),

  ...quests('evora', [
    [
      'divor',
      'Divor Reservoir',
      'coast',
      38.688,
      -7.878,
      40,
      'An Alentejo lake where storks fish in summer. Quest: find the dam wall.',
    ],
    [
      'monte-novo',
      'Monte Novo Reservoir',
      'coast',
      38.542,
      -7.717,
      50,
      'The lake that keeps Évora in water through the dry months. Quest: watch the sunset over it.',
    ],
    [
      'portas-moura-fountain',
      'Fountain of Portas de Moura',
      'coast',
      38.5693,
      -7.9056,
      200,
      'A Renaissance fountain shaped like a globe, fed by the aqueduct. Quest: find the sphere.',
    ],
    [
      'giraldo-fountain',
      'Giraldo Square Fountain',
      'coast',
      38.5712,
      -7.9092,
      600,
      'Eight spouts for the eight streets that meet here. Quest: count them.',
    ],
    [
      'valverde',
      'Bom Jesus de Valverde',
      'coast',
      38.5235,
      -8.007,
      30,
      'A Renaissance convent by a stream, on a plan by the king’s architect. Quest: find the octagonal church.',
    ],
    [
      'jardim-publico',
      'Évora Public Garden',
      'nature',
      38.5655,
      -7.91,
      400,
      'A Romantic garden with peacocks and fake ruins. Quest: find the false ruins.',
    ],
    [
      'alto-sao-bento',
      'Alto de São Bento',
      'nature',
      38.585,
      -7.948,
      100,
      'Windmills on a granite hill above the plain. Quest: find the mill you can climb.',
    ],
    [
      'ecopista',
      'Ecopista of Évora',
      'nature',
      38.5795,
      -7.8985,
      60,
      'An old railway line turned into a path through the cork oaks. Quest: ride a kilometre.',
    ],
    [
      'mitra',
      'Herdade da Mitra',
      'nature',
      38.533,
      -8.015,
      30,
      'The archbishops’ estate of cork and holm oaks. Quest: find a cork oak with its bark stripped.',
    ],
    [
      'cartuxa',
      'Cartuxa Vineyards',
      'nature',
      38.581,
      -7.93,
      150,
      'Vines planted by Carthusian monks. Quest: find the monastery walls.',
    ],
    [
      'roman-temple',
      'Roman Temple of Évora',
      'heritage',
      38.5728,
      -7.9073,
      3000,
      'Corinthian columns from the 1st century, once walled into a slaughterhouse. Quest: count the columns.',
    ],
    [
      'almendres',
      'Almendres Cromlech',
      'heritage',
      38.5575,
      -8.061,
      400,
      'Nearly 100 standing stones, older than Stonehenge. Quest: find the stone with a carved crook.',
    ],
    [
      'zambujeiro',
      'Anta Grande do Zambujeiro',
      'heritage',
      38.537,
      -8.013,
      40,
      'One of the largest dolmens in Europe. Quest: find its capstone.',
    ],
    [
      'dom-manuel',
      'Palace of King Manuel',
      'heritage',
      38.5665,
      -7.908,
      60,
      'The Ladies’ Gallery of a palace where Vasco da Gama got his orders. Quest: find the arches.',
    ],
    [
      'aqueduct',
      'Água de Prata Aqueduct',
      'heritage',
      38.5755,
      -7.9105,
      300,
      'Built in 1537; houses are tucked between its arches. Quest: find a door in an arch.',
    ],
    [
      'se',
      'Évora Cathedral',
      'culture',
      38.5705,
      -7.907,
      1500,
      'A fortress-like Gothic cathedral with a rooftop walk. Quest: climb to the roof.',
    ],
    [
      'university',
      'University of Évora',
      'culture',
      38.5735,
      -7.904,
      300,
      'A Jesuit college of 1559 with tiled classrooms. Quest: find a tiled lecture hall.',
    ],
    [
      'museu-evora',
      'Museum of Évora',
      'culture',
      38.5718,
      -7.9068,
      200,
      'Flemish altarpieces in the archbishops’ palace. Quest: find the Life of the Virgin.',
    ],
    [
      'artesanato',
      'Museum of Crafts and Design',
      'culture',
      38.5698,
      -7.9093,
      80,
      'Alentejo crafts from cork to clay. Quest: find a cork object.',
    ],
    [
      'biblioteca',
      'Évora Public Library',
      'culture',
      38.5715,
      -7.908,
      50,
      'One of Portugal’s oldest libraries. Quest: find the reading room.',
    ],
    [
      'fea',
      'Eugénio de Almeida Art Centre',
      'art',
      38.572,
      -7.9055,
      150,
      'Contemporary art in a palace by the temple. Quest: find the current show.',
    ],
    [
      'sao-bras',
      'Hermitage of São Brás',
      'art',
      38.564,
      -7.903,
      40,
      'A castle-like chapel of the 1480s with fortified turrets. Quest: count the turrets.',
    ],
    [
      'station-tiles',
      'Évora Station Tiles',
      'art',
      38.5605,
      -7.905,
      50,
      'Azulejo panels of Alentejo life on the old station. Quest: find the harvest scene.',
    ],
    [
      'santa-clara',
      'Santa Clara Convent Tiles',
      'art',
      38.566,
      -7.911,
      30,
      'A convent church lined with blue tiles. Quest: find the choir grille.',
    ],
    [
      'merces',
      'Mercês Church Tiles',
      'art',
      38.568,
      -7.903,
      30,
      'A museum of decorative arts in a tiled church. Quest: find the tile flowers.',
    ],
    [
      'garcia-resende',
      'Garcia de Resende Theatre',
      'music_events',
      38.5685,
      -7.9115,
      150,
      'An Italian-style theatre of 1892. Quest: find the painted ceiling.',
    ],
    [
      'sao-joao-fair',
      'São João Fair',
      'music_events',
      38.565,
      -7.902,
      300,
      'The great June fair of the Alentejo. Quest: try the fried farturas.',
    ],
    [
      'arena',
      'Évora Bullring',
      'music_events',
      38.5655,
      -7.905,
      200,
      'A bullring of 1890 that also hosts concerts and fairs. Quest: find the poster.',
    ],
    [
      'harmonia',
      'Harmonia Eborense',
      'music_events',
      38.5722,
      -7.9102,
      60,
      'A music society since 1849 on Giraldo Square. Quest: find the ballroom.',
    ],
    [
      'soror-mariana',
      'Soror Mariana Auditorium',
      'music_events',
      38.574,
      -7.9095,
      60,
      'A convent turned concert hall. Quest: catch a concert.',
    ],
    [
      'bones',
      'Chapel of Bones',
      'other',
      38.5687,
      -7.9093,
      2000,
      '“We bones that are here, await yours.” Quest: find the inscription.',
    ],
    [
      'mercado',
      'Évora Market',
      'culture',
      38.5665,
      -7.9035,
      300,
      'Alentejo cheese and sausages. Quest: buy a queijo de Évora.',
    ],
    [
      'rua-do-cano',
      'Rua do Cano',
      'other',
      38.577,
      -7.913,
      80,
      'A street where houses are built into the aqueduct. Quest: find a window in an arch.',
    ],
    [
      'pao-de-rala',
      'Pão de Rala',
      'culture',
      38.5705,
      -7.9035,
      200,
      'Convent sweets made to old nuns’ recipes. Quest: try a pão de rala.',
    ],
    [
      'menhir',
      'Almendres Menhir',
      'other',
      38.564,
      -8.056,
      60,
      'A lone standing stone in the cork oaks. Quest: find it.',
    ],
    [
      'sao-miguel',
      'Pátio de São Miguel',
      'heritage',
      38.5727,
      -7.9085,
      5,
      'A hidden courtyard of the counts of Basto. Quest: find the Moorish arch.',
      'hidden',
    ],
    [
      'cinco-quinas',
      'Torre das Cinco Quinas',
      'other',
      38.5745,
      -7.902,
      5,
      'A five-cornered tower from the old walls. Quest: count the corners.',
      'hidden',
    ],
  ]),

  ...quests('aveiro', [
    [
      'costa-nova',
      'Costa Nova Beach',
      'coast',
      40.614,
      -8.752,
      1500,
      'Atlantic dunes beside the striped fishermen’s houses. Quest: watch the surfers.',
    ],
    [
      'barra',
      'Praia da Barra',
      'coast',
      40.642,
      -8.747,
      800,
      'A beach under Portugal’s tallest lighthouse. Quest: find the lighthouse.',
    ],
    [
      'sao-jacinto',
      'São Jacinto Beach',
      'coast',
      40.668,
      -8.744,
      200,
      'A wild beach reached by ferry. Quest: cross by boat.',
    ],
    [
      'vagueira',
      'Vagueira Beach',
      'coast',
      40.56,
      -8.768,
      300,
      'Fishermen still haul nets with tractors. Quest: watch the arte xávega.',
    ],
    [
      'salt-pans',
      'Troncalhada Salt Pans',
      'coast',
      40.6435,
      -8.662,
      200,
      'Salt made the old way in the lagoon. Quest: find the salt flower.',
    ],
    [
      'sao-jacinto-dunes',
      'São Jacinto Dunes Reserve',
      'nature',
      40.685,
      -8.73,
      150,
      'Dunes and pine forest between sea and lagoon. Quest: find the bird hide.',
    ],
    [
      'parque-d-pedro',
      'Infante D. Pedro Park',
      'nature',
      40.6365,
      -8.652,
      300,
      'A city park with a lake and tiled stairs. Quest: find the tiled stairs.',
    ],
    [
      'fermentelos',
      'Pateira de Fermentelos',
      'nature',
      40.573,
      -8.522,
      100,
      'A lagoon of reeds and herons. Quest: spot a heron.',
    ],
    [
      'bioria',
      'BioRia Salreu',
      'nature',
      40.73,
      -8.565,
      80,
      'Wetland trails through rice fields. Quest: find the tower.',
    ],
    [
      'canal-piramides',
      'Canal das Pirâmides',
      'other',
      40.642,
      -8.66,
      200,
      'The canal where the lagoon meets the city, its mouth marked by two stone pyramids. Quest: find the pyramids.',
    ],
    [
      'se',
      'Aveiro Cathedral',
      'heritage',
      40.639,
      -8.6505,
      300,
      'A Dominican convent church of 1423. Quest: find the cross outside.',
    ],
    [
      'barra-lighthouse',
      'Barra Lighthouse',
      'heritage',
      40.643,
      -8.748,
      400,
      'The tallest lighthouse in Portugal, 62 m. Quest: count the stripes.',
    ],
    [
      'vista-alegre-palace',
      'Vista Alegre Palace and Chapel',
      'heritage',
      40.587,
      -8.678,
      60,
      'A porcelain factory’s palace and baroque chapel. Quest: find the bishop’s tomb.',
    ],
    [
      'goncalinho',
      'Chapel of São Gonçalinho',
      'heritage',
      40.6445,
      -8.6555,
      100,
      'In January locals throw cakes from its roof. Quest: find the dome.',
    ],
    [
      'forte-barra',
      'Forte da Barra',
      'heritage',
      40.644,
      -8.734,
      50,
      'A tower guarding the lagoon’s mouth. Quest: find the tower.',
    ],
    [
      'museu-aveiro',
      'Museum of Aveiro',
      'culture',
      40.6383,
      -8.6525,
      200,
      'The convent of Princess Joana, with her marble tomb. Quest: find the tomb.',
    ],
    [
      'ilhavo',
      'Ílhavo Maritime Museum',
      'culture',
      40.6,
      -8.668,
      300,
      'The cod fishing fleets, and an aquarium of cod. Quest: find the cod aquarium.',
    ],
    [
      'arte-nova',
      'Art Nouveau Museum',
      'culture',
      40.6418,
      -8.6535,
      500,
      'A house of curving balconies on the canal. Quest: find the tea room.',
    ],
    [
      'station',
      'Old Aveiro Station',
      'culture',
      40.644,
      -8.64,
      300,
      'Tiled scenes of the region on the 1916 station. Quest: find a moliceiro tile.',
    ],
    [
      'fabrica',
      'Fábrica Ciência Viva',
      'culture',
      40.64,
      -8.656,
      100,
      'A science centre in an old factory. Quest: find the experiment.',
    ],
    [
      'vista-alegre-museum',
      'Vista Alegre Museum',
      'art',
      40.5885,
      -8.68,
      200,
      'Two centuries of Portuguese porcelain. Quest: find the oldest piece.',
    ],
    [
      'moliceiros',
      'Moliceiro Prows',
      'art',
      40.6428,
      -8.656,
      800,
      'Boats with painted prows, often cheeky. Quest: find a funny prow.',
    ],
    [
      'cooperativa',
      'Cooperativa Agrícola Building',
      'art',
      40.641,
      -8.6545,
      100,
      'Art Nouveau tiles of flowers on a farm co-op. Quest: find the irises.',
    ],
    [
      'capitania',
      'Antiga Capitania Gallery',
      'art',
      40.6425,
      -8.651,
      60,
      'Art in the old harbour master’s house. Quest: find the show.',
    ],
    [
      'palheiros',
      'Costa Nova Striped Houses',
      'art',
      40.619,
      -8.749,
      1000,
      'Fishermen painted their sheds in stripes to find them in the fog. Quest: find your colour.',
    ],
    [
      'aveirense',
      'Teatro Aveirense',
      'music_events',
      40.6405,
      -8.6475,
      200,
      'A theatre of 1881. Quest: catch a show.',
    ],
    [
      'feira-marco',
      'Feira de Março',
      'music_events',
      40.629,
      -8.641,
      400,
      'A fair held every March for 600 years. Quest: ride the ferris wheel.',
    ],
    [
      'gretua',
      'GrETUA',
      'music_events',
      40.6305,
      -8.658,
      60,
      'The students’ theatre. Quest: catch a gig.',
    ],
    [
      'congressos',
      'Centro de Congressos',
      'music_events',
      40.6425,
      -8.642,
      100,
      'A tile factory turned venue. Quest: find the chimney.',
    ],
    [
      'canais',
      'Festival dos Canais',
      'music_events',
      40.644,
      -8.653,
      300,
      'Street theatre and music on the canals in July. Quest: find a stage on the water.',
    ],
    [
      'ovos-moles',
      'Ovos Moles',
      'culture',
      40.6415,
      -8.6505,
      800,
      'Egg sweets in wafer shells shaped like shells and fish. Quest: try one.',
    ],
    [
      'mercado-peixe',
      'Mercado do Peixe',
      'culture',
      40.6445,
      -8.6575,
      300,
      'The fish market by the canal. Quest: find the grilled sardines.',
    ],
    [
      'lacos',
      'Bridge of Friendship Ribbons',
      'other',
      40.643,
      -8.653,
      600,
      'Ribbons tied by friends and lovers. Quest: tie one.',
    ],
    [
      'moliceiro-ride',
      'Moliceiro Boat Ride',
      'other',
      40.6415,
      -8.6558,
      1000,
      'The boats that once gathered seaweed. Quest: take a ride.',
    ],
    [
      'sao-jacinto-ferry',
      'São Jacinto Ferry',
      'other',
      40.665,
      -8.739,
      100,
      'A ferry across the lagoon mouth. Quest: cross.',
    ],
    [
      'misericordia',
      'Misericórdia Church',
      'heritage',
      40.6413,
      -8.652,
      5,
      'A tiled church with a lions’ portal. Quest: find the lions.',
      'hidden',
    ],
    [
      'botiroes',
      'Cais dos Botirões',
      'other',
      40.6455,
      -8.651,
      5,
      'Tiles of old fishermen on the quay. Quest: find the tile.',
      'hidden',
    ],
  ]),
];
