import { quests } from '../place-in';

// Side quests written as a travelling historian would brief you: a line of history, then what to
// go and find. Heritage leans on the quieter palaces and quintas rather than the famous queues.

export const SPAIN_QUESTS = [
  ...quests('madrid', [
    [
      'retiro-pond',
      'Retiro Great Pond',
      'coast',
      40.418,
      -3.683,
      2000,
      'Philip IV staged mock sea battles here. Quest: row past the Alfonso XII monument.',
    ],
    [
      'madrid-rio-beach',
      'Madrid Río Urban Beach',
      'coast',
      40.4045,
      -3.72,
      600,
      'Fountains and sand along the reclaimed Manzanares. Quest: cool off in the spray.',
    ],
    [
      'juan-carlos-lake',
      'Juan Carlos I Park Lake',
      'coast',
      40.463,
      -3.608,
      300,
      'A park with a lake and an olive grove on a former airfield. Quest: walk around the lake.',
    ],
    [
      'segovia-bridge',
      'Segovia Bridge',
      'coast',
      40.415,
      -3.721,
      150,
      'Philip II’s granite bridge over the Manzanares. Quest: photograph it from the riverbank.',
    ],
    [
      'toledo-bridge',
      'Toledo Bridge',
      'coast',
      40.404,
      -3.713,
      150,
      'A baroque bridge with statues of Madrid’s patron saints. Quest: find San Isidro.',
    ],
    [
      'capricho',
      'El Capricho Park',
      'nature',
      40.456,
      -3.599,
      200,
      'The Duchess of Osuna’s 18th-century romantic garden. Quest: find the hermit’s house.',
    ],
    [
      'liria',
      'Liria Palace',
      'heritage',
      40.428,
      -3.713,
      40,
      'The Duke of Alba’s private palace, with Goyas and Titians. Quest: see the facade from Calle Princesa.',
    ],
    [
      'descalzas',
      'Descalzas Reales Monastery',
      'heritage',
      40.4185,
      -3.706,
      150,
      'A convent for royal princesses, full of treasures. Quest: find the Rubens tapestries.',
    ],
    [
      'linares',
      'Linares Palace',
      'heritage',
      40.4195,
      -3.6925,
      60,
      'A palace of the 1870s said to be haunted. Quest: find the Casa de América sign.',
    ],
    [
      'cerralbo',
      'Cerralbo Museum',
      'culture',
      40.424,
      -3.7145,
      120,
      'A marquis’s palace left exactly as he furnished it. Quest: find the ballroom.',
    ],
    [
      'sorolla',
      'Sorolla Museum',
      'culture',
      40.4355,
      -3.6925,
      200,
      'The painter’s house and Andalusian garden. Quest: find his studio.',
    ],
    [
      'florida',
      'San Antonio de la Florida',
      'art',
      40.4252,
      -3.727,
      150,
      'Goya painted its dome in 1798 and is buried beneath it. Quest: find his tomb.',
    ],
    [
      'lazaro-galdiano',
      'Lázaro Galdiano Museum',
      'art',
      40.4405,
      -3.6855,
      120,
      'A collector’s mansion of Bosch, Goya and enamels. Quest: find Goya’s witches.',
    ],
    [
      'cafe-central',
      'Café Central',
      'music_events',
      40.4145,
      -3.7005,
      300,
      'A jazz café in an old glass shop. Quest: catch a set.',
    ],
    [
      'corral-moreria',
      'Corral de la Morería',
      'music_events',
      40.4128,
      -3.7145,
      400,
      'A flamenco tablao since 1956. Quest: watch the zapateado.',
    ],
    [
      'zarzuela',
      'Teatro de la Zarzuela',
      'music_events',
      40.4175,
      -3.6965,
      200,
      'Built in 1856 for Spain’s own light opera. Quest: find out what’s on.',
    ],
    [
      'wizink',
      'WiZink Center',
      'music_events',
      40.4235,
      -3.6715,
      500,
      'Madrid’s big indoor arena. Quest: catch a concert.',
    ],
    [
      'las-ventas',
      'Las Ventas',
      'music_events',
      40.432,
      -3.6635,
      400,
      'A neo-Mudéjar ring of 1931 that also hosts concerts. Quest: photograph the tilework.',
    ],
    [
      'chamberi',
      'Chamberí Ghost Station',
      'culture',
      40.4325,
      -3.701,
      200,
      'A metro station closed in 1966 and left as it was. Quest: find the old adverts.',
    ],
    [
      'principe-pio',
      'Príncipe Pío Station',
      'culture',
      40.421,
      -3.72,
      300,
      'An iron station of 1881 turned into a shopping hall. Quest: find the old platform roof.',
    ],
    [
      'railway-museum',
      'Railway Museum (Delicias)',
      'culture',
      40.3985,
      -3.693,
      150,
      'Steam engines in an iron station of 1880. Quest: find the oldest locomotive.',
    ],
    [
      'rastro',
      'El Rastro',
      'other',
      40.4085,
      -3.7075,
      1500,
      'A Sunday flea market for 500 years. Quest: find an old map.',
    ],
    [
      'botin',
      'Sobrino de Botín',
      'other',
      40.4142,
      -3.7085,
      800,
      'The oldest restaurant in the world, says Guinness. Quest: find the old wood oven.',
    ],
    [
      'oso-madrono',
      'Bear and Strawberry Tree',
      'other',
      40.417,
      -3.7035,
      2000,
      'The statue of the city’s coat of arms. Quest: touch the bear.',
    ],
    [
      'lhardy',
      'Lhardy',
      'other',
      40.4163,
      -3.7013,
      400,
      'Since 1839 the consommé is poured from a silver samovar. Quest: pour your own cup.',
    ],
  ]),

  ...quests('barcelona', [
    [
      'bogatell',
      'Bogatell Beach',
      'coast',
      41.3945,
      2.2055,
      800,
      'Built for the 1992 Olympics on old factory land. Quest: walk to the breakwater.',
    ],
    [
      'nova-icaria',
      'Nova Icària Beach',
      'coast',
      41.3905,
      2.2015,
      900,
      'Named for a 19th-century utopian commune. Quest: find the Olympic Port.',
    ],
    [
      'mar-bella',
      'Mar Bella Beach',
      'coast',
      41.399,
      2.2115,
      400,
      'Barcelona’s sporty beach. Quest: watch the sailing boats.',
    ],
    [
      'sant-sebastia',
      'Sant Sebastià Beach',
      'coast',
      41.371,
      2.188,
      800,
      'The city’s oldest beach, by the sail-shaped hotel. Quest: find the old baths.',
    ],
    [
      'ciutadella-lake',
      'Ciutadella Park Cascade',
      'nature',
      41.3895,
      2.1885,
      800,
      'A fountain on which young Gaudí worked. Quest: find the griffins.',
    ],
    [
      'pedralbes',
      'Pedralbes Monastery',
      'heritage',
      41.3955,
      2.1125,
      150,
      'A Gothic convent founded by a queen in 1327. Quest: find the queen’s tomb.',
    ],
    [
      'sant-pau',
      'Sant Pau Recinte Modernista',
      'heritage',
      41.4115,
      2.1745,
      300,
      'Domènech i Montaner’s hospital, a city of pavilions. Quest: find the tunnels.',
    ],
    [
      'palau-guell',
      'Palau Güell',
      'heritage',
      41.379,
      2.1745,
      400,
      'Gaudí’s first great work, with a rooftop of chimneys. Quest: find the red chimney.',
    ],
    [
      'santa-maria-mar',
      'Santa Maria del Mar',
      'culture',
      41.3837,
      2.182,
      1000,
      'The church built by the porters of the port. Quest: find the porter carvings.',
    ],
    [
      'els-quatre-gats',
      'Els Quatre Gats',
      'culture',
      41.3855,
      2.1735,
      600,
      'The café where young Picasso had his first show. Quest: order a coffee.',
    ],
    [
      'tapies',
      'Fundació Antoni Tàpies',
      'art',
      41.3915,
      2.1635,
      200,
      'Tàpies crowned the building with a tangle of wire. Quest: photograph the cloud.',
    ],
    [
      'mnac',
      'MNAC',
      'art',
      41.3685,
      2.1535,
      500,
      'Romanesque murals rescued from Pyrenean churches. Quest: find Christ in Majesty.',
    ],
    [
      'razzmatazz',
      'Razzmatazz',
      'music_events',
      41.3975,
      2.191,
      400,
      'A warehouse club with five rooms. Quest: find the smallest room.',
    ],
    [
      'sala-apolo',
      'Sala Apolo',
      'music_events',
      41.3745,
      2.169,
      300,
      'A ballroom of 1943. Quest: find the balcony.',
    ],
    [
      'magic-fountain',
      'Magic Fountain of Montjuïc',
      'music_events',
      41.371,
      2.1517,
      2000,
      'Fountains that dance to music since 1929. Quest: catch the show.',
    ],
    [
      'jamboree',
      'Jamboree Jazz Club',
      'music_events',
      41.3805,
      2.175,
      300,
      'A cellar jazz club on Plaça Reial since 1960. Quest: find the cellar steps.',
    ],
    [
      'franca',
      'Estació de França',
      'culture',
      41.3845,
      2.1855,
      200,
      'An iron and glass station of 1929. Quest: look up at the roof.',
    ],
    [
      'tramvia-blau',
      'Tramvia Blau',
      'culture',
      41.4115,
      2.1365,
      150,
      'Barcelona’s blue tram climbing to Tibidabo. Quest: find the tram stop.',
    ],
    [
      'funicular-montjuic',
      'Montjuïc Funicular',
      'culture',
      41.375,
      2.168,
      300,
      'A hidden funicular inside the hill. Quest: ride to the top.',
    ],
    [
      'boqueria',
      'La Boqueria',
      'other',
      41.3817,
      2.1717,
      4000,
      'A market since 1217. Quest: find the egg stall.',
    ],
    [
      'sant-felip-neri',
      'Plaça de Sant Felip Neri',
      'other',
      41.3832,
      2.1745,
      600,
      'A quiet square whose church walls still bear 1938 shrapnel scars. Quest: find the marks.',
    ],
    [
      'marsella',
      'Bar Marsella',
      'other',
      41.3785,
      2.172,
      400,
      'Absinthe served the old way since 1820. Quest: watch the sugar cube melt.',
    ],
    [
      'walden',
      'Walden 7',
      'other',
      41.375,
      2.0565,
      50,
      'Ricardo Bofill’s red tower block. Quest: photograph the courtyard.',
    ],
    [
      'sant-antoni',
      'Sant Antoni Market',
      'other',
      41.3785,
      2.162,
      600,
      'An iron market of 1882 with a Sunday book fair. Quest: find an old comic.',
    ],
  ]),

  ...quests('basque', [
    [
      'concha',
      'La Concha Beach',
      'coast',
      43.3175,
      -1.986,
      3000,
      'The shell-shaped bay the royal family made fashionable in the 1880s. Quest: walk the railings.',
    ],
    [
      'zurriola',
      'Zurriola Beach',
      'coast',
      43.3255,
      -1.974,
      1000,
      'San Sebastián’s surf beach. Quest: watch the surfers at sunset.',
    ],
    [
      'gaztelugatxe',
      'San Juan de Gaztelugatxe',
      'coast',
      43.447,
      -2.7845,
      2000,
      'A hermitage on an islet up 241 steps. Quest: ring the bell three times.',
    ],
    [
      'zarautz',
      'Zarautz Beach',
      'coast',
      43.285,
      -2.17,
      600,
      'A long surf beach. Quest: find the old palace on the seafront.',
    ],
    [
      'sopelana',
      'Sopelana Cliffs',
      'coast',
      43.3875,
      -2.9965,
      300,
      'Surf beaches below flysch cliffs. Quest: find the folded rock layers.',
    ],
    [
      'urdaibai',
      'Urdaibai Marshes',
      'nature',
      43.36,
      -2.68,
      200,
      'A biosphere reserve. Quest: spot a heron.',
    ],
    [
      'igueldo',
      'Mount Igueldo',
      'nature',
      43.3095,
      -2.0085,
      800,
      'An old funfair on a hilltop. Quest: ride the old roller coaster.',
    ],
    [
      'urgull',
      'Mount Urgull',
      'nature',
      43.3265,
      -1.9865,
      600,
      'A castle hill with English soldiers’ graves. Quest: find the cemetery.',
    ],
    [
      'artxanda',
      'Mount Artxanda',
      'nature',
      43.2725,
      -2.9225,
      400,
      'Bilbao’s viewpoint hill. Quest: find the giant fork.',
    ],
    [
      'pagasarri',
      'Pagasarri',
      'nature',
      43.225,
      -2.935,
      200,
      'The Bilbaínos’ Sunday hill. Quest: reach the refuge.',
    ],
    [
      'miramar',
      'Miramar Palace',
      'heritage',
      43.3145,
      -1.995,
      100,
      'A royal summer palace of 1893. Quest: walk its lawns.',
    ],
    [
      'gernika-tree',
      'Tree of Gernika',
      'heritage',
      43.3148,
      -2.6785,
      400,
      'Under the oak the Basque assemblies met. Quest: find the old trunk.',
    ],
    [
      'aiete',
      'Aiete Palace',
      'heritage',
      43.3075,
      -1.98,
      30,
      'A summer palace of 1878 where Spanish queens and, later, Franco stayed. Quest: find the pond in its park.',
    ],
    [
      'butron',
      'Butrón Castle',
      'heritage',
      43.3555,
      -2.8515,
      30,
      'A fairytale castle rebuilt in the 19th century. Quest: photograph the towers.',
    ],
    [
      'arteaga',
      'Arteaga Castle',
      'heritage',
      43.3505,
      -2.651,
      20,
      'Napoleon III built it for Empress Eugénie. Quest: find the eagle.',
    ],
    [
      'guggenheim',
      'Guggenheim Bilbao',
      'culture',
      43.2687,
      -2.934,
      4000,
      'Gehry’s titanium ship. Quest: find Puppy.',
    ],
    [
      'san-telmo',
      'San Telmo Museum',
      'culture',
      43.3245,
      -1.983,
      300,
      'A convent turned museum. Quest: find the giant murals.',
    ],
    [
      'euskal-museoa',
      'Basque Museum',
      'culture',
      43.2585,
      -2.9235,
      150,
      'Basque life and the old stone idol. Quest: find the idol of Mikeldi.',
    ],
    [
      'ribera-market',
      'Ribera Market',
      'culture',
      43.2565,
      -2.924,
      400,
      'A deco market on the river. Quest: find the stained glass.',
    ],
    [
      'chillida-leku',
      'Chillida Leku',
      'culture',
      43.279,
      -1.988,
      200,
      'Chillida’s sculpture garden. Quest: find a giant iron.',
    ],
    [
      'peine-viento',
      'Comb of the Wind',
      'art',
      43.3215,
      -2.0055,
      1000,
      'Chillida’s iron claws at the end of the bay. Quest: feel the blowholes.',
    ],
    [
      'bellas-artes',
      'Bilbao Fine Arts Museum',
      'art',
      43.2665,
      -2.9375,
      300,
      'From El Greco to Basque modernism. Quest: find a Zuloaga.',
    ],
    [
      'tabakalera',
      'Tabakalera',
      'art',
      43.3175,
      -1.976,
      200,
      'A tobacco factory turned art centre. Quest: find the rooftop.',
    ],
    [
      'maman',
      'Maman',
      'art',
      43.2685,
      -2.9365,
      1500,
      'Louise Bourgeois’s giant spider. Quest: stand beneath her.',
    ],
    [
      'azkuna',
      'Azkuna Zentroa',
      'art',
      43.2595,
      -2.9395,
      300,
      'A wine warehouse on 43 columns. Quest: find the glass-bottomed pool.',
    ],
    [
      'kursaal',
      'Kursaal',
      'music_events',
      43.3245,
      -1.9785,
      400,
      'Moneo’s two glass cubes. Quest: find the cube in the sea.',
    ],
    [
      'euskalduna',
      'Euskalduna Palace',
      'music_events',
      43.2665,
      -2.9475,
      200,
      'A concert hall shaped like a ship. Quest: find the shipyard crane.',
    ],
    [
      'arriaga',
      'Arriaga Theatre',
      'music_events',
      43.2585,
      -2.9255,
      200,
      'An opera house named after the Basque Mozart. Quest: find the bust.',
    ],
    [
      'bbk-live',
      'Kobetamendi',
      'music_events',
      43.2575,
      -2.9555,
      300,
      'The hill that hosts BBK Live festival. Quest: find the stage.',
    ],
    [
      'illumbe',
      'Illumbe Bullring',
      'music_events',
      43.2985,
      -1.979,
      300,
      'San Sebastián’s covered bullring, where the corridas of the Semana Grande are held each August. Quest: find this year’s fair poster.',
    ],
    [
      'jazzaldia',
      'Jazzaldia at Trinidad Square',
      'music_events',
      43.3245,
      -1.9855,
      300,
      'Europe’s oldest jazz festival. Quest: find the square.',
    ],
    [
      'vizcaya-bridge',
      'Vizcaya Bridge',
      'culture',
      43.3235,
      -3.017,
      600,
      'The world’s oldest transporter bridge, 1893. Quest: ride the gondola.',
    ],
    [
      'abando',
      'Abando Station',
      'culture',
      43.2605,
      -2.9265,
      300,
      'A station with a stained-glass window. Quest: find the window.',
    ],
    [
      'igueldo-funicular',
      'Igueldo Funicular',
      'culture',
      43.3075,
      -2.0035,
      600,
      'A funicular of 1912. Quest: ride it.',
    ],
    [
      'zubizuri',
      'Zubizuri Bridge',
      'culture',
      43.2675,
      -2.9285,
      500,
      'Calatrava’s white bridge. Quest: walk across.',
    ],
    [
      'larreineta',
      'Larreineta Funicular',
      'culture',
      43.255,
      -3.0475,
      100,
      'A miners’ funicular. Quest: ride it.',
    ],
    [
      'parte-vieja',
      'Parte Vieja Pintxos',
      'other',
      43.3235,
      -1.985,
      2000,
      'The pintxo bars of San Sebastián. Quest: try a gilda.',
    ],
    [
      'bretxa',
      'La Bretxa Market',
      'other',
      43.3225,
      -1.9835,
      300,
      'Market on the breach the British blew in the walls in 1813. Quest: find the fish hall.',
    ],
    [
      'casco-viejo',
      'Siete Calles',
      'other',
      43.2575,
      -2.9225,
      800,
      'Bilbao’s Seven Streets. Quest: walk all seven.',
    ],
    [
      'gernika-market',
      'Gernika Market',
      'other',
      43.3165,
      -2.676,
      100,
      'A Monday market. Quest: buy a cheese.',
    ],
    [
      'ondarreta',
      'Ondarreta Beach',
      'other',
      43.3185,
      -2.0005,
      400,
      'The quiet end of the bay. Quest: find the tamarinds.',
    ],
    [
      'mallona',
      'Calzadas de Mallona',
      'other',
      43.2585,
      -2.9205,
      5,
      'The 300-odd steps pilgrims climbed from the old town to Begoña. Quest: count them on the way up.',
      'hidden',
    ],
  ]),
];
