// Generated by scripts/render-explorers.mjs. Do not edit by hand.
import type { ImageSource } from 'expo-image';
import type { ExplorerId, ExplorerKit } from '@wandro/shared';

export type OutfitKey = 'default' | 'skin_ocean' | 'skin_coral' | 'skin_midnight' | 'skin_gold';

/* eslint-disable @typescript-eslint/no-require-imports -- static asset requires for Metro */
export const EXPLORER_ART: Record<ExplorerId, Record<OutfitKey, ImageSource>> = {
  e1: {
    default: require('../assets/explorers/e1-default.png'),
    skin_ocean: require('../assets/explorers/e1-skin_ocean.png'),
    skin_coral: require('../assets/explorers/e1-skin_coral.png'),
    skin_midnight: require('../assets/explorers/e1-skin_midnight.png'),
    skin_gold: require('../assets/explorers/e1-skin_gold.png'),
  },
  e2: {
    default: require('../assets/explorers/e2-default.png'),
    skin_ocean: require('../assets/explorers/e2-skin_ocean.png'),
    skin_coral: require('../assets/explorers/e2-skin_coral.png'),
    skin_midnight: require('../assets/explorers/e2-skin_midnight.png'),
    skin_gold: require('../assets/explorers/e2-skin_gold.png'),
  },
  e3: {
    default: require('../assets/explorers/e3-default.png'),
    skin_ocean: require('../assets/explorers/e3-skin_ocean.png'),
    skin_coral: require('../assets/explorers/e3-skin_coral.png'),
    skin_midnight: require('../assets/explorers/e3-skin_midnight.png'),
    skin_gold: require('../assets/explorers/e3-skin_gold.png'),
  },
  e4: {
    default: require('../assets/explorers/e4-default.png'),
    skin_ocean: require('../assets/explorers/e4-skin_ocean.png'),
    skin_coral: require('../assets/explorers/e4-skin_coral.png'),
    skin_midnight: require('../assets/explorers/e4-skin_midnight.png'),
    skin_gold: require('../assets/explorers/e4-skin_gold.png'),
  },
  e5: {
    default: require('../assets/explorers/e5-default.png'),
    skin_ocean: require('../assets/explorers/e5-skin_ocean.png'),
    skin_coral: require('../assets/explorers/e5-skin_coral.png'),
    skin_midnight: require('../assets/explorers/e5-skin_midnight.png'),
    skin_gold: require('../assets/explorers/e5-skin_gold.png'),
  },
  e6: {
    default: require('../assets/explorers/e6-default.png'),
    skin_ocean: require('../assets/explorers/e6-skin_ocean.png'),
    skin_coral: require('../assets/explorers/e6-skin_coral.png'),
    skin_midnight: require('../assets/explorers/e6-skin_midnight.png'),
    skin_gold: require('../assets/explorers/e6-skin_gold.png'),
  },
  e7: {
    default: require('../assets/explorers/e7-default.png'),
    skin_ocean: require('../assets/explorers/e7-skin_ocean.png'),
    skin_coral: require('../assets/explorers/e7-skin_coral.png'),
    skin_midnight: require('../assets/explorers/e7-skin_midnight.png'),
    skin_gold: require('../assets/explorers/e7-skin_gold.png'),
  },
  e8: {
    default: require('../assets/explorers/e8-default.png'),
    skin_ocean: require('../assets/explorers/e8-skin_ocean.png'),
    skin_coral: require('../assets/explorers/e8-skin_coral.png'),
    skin_midnight: require('../assets/explorers/e8-skin_midnight.png'),
    skin_gold: require('../assets/explorers/e8-skin_gold.png'),
  },
};

export const KIT_ART: Record<ExplorerKit, ImageSource> = {
  map: require('../assets/explorers/kit-map.png'),
  backpack: require('../assets/explorers/kit-backpack.png'),
  camera: require('../assets/explorers/kit-camera.png'),
};
/* eslint-enable @typescript-eslint/no-require-imports */
