import type { PlaceDetails } from '../types';

/**
 * Learn and Plan content for Sintra, keyed by place id. Facts are kept short and checkable;
 * the pilot city for place details (review before adding the other cities).
 */
export const SINTRA_DETAILS: Record<string, PlaceDetails> = {
  'demo-pena': {
    teaser: 'A fairy-tale palace painted red and yellow on a peak above the clouds.',
    facts: [
      'King Ferdinand II, a German prince known as the "Artist King", built it in the mid-1800s.',
      'It rises around the ruins of a 16th-century monastery, whose cloister and chapel survive inside.',
      'It is part of the Cultural Landscape of Sintra, a UNESCO World Heritage Site since 1995.',
    ],
    lookFor: 'The Triton arch: a sea monster holding up a window on its back.',
    bestTime: 'The first entry slot of the morning; tour coaches arrive later.',
    durationMin: 120,
    cost: 'ticket',
    access: 'steep',
  },
  'demo-regaleira': {
    teaser: 'A millionaire’s mystical garden of grottoes, towers and secret tunnels.',
    facts: [
      'The Initiation Well spirals about 27 m down, with nine landings, and was never used for water.',
      'Its owner, António Augusto Carvalho Monteiro, was nicknamed “Monteiro the Millionaire”.',
      'The Italian architect Luigi Manini designed the palace and gardens in the early 1900s.',
    ],
    lookFor: 'The stepping stones across the lake grotto.',
    bestTime: 'Right at opening, before the queue reaches the gate.',
    durationMin: 120,
    cost: 'ticket',
    access: 'some_steps',
  },
  'demo-mouros': {
    teaser: 'Stone walls that snake along the ridge like a dragon’s back.',
    facts: [
      'The Moors built it in the 8th and 9th centuries; Christian forces took it after Lisbon fell in 1147.',
      'King Ferdinand II restored the ruined walls in the 1800s, while building Pena next door.',
      'From its towers you can see Pena Palace, the town and, on clear days, the ocean.',
    ],
    lookFor: 'The Royal Tower, the highest point of the walls.',
    bestTime: 'Late afternoon, when the hills are clear of fog.',
    durationMin: 75,
    cost: 'ticket',
    access: 'steep',
  },
  'demo-monserrate': {
    teaser: 'An Indian-inspired summer palace in a garden of plants from five continents.',
    facts: [
      'The English art collector Francis Cook rebuilt it in the 1860s on the ruins of an older house.',
      'Lord Byron visited the earlier ruin in 1809 and wrote about it in “Childe Harold”.',
      'Its gardens mix Mexican agaves, Australian tree ferns and Himalayan rhododendrons.',
    ],
    lookFor: 'The domed music room at the end of the gallery.',
    bestTime: 'Weekday mornings, when the gardens are quiet.',
    durationMin: 120,
    cost: 'ticket',
    access: 'some_steps',
  },
  'demo-capuchos': {
    teaser: 'A 16th-century convent where friars lived in tiny cells lined with cork.',
    facts: [
      'It was founded in 1560 for a small community of Franciscan friars.',
      'Cork lined the walls and doors to keep out the cold and damp of the forest.',
      'The doorways are so low that visitors have to bow to go through, a lesson in humility.',
    ],
    lookFor: 'A cork-lined cell door, barely as tall as a child.',
    bestTime: 'Any time; it’s cool and shaded even in summer.',
    durationMin: 45,
    cost: 'ticket',
    access: 'some_steps',
  },
  'demo-seteais': {
    teaser: 'A neoclassical palace whose arch frames Pena on the hilltop.',
    facts: [
      'It was built in the late 1700s for the Dutch consul Daniel Gildemeester.',
      'The triumphal arch celebrates a visit by the future King John VI in 1802.',
      'The palace is a hotel today, but you can walk to the arch and its lawn.',
    ],
    lookFor: 'Pena Palace framed in the middle of the arch.',
    bestTime: 'Golden hour, before sunset.',
    durationMin: 20,
    cost: 'free',
    access: 'step_free',
  },
  'demo-cabo': {
    teaser: 'Where the land ends and the sea begins: Europe’s westernmost point.',
    facts: [
      'The poet Luís de Camões described it as the place “where the land ends and the sea begins”.',
      'The cliffs rise about 140 m above the Atlantic.',
      'Its lighthouse has guarded the cape since 1772.',
    ],
    lookFor: 'The stone monument with Camões’s line and the coordinates.',
    bestTime: 'Sunset, with a jacket: it is almost always windy.',
    durationMin: 30,
    cost: 'free',
    access: 'step_free',
    tip: 'Stay behind the fences; the cliff edges are unstable.',
  },
  'demo-adraga': {
    teaser: 'A wild cove of sea arches and rock stacks under steep cliffs.',
    facts: [
      'Its rock arch and sea stacks are among the most photographed on the Sintra coast.',
      'A family restaurant has served grilled fish right on the sand for decades.',
    ],
    lookFor: 'The natural rock arch at the northern end of the beach.',
    bestTime: 'Summer evenings at low tide.',
    durationMin: 90,
    cost: 'free',
    access: 'some_steps',
    tip: 'The Atlantic is strong here: swim only between the flags when lifeguards are on duty.',
  },
  'demo-condessa': {
    teaser: 'An Alpine-style chalet a king built for an opera singer.',
    facts: [
      'Ferdinand II built it in the 1860s with Elise Hensler, the singer he later married.',
      'Its decoration uses cork, the local material of the Sintra hills.',
      'Fire gutted it in 1999; it was restored and reopened in 2011.',
    ],
    lookFor: 'The cork trim around the windows and doors.',
    bestTime: 'Pair it with Pena: it sits in the quieter western part of the park.',
    durationMin: 45,
    cost: 'ticket',
    access: 'trail',
  },
  'demo-cruz-alta': {
    teaser: 'The roof of the Sintra hills, marked by a stone cross.',
    facts: [
      'At about 529 m, it is the highest point of the Sintra hills.',
      'King Ferdinand II replaced the original 16th-century cross in the 1800s.',
      'You look down on Pena Palace from here.',
    ],
    lookFor: 'Pena’s yellow towers below you.',
    bestTime: 'Clear mornings.',
    durationMin: 40,
    cost: 'ticket',
    access: 'trail',
  },
  'demo-brinquedo': {
    teaser: 'Toys from across the centuries, from tin soldiers to model trains.',
    facts: ['It grew from one collector’s childhood toys into thousands of pieces.'],
    bestTime: 'A rainy day.',
    durationMin: 60,
    cost: 'ticket',
    tip: 'Check it’s open before you go.',
  },
  'demo-music': {
    teaser: 'A small local room for fado nights.',
    facts: [
      'Fado has been on UNESCO’s list of Intangible Cultural Heritage since 2011.',
      'When the fadista sings, the room goes quiet: talking is a faux pas.',
    ],
    lookFor: 'The pear-shaped Portuguese guitar with its twelve strings.',
    bestTime: 'Thursday to Saturday, from 21:30.',
    durationMin: 90,
    cost: 'paid',
    access: 'step_free',
  },
  'demo-praia-grande': {
    teaser: 'A big surf beach with dinosaur footprints on its cliff.',
    facts: [
      'Dinosaur tracks about 120 million years old climb the rock at the southern end.',
      'It hosts surf and bodyboard competitions.',
      'A huge saltwater pool sits beside the beach.',
    ],
    lookFor: 'The footprint wall at the south end, seen from the stairs.',
    bestTime: 'Late afternoon in summer.',
    durationMin: 120,
    cost: 'free',
    access: 'some_steps',
    tip: 'Swim only when lifeguards are on duty; rip currents are common.',
  },
  'demo-azenhas': {
    teaser: 'A white village spilling down a cliff to a natural sea pool.',
    facts: [
      'Its name comes from the watermills (azenhas) that once stood on the stream.',
      'The rock pool below the village refills with every high tide.',
    ],
    lookFor: 'The classic view of the village from the road above it.',
    bestTime: 'Sunset.',
    durationMin: 45,
    cost: 'free',
    access: 'steep',
  },
  'demo-sintra-fonte-mourisca': {
    teaser: 'A little Neo-Moorish fountain hidden in a bend of the old road.',
    facts: ['It was built in the 1920s in a Moorish Revival style, with horseshoe arches.'],
    lookFor: 'The green and white tiles around the arch.',
    durationMin: 10,
    cost: 'free',
    access: 'step_free',
  },
  'demo-sintra-peninha': {
    teaser: 'A hermit’s chapel on a granite crag with the whole coast below.',
    facts: [
      'At about 490 m, it is one of the highest points of the Sintra hills.',
      'A small chapel has stood on the crag since the 1600s.',
    ],
    lookFor: 'The Cabo da Roca lighthouse, far below to the west.',
    bestTime: 'Clear afternoons.',
    durationMin: 45,
    cost: 'free',
    access: 'trail',
    tip: 'Stay on the path near the edges; it can be very windy.',
  },
  'demo-sintra-musa': {
    teaser: 'Modern and contemporary art in Sintra’s old casino.',
    facts: [
      'The building opened as a casino in the 1920s.',
      'Its exhibitions change through the year, so each visit is different.',
    ],
    bestTime: 'Combine it with the station on the way into town.',
    durationMin: 60,
    access: 'step_free',
  },
  'demo-sintra-anjos-teixeira': {
    teaser: 'A sculptor father and son’s studio beside the stream.',
    facts: ['Artur Anjos Teixeira and his son Pedro, both sculptors, worked here.'],
    lookFor: 'The plaster models beside the finished bronzes.',
    durationMin: 45,
  },
  'demo-sintra-leal-da-camara': {
    teaser: 'The house of a cartoonist who mocked kings and politicians.',
    facts: [
      'Rafael Leal da Câmara drew biting cartoons of the monarchy and spent years in exile in Paris.',
      'He lived in this house in Rinchoa until his death in 1948.',
    ],
    durationMin: 45,
  },
  'demo-sintra-national-palace': {
    teaser: 'A medieval royal palace crowned by two giant white chimneys.',
    facts: [
      'The two cone-shaped chimneys, about 33 m tall, belong to the royal kitchen.',
      'It is the best-preserved medieval royal palace in Portugal, used by kings for centuries.',
      'The Magpie Room ceiling is painted with 136 magpies, each holding the motto “Por bem”.',
    ],
    lookFor: 'The magpies on the ceiling of the Magpie Room.',
    bestTime: 'Mornings, before the day trips arrive.',
    durationMin: 75,
    cost: 'ticket',
    access: 'some_steps',
  },
  'demo-sintra-ferreira-de-castro': {
    teaser: 'The study and library of one of Portugal’s great novelists.',
    facts: [
      'José Maria Ferreira de Castro wrote “A Selva” about his years in the Amazon.',
      'He asked to be buried in Sintra, on the path up to the Castle of the Moors.',
    ],
    durationMin: 30,
  },
  'demo-sintra-valley-of-lakes': {
    teaser: 'A chain of ponds deep in Pena Park, with a castle for ducks.',
    facts: [
      'Ferdinand II laid out Pena Park as a Romantic garden with trees from around the world.',
      'The miniature castle on the water was built as a house for ducks.',
    ],
    lookFor: 'The little duck castle on the lake.',
    durationMin: 45,
    cost: 'ticket',
    access: 'trail',
  },
  'demo-sintra-lagoa-azul': {
    teaser: 'A quiet blue lake in the pine forest on the road to the coast.',
    facts: ['It lies inside the Sintra-Cascais Natural Park.'],
    bestTime: 'Weekday mornings.',
    durationMin: 45,
    cost: 'free',
    access: 'trail',
  },
  'demo-sintra-pedra-amarela': {
    teaser: 'A granite outcrop with a sweeping view over the hills to the sea.',
    facts: [
      'Its name means “Yellow Stone”.',
      'Like the rest of the Sintra hills, it is made of hard igneous rock pushed up from deep below.',
    ],
    bestTime: 'Clear days.',
    durationMin: 60,
    cost: 'free',
    access: 'trail',
  },
  'demo-sintra-station': {
    teaser: 'The end of the line from Lisbon, in a tiled 19th-century station.',
    facts: [
      'The railway reached Sintra in 1887.',
      'Trains from Lisbon’s Rossio station take about 40 minutes.',
    ],
    lookFor: 'The tiled panels in and around the station.',
    durationMin: 10,
    cost: 'free',
    access: 'step_free',
  },
  'demo-sintra-tram': {
    teaser: 'A vintage tram that rattles from the hills down to the beach.',
    facts: [
      'The Sintra tram line opened in 1904.',
      'It mostly runs in the warmer months, on restored old cars.',
    ],
    bestTime: 'Summer weekends: check the timetable first.',
    durationMin: 45,
    cost: 'paid',
  },
  'demo-sintra-praia-macas': {
    teaser: 'A family beach where the old tram line meets the sea.',
    facts: ['Its name means “Apples Beach”.', 'The Sintra tram has its seaside stop here.'],
    lookFor: 'The tidal sea pool at the north end.',
    bestTime: 'Summer afternoons.',
    durationMin: 120,
    cost: 'free',
    access: 'some_steps',
  },
  'demo-sintra-praia-ursa': {
    teaser: 'A wild cove under Cabo da Roca, reached only by a steep path.',
    facts: [
      'It is named after a rock the fishermen thought looked like a she-bear (ursa).',
      'There are no lifeguards, cafés or facilities on the beach.',
    ],
    lookFor: 'The She-Bear rock standing in the sea.',
    bestTime: 'Dry days, with good shoes.',
    durationMin: 120,
    cost: 'free',
    access: 'trail',
    tip: 'The path is steep and loose: skip it in wet weather and don’t swim in rough seas.',
  },
  'demo-sintra-monserrate-ferns': {
    teaser: 'A valley of giant tree ferns from the other side of the world.',
    facts: [
      'Francis Cook’s gardeners planted it in the 1800s with ferns from Australia and New Zealand.',
      'Tree ferns can grow several metres tall.',
    ],
    lookFor: 'The tallest frond in the valley.',
    durationMin: 30,
    cost: 'ticket',
    access: 'trail',
  },
  'demo-sintra-quinta-relogio': {
    teaser: 'A neo-Moorish house where a king spent his honeymoon.',
    facts: [
      'It was built around 1860 in a Moorish Revival style.',
      'King Carlos and Queen Amélia spent their honeymoon here in 1886.',
    ],
    lookFor: 'The horseshoe arches, seen from the road.',
    durationMin: 10,
    cost: 'free',
    access: 'step_free',
    tip: 'Private property: enjoy it from the road.',
  },
  'demo-sintra-penha-verde': {
    teaser: 'The wooded estate of a 16th-century viceroy of India.',
    facts: [
      'João de Castro, viceroy of Portuguese India, made this estate his retreat.',
      'Legend says he planted trees here that he brought back from Asia.',
    ],
    durationMin: 15,
    tip: 'Private estate: view it from the road unless it is open for an event.',
  },
  'demo-sintra-chalet-biester': {
    teaser: 'A Gothic chalet with slate turrets that starred in a Hollywood film.',
    facts: [
      'It was built in the 1880s for the Biester family.',
      'Luigi Manini, who later designed Quinta da Regaleira, painted its interiors.',
      'Roman Polanski filmed scenes of “The Ninth Gate” (1999) here.',
    ],
    lookFor: 'The slate turrets through the trees.',
    durationMin: 45,
    tip: 'Open on selected days only: check before you go.',
  },
  'demo-sintra-santa-maria': {
    teaser: 'One of Sintra’s oldest churches, founded after the Christian conquest.',
    facts: [
      'It was founded after Afonso Henriques took Sintra in 1147.',
      'Its portal is carved in the Manueline style of the 1500s.',
    ],
    lookFor: 'The old tomb slabs set into the floor.',
    durationMin: 20,
    cost: 'free',
    access: 'some_steps',
  },
  'demo-sintra-natural-history': {
    teaser: 'Fossils and minerals in a 19th-century house on the old square.',
    facts: ['Some of its fossils are tens of millions of years old.'],
    lookFor: 'The dinosaur egg.',
    durationMin: 45,
    cost: 'ticket',
  },
  'demo-sintra-fonte-pipa': {
    teaser: 'A tiled fountain where villagers once filled their jugs.',
    facts: ['Before piped water, fountains like this were where the town got its water.'],
    lookFor: 'The date painted in its tiles.',
    durationMin: 10,
    cost: 'free',
    access: 'step_free',
  },
  'demo-sintra-volta-duche': {
    teaser: 'The Romantic promenade into town, lined with tiled benches.',
    facts: ['In the 1800s visitors strolled this road between the new town and the palace.'],
    lookFor: 'A bench with a view of the Moorish walls.',
    durationMin: 20,
    cost: 'free',
    access: 'step_free',
  },
  'demo-sintra-olga-cadaval': {
    teaser: 'Sintra’s main stage for concerts, theatre and dance.',
    facts: [
      'It is named after Olga Cadaval, a duchess and music patron who supported the Sintra Music Festival.',
    ],
    bestTime: 'An evening show: check the programme.',
    durationMin: 120,
    cost: 'ticket',
    access: 'step_free',
  },
  'demo-sintra-casa-teatro': {
    teaser: 'A small theatre company’s home in the Estefânia quarter.',
    facts: ['Small venues like this stage local productions and readings through the year.'],
    bestTime: 'An evening performance.',
    durationMin: 90,
    cost: 'ticket',
  },
  'demo-sintra-feira-merces': {
    teaser: 'Sintra’s old country fair, around a hilltop chapel.',
    facts: ['It is held each autumn around the chapel of Nossa Senhora das Mercês.'],
    lookFor: 'The chapel on the fairground.',
    bestTime: 'During the autumn fair.',
    durationMin: 90,
    cost: 'free',
  },
  'demo-sintra-colares-adega': {
    teaser: 'The cellars of a rare wine grown in sand by the sea.',
    facts: [
      'Colares vines grow in deep sand, which saved them from the phylloxera plague of the 1800s.',
      'Ramisco is the local red grape.',
      'The regional co-operative cellar was founded in 1931.',
    ],
    lookFor: 'The old wooden vats in the cellar.',
    bestTime: 'Harvest time, in early autumn.',
    durationMin: 60,
    cost: 'paid',
  },
  'demo-sintra-tram-banzao': {
    teaser: 'A stop among the vineyards on Sintra’s 1904 tram line.',
    facts: ['The tram has rattled through these Colares vineyards since the early 1900s.'],
    lookFor: 'The tram car coming round the bend.',
    bestTime: 'Summer weekends, when the tram runs.',
    durationMin: 20,
    cost: 'free',
    access: 'step_free',
  },
  'demo-sintra-tram-galamares': {
    teaser: 'A halt on the old tram line from the hills to the sea.',
    facts: ['The line links Sintra town with the beach at Praia das Maçãs.'],
    bestTime: 'Summer weekends, when the tram runs.',
    durationMin: 20,
    cost: 'free',
    access: 'step_free',
  },
  'demo-sintra-portela-station': {
    teaser: 'The station of Sintra’s newer quarter, one stop before the end of the line.',
    facts: ['Trains from Lisbon stop here just before the Sintra terminus.'],
    lookFor: 'The tile panel in the hall.',
    durationMin: 10,
    cost: 'free',
    access: 'step_free',
  },
  'demo-sintra-piriquita': {
    teaser: 'Sintra’s famous bakery, warm travesseiros since 1862.',
    facts: [
      'It has been baking in Sintra since 1862.',
      'A travesseiro (“pillow”) is puff pastry filled with almond and egg cream.',
      'Queijadas, little cheese tarts, have been a Sintra speciality for centuries.',
    ],
    lookFor: 'Trays of travesseiros coming out of the kitchen.',
    bestTime: 'Weekday mornings, before the queue.',
    durationMin: 20,
    cost: 'paid',
    access: 'step_free',
  },
  'demo-sintra-sao-pedro-fair': {
    teaser: 'A Sunday market of antiques, plants, cheese and bread.',
    facts: ['A market has been held here on the 2nd and 4th Sunday since the Middle Ages.'],
    lookFor: 'Something old and something edible.',
    bestTime: 'The 2nd and 4th Sunday mornings of the month.',
    durationMin: 60,
    cost: 'free',
    access: 'step_free',
  },
  'demo-sintra-azoia': {
    teaser: 'The last village before Cabo da Roca, at the edge of Europe.',
    facts: ['It is the closest village to mainland Europe’s westernmost point.'],
    lookFor: 'The café where the lighthouse keepers used to stop.',
    durationMin: 30,
    cost: 'free',
    access: 'step_free',
  },
  'demo-sintra-janas-chapel': {
    teaser: 'A round chapel where farmers bring their animals to be blessed.',
    facts: [
      'Round chapels are rare in Portugal.',
      'At the August festival of São Mamede, animals are led around the chapel for a blessing.',
    ],
    lookFor: 'The circular wall, best seen by walking once around it.',
    bestTime: 'Mid-August, during the festival.',
    durationMin: 20,
    cost: 'free',
    access: 'step_free',
  },
  'demo-sintra-dino-footprints': {
    teaser: 'Dinosaur tracks climbing a cliff that was once a muddy shore.',
    facts: [
      'The footprints are about 120 million years old.',
      'The rock layers were later tilted almost upright, so the tracks now run up the cliff.',
    ],
    lookFor: 'The line of round prints on the cliff face.',
    bestTime: 'Late afternoon light from the side shows the prints best.',
    durationMin: 20,
    cost: 'free',
    access: 'some_steps',
    tip: 'Look from the beach stairs; don’t climb the cliff.',
  },
  'demo-sintra-cafe-saudade': {
    teaser: 'A café and bakery near the station, for a queijada and a galão.',
    facts: [
      '“Saudade” is the Portuguese word for a longing that’s famously hard to translate.',
      'A galão is milky coffee served in a tall glass.',
    ],
    bestTime: 'Breakfast or a late-afternoon snack.',
    durationMin: 30,
    cost: 'paid',
    access: 'step_free',
  },
  'demo-sintra-santa-eufemia': {
    teaser: 'A hilltop hermitage with a holy spring and a yearly pilgrimage.',
    facts: [
      'Pilgrims have climbed here for centuries for the festival of Santa Eufémia.',
      'A spring below the chapel is said to have healing water.',
    ],
    lookFor: 'The spring below the chapel.',
    durationMin: 45,
    cost: 'free',
    access: 'trail',
  },
  'demo-sintra-almocageme': {
    teaser: 'A village square where locals meet for coffee before the beach.',
    facts: ['It is the village above Adraga beach, in the Colares wine area.'],
    lookFor: 'The old fountain on the square.',
    durationMin: 20,
    cost: 'free',
    access: 'step_free',
  },
  'demo-sintra-vila-sassetti': {
    teaser: 'A secret garden path from a hidden villa up to the Moorish castle.',
    facts: [
      'The villa was designed by Luigi Manini, the architect of Quinta da Regaleira.',
      'The path climbs through granite boulders and woods to the castle walls.',
    ],
    lookFor: 'The villa’s tower among the trees.',
    durationMin: 60,
    cost: 'free',
    access: 'trail',
  },
};
