-- Development seed: the Sintra region, a handful of curated places, and daily
-- challenges. Real place data comes from scripts/importer (OSM + Wikidata).
-- Coordinates are approximate.

insert into public.regions (slug, name, bbox, is_active)
values ('sintra', 'Sintra', extensions.st_makeenvelope(-9.52, 38.73, -9.30, 38.85, 4326), true)
on conflict (slug) do nothing;

with r as (select id from public.regions where slug = 'sintra')
insert into public.places (name, description, location, category, base_points, source, source_id, status, region_id)
select v.name, v.description,
       extensions.st_setsrid(extensions.st_makepoint(v.lng, v.lat), 4326)::extensions.geography,
       v.category::public.place_category, v.base_points, 'seed', v.source_id, 'active', r.id
from r, (values
  ('pena', 'Pena Palace', 'Colourful Romanticist palace on a hilltop above Sintra.', 'heritage', 120, 38.7876, -9.3906),
  ('regaleira', 'Quinta da Regaleira', 'Estate with gardens, grottoes and the famous initiation well.', 'heritage', 120, 38.7967, -9.3958),
  ('mouros', 'Castle of the Moors', 'Medieval hilltop castle with walls that climb the ridge.', 'heritage', 120, 38.7917, -9.3880),
  ('monserrate', 'Monserrate Palace', 'Exotic palace surrounded by botanical gardens.', 'culture', 100, 38.7919, -9.4191),
  ('capuchos', 'Convent of the Capuchos', 'Tiny cork-lined convent hidden in the forest.', 'heritage', 120, 38.7777, -9.4469),
  ('cabo-da-roca', 'Cabo da Roca Viewpoint', 'The westernmost point of mainland Europe.', 'coast', 80, 38.7804, -9.4989),
  ('adraga', 'Adraga Beach', 'Wild cove with rock arches and dramatic sunsets.', 'coast', 80, 38.8236, -9.4731),
  ('praia-grande', 'Praia Grande', 'Surf beach where dinosaur footprints climb the cliff at the southern end.', 'coast', 80, 38.8160, -9.4785),
  ('azenhas', 'Azenhas do Mar', 'White village tumbling down a cliff to a tide pool.', 'coast', 80, 38.8406, -9.4618),
  ('music-corner', 'Sintra Live Music Corner', 'Small local venue with traditional fado nights.', 'music_events', 100, 38.7985, -9.3875),
  ('cruz-alta', 'Cruz Alta Viewpoint', 'The highest point of the Sintra hills.', 'nature', 80, 38.7861, -9.3897)
) as v(source_id, name, description, category, base_points, lat, lng)
on conflict (source, source_id) do nothing;

-- Venues with set times (Thu–Sat, 21:30 to 00:30).
update public.places
set opening_hours = '[{"days": [4, 5, 6], "open": "21:30", "close": "00:30"}]'
where source = 'seed' and source_id = 'music-corner';

-- Europe launch cities (mirrors EUROPE_PLACES in packages/shared). Hidden gems stay off the map
-- until a player is within 200 m.
insert into public.places (name, description, location, category, base_points, source, source_id, status, region_id, is_hidden, opening_hours)
select v.name, v.description,
       extensions.st_setsrid(extensions.st_makepoint(v.lng, v.lat), 4326)::extensions.geography,
       v.category::public.place_category, v.base_points, 'seed', v.source_id, 'active', r.id, v.hidden, v.hours
from (values
  ('sintra', 'sintra-fonte-mourisca', 'Moorish Fountain', 'Neo-Moorish fountain tiled in green and white, tucked into a bend of the old road.', 'heritage', 120, 38.7983, -9.3858, true, null),
  ('sintra', 'sintra-peninha', 'Peninha Sanctuary', 'Hermit chapel on a granite crag with the whole coast below it.', 'nature', 80, 38.7686, -9.4589, true, null),
  ('sintra', 'sintra-musa', 'MU.SA – Sintra Arts Museum', 'Modern and contemporary art in the old casino building, a short walk from the palace.', 'art', 100, 38.7988, -9.3826, false, null),
  ('sintra', 'sintra-anjos-teixeira', 'Anjos Teixeira Sculpture Museum', 'Father-and-son sculptor’s studio, tucked beside the stream below the town.', 'art', 100, 38.795, -9.392, false, null),
  ('sintra', 'sintra-leal-da-camara', 'Leal da Câmara House-Museum', 'Caricatures and posters by a cartoonist who mocked kings and politicians.', 'art', 100, 38.7826, -9.334, false, null),
  ('sintra', 'sintra-national-palace', 'Sintra National Palace', 'Medieval royal palace crowned by two giant white chimneys.', 'culture', 100, 38.7976, -9.3906, false, null),
  ('sintra', 'sintra-ferreira-de-castro', 'Ferreira de Castro House-Museum', 'The study and library of one of Portugal’s great novelists.', 'culture', 100, 38.7962, -9.3913, false, null),
  ('sintra', 'sintra-valley-of-lakes', 'Valley of the Lakes, Pena Park', 'Chain of ponds with a little duck castle, deep in the palace gardens.', 'nature', 80, 38.786, -9.392, false, null),
  ('sintra', 'sintra-lagoa-azul', 'Lagoa Azul', 'Quiet blue lake in the pine forest on the road to the coast.', 'nature', 80, 38.771, -9.418, false, null),
  ('sintra', 'sintra-pedra-amarela', 'Pedra Amarela', 'Granite outcrop with a sweeping view over the hills to the sea.', 'nature', 80, 38.781, -9.431, false, null),
  ('sintra', 'sintra-station', 'Sintra Station', 'Tiled 19th-century terminus where the train from Lisbon ends.', 'travel', 80, 38.7988, -9.378, false, null),
  ('sintra', 'sintra-tram', 'Sintra Tram at Praia das Maçãs', 'Vintage tram that rattles from the hills down to the beach.', 'travel', 80, 38.8226, -9.4664, false, null),
  ('lisbon', 'lisbon-belem-tower', 'Belém Tower', 'Sixteenth-century fortress that guarded the mouth of the Tagus.', 'heritage', 120, 38.6916, -9.216, false, null),
  ('lisbon', 'lisbon-jeronimos', 'Jerónimos Monastery', 'Manueline monastery carved with ropes, shells and sea creatures.', 'heritage', 120, 38.6979, -9.2068, false, null),
  ('lisbon', 'lisbon-sao-jorge', 'São Jorge Castle', 'Hilltop castle whose ramparts look over the red roofs of Alfama.', 'heritage', 120, 38.7139, -9.1335, false, null),
  ('lisbon', 'lisbon-senhora-do-monte', 'Senhora do Monte Viewpoint', 'The highest viewpoint in Lisbon, under umbrella pines.', 'nature', 80, 38.7193, -9.1326, false, null),
  ('lisbon', 'lisbon-lx-factory', 'LX Factory', 'Old textile mill turned into studios, bookshops and street art.', 'culture', 100, 38.7037, -9.1785, false, null),
  ('lisbon', 'lisbon-fado-alfama', 'Alfama Fado House', 'Candle-lit room where fado is sung most nights.', 'music_events', 100, 38.7106, -9.1305, false, '[{"days": [0, 1, 2, 3, 4, 5, 6], "open": "20:00", "close": "01:00"}]'::jsonb),
  ('lisbon', 'lisbon-sao-cristovao-steps', 'São Cristóvão Steps', 'Stairway painted with a mural of the fado singers who lived here.', 'other', 60, 38.7128, -9.1351, true, null),
  ('lisbon', 'lisbon-maat', 'MAAT', 'Wave-shaped museum of art, architecture and technology you can walk on top of.', 'art', 100, 38.6956, -9.195, false, null),
  ('lisbon', 'lisbon-berardo', 'Berardo Collection at CCB', 'Modern art from Picasso to Warhol in the Belém Cultural Centre.', 'art', 100, 38.6957, -9.2083, false, null),
  ('lisbon', 'lisbon-crono-murals', 'Crono Project Murals', 'Giant murals painted across a row of abandoned buildings.', 'art', 100, 38.7315, -9.1468, false, null),
  ('lisbon', 'lisbon-gulbenkian', 'Calouste Gulbenkian Museum', 'From Egyptian treasures to Lalique jewels, in a modernist garden.', 'culture', 100, 38.7372, -9.1545, false, null),
  ('lisbon', 'lisbon-azulejo', 'National Tile Museum', 'Five centuries of Portuguese tiles in a gilded convent.', 'culture', 100, 38.7247, -9.1137, false, null),
  ('lisbon', 'lisbon-monsanto', 'Monsanto Panoramic', 'Abandoned hilltop restaurant in the forest with a 360° view.', 'nature', 80, 38.73, -9.1835, false, null),
  ('lisbon', 'lisbon-estufa-fria', 'Estufa Fria', 'Shaded greenhouse jungle of ferns, ponds and palms.', 'nature', 80, 38.7287, -9.153, false, null),
  ('lisbon', 'lisbon-estrela', 'Estrela Garden', 'Romantic park with a bandstand, ducks and a café by the lake.', 'nature', 80, 38.714, -9.1595, false, null),
  ('lisbon', 'lisbon-tram-28', 'Tram 28 at Martim Moniz', 'Start of the famous yellow tram that climbs through Graça and Alfama.', 'travel', 80, 38.716, -9.1365, false, null),
  ('lisbon', 'lisbon-santa-justa', 'Santa Justa Lift', 'Neo-Gothic iron lift linking the Baixa to the Carmo ruins.', 'travel', 80, 38.7121, -9.1393, false, null),
  ('porto', 'porto-ribeira', 'Ribeira Waterfront', 'Stacked, colourful houses along the Douro quay.', 'heritage', 120, 41.1407, -8.6131, false, null),
  ('porto', 'porto-lello', 'Livraria Lello', 'Neo-Gothic bookshop with a crimson staircase.', 'culture', 100, 41.1469, -8.6149, false, null),
  ('porto', 'porto-clerigos', 'Clérigos Tower', 'Baroque bell tower with 240 steps to the top.', 'heritage', 120, 41.1457, -8.6146, false, null),
  ('porto', 'porto-dom-luis', 'Dom Luís I Bridge', 'Double-decker iron bridge you can walk across at rooftop height.', 'heritage', 120, 41.1399, -8.6094, false, null),
  ('porto', 'porto-palacio-cristal', 'Crystal Palace Gardens', 'Romantic gardens with peacocks and river views.', 'nature', 80, 41.1479, -8.6255, false, null),
  ('porto', 'porto-foz', 'Foz do Douro Beach', 'Where the Douro meets the Atlantic, with a lighthouse pier.', 'coast', 80, 41.1497, -8.6764, false, null),
  ('porto', 'porto-virtudes', 'Virtudes Terraces', 'Sloping garden where locals watch the sun set over the river.', 'nature', 80, 41.1438, -8.6188, true, null),
  ('porto', 'porto-serralves', 'Serralves Museum', 'White Siza Vieira museum of contemporary art.', 'art', 100, 41.1597, -8.6598, false, null),
  ('porto', 'porto-soares-dos-reis', 'Soares dos Reis Museum', 'Portugal’s oldest public art museum, in a neoclassical palace.', 'art', 100, 41.1475, -8.6215, false, null),
  ('porto', 'porto-half-rabbit', 'Bordalo II’s Half Rabbit', 'Huge rabbit sculpted from street rubbish on a Gaia wall.', 'art', 100, 41.1372, -8.6095, false, null),
  ('porto', 'porto-bolsa', 'Palácio da Bolsa', 'Stock exchange palace with a dazzling Arab Room.', 'culture', 100, 41.1414, -8.6156, false, null),
  ('porto', 'porto-wow', 'World of Wine', 'Museums about wine, cork and chocolate in old port cellars.', 'culture', 100, 41.1355, -8.6143, false, null),
  ('porto', 'porto-serralves-park', 'Serralves Park', 'Gardens, woods and a giant red trowel sculpture.', 'nature', 80, 41.1585, -8.661, false, null),
  ('porto', 'porto-city-park', 'Porto City Park', 'The biggest urban park in Portugal, running down to the sea.', 'nature', 80, 41.1705, -8.678, false, null),
  ('porto', 'porto-passeio-alegre', 'Passeio Alegre Garden', 'Palm-lined promenade where the river meets the ocean.', 'nature', 80, 41.148, -8.672, false, null),
  ('porto', 'porto-sao-bento', 'São Bento Station', 'Station hall covered in 20,000 blue-and-white tiles.', 'travel', 80, 41.1456, -8.6106, false, null),
  ('porto', 'porto-guindais', 'Guindais Funicular', 'Funicular that climbs the old city walls from the river.', 'travel', 80, 41.1407, -8.6084, false, null),
  ('madrid', 'madrid-royal-palace', 'Royal Palace of Madrid', 'One of the largest palaces in Europe, with 3,400 rooms.', 'heritage', 120, 40.418, -3.7143, false, null),
  ('madrid', 'madrid-prado', 'Prado Museum', 'Velázquez, Goya and Bosch under one roof.', 'culture', 100, 40.4138, -3.6921, false, null),
  ('madrid', 'madrid-retiro', 'Retiro Park', 'Rowing lake, rose garden and a glass palace.', 'nature', 80, 40.4153, -3.6845, false, null),
  ('madrid', 'madrid-plaza-mayor', 'Plaza Mayor', 'Arcaded seventeenth-century square at the heart of old Madrid.', 'heritage', 120, 40.4155, -3.7074, false, null),
  ('madrid', 'madrid-debod', 'Temple of Debod', 'Ancient Egyptian temple rebuilt on a hill above the city.', 'heritage', 120, 40.424, -3.7178, false, null),
  ('madrid', 'madrid-san-miguel', 'San Miguel Market', 'Iron-and-glass market hall full of tapas stalls.', 'other', 60, 40.4154, -3.709, false, '[{"days": [0, 1, 2, 3, 4, 5, 6], "open": "10:00", "close": "00:00"}]'::jsonb),
  ('madrid', 'madrid-anglona', 'Prince of Anglona Garden', 'A tiny walled garden from the 1700s, easy to walk past.', 'nature', 80, 40.4127, -3.7118, true, null),
  ('madrid', 'madrid-reina-sofia', 'Reina Sofía Museum', 'Home of Picasso’s Guernica.', 'art', 100, 40.408, -3.6946, false, null),
  ('madrid', 'madrid-thyssen', 'Thyssen-Bornemisza Museum', 'Seven centuries of painting in one private collection.', 'art', 100, 40.416, -3.6949, false, null),
  ('madrid', 'madrid-caixaforum', 'CaixaForum Madrid', 'Art centre beside a living wall of 15,000 plants.', 'art', 100, 40.4113, -3.6934, false, null),
  ('madrid', 'madrid-archaeological', 'National Archaeological Museum', 'Iberian treasures, including the mysterious Lady of Elche.', 'culture', 100, 40.4235, -3.6893, false, null),
  ('madrid', 'madrid-teatro-real', 'Teatro Real', 'Madrid’s grand opera house, facing the Royal Palace.', 'culture', 100, 40.4184, -3.711, false, null),
  ('madrid', 'madrid-botanic', 'Royal Botanic Garden', 'Eighteenth-century terraces of plants and glasshouses.', 'nature', 80, 40.4114, -3.691, false, null),
  ('madrid', 'madrid-casa-de-campo', 'Casa de Campo Lake', 'Rowing lake in Madrid’s huge former royal hunting ground.', 'nature', 80, 40.4196, -3.736, false, null),
  ('madrid', 'madrid-rosaleda', 'Rose Garden of Parque del Oeste', 'Hundreds of rose varieties, at their best in May.', 'nature', 80, 40.4291, -3.7225, false, null),
  ('madrid', 'madrid-atocha', 'Atocha Station Garden', 'Old train shed turned into a tropical garden with turtles.', 'travel', 80, 40.407, -3.6905, false, null),
  ('madrid', 'madrid-teleferico', 'Madrid Cable Car', 'Cable car gliding over the trees of Casa de Campo.', 'travel', 80, 40.4268, -3.7203, false, null),
  ('barcelona', 'barcelona-sagrada-familia', 'Sagrada Família', 'Gaudí’s basilica, still being built after more than a century.', 'heritage', 120, 41.4036, 2.1744, false, null),
  ('barcelona', 'barcelona-park-guell', 'Park Güell', 'Mosaic terraces and gingerbread houses above the city.', 'nature', 80, 41.4145, 2.1527, false, null),
  ('barcelona', 'barcelona-casa-batllo', 'Casa Batlló', 'A house with a dragon’s back for a roof.', 'culture', 100, 41.3917, 2.1649, false, null),
  ('barcelona', 'barcelona-barceloneta', 'Barceloneta Beach', 'The city’s beach, a short walk from the old town.', 'coast', 80, 41.3784, 2.1925, false, null),
  ('barcelona', 'barcelona-cathedral', 'Barcelona Cathedral', 'Gothic cathedral whose cloister is home to thirteen geese.', 'heritage', 120, 41.3839, 2.1762, false, null),
  ('barcelona', 'barcelona-palau-musica', 'Palau de la Música Catalana', 'Modernista concert hall lit by a stained-glass skylight.', 'music_events', 100, 41.3875, 2.1753, false, '[{"days": [0, 1, 2, 3, 4, 5, 6], "open": "10:00", "close": "23:00"}]'::jsonb),
  ('barcelona', 'barcelona-bunkers', 'Carmel Bunkers', 'Old anti-aircraft battery with a 360° view of Barcelona.', 'nature', 80, 41.4192, 2.1617, true, null),
  ('barcelona', 'barcelona-picasso', 'Picasso Museum', 'Picasso’s early years, in five medieval palaces.', 'art', 100, 41.3852, 2.1809, false, null),
  ('barcelona', 'barcelona-miro', 'Fundació Joan Miró', 'Bright Miró paintings and sculptures on Montjuïc hill.', 'art', 100, 41.3685, 2.16, false, null),
  ('barcelona', 'barcelona-macba', 'MACBA', 'White contemporary art museum, with skaters on the square outside.', 'art', 100, 41.3833, 2.1668, false, null),
  ('barcelona', 'barcelona-pedrera', 'Casa Milà (La Pedrera)', 'Gaudí’s wavy apartment block with warrior-like chimneys.', 'culture', 100, 41.3954, 2.1619, false, null),
  ('barcelona', 'barcelona-liceu', 'Gran Teatre del Liceu', 'Red-and-gold opera house on La Rambla.', 'culture', 100, 41.3803, 2.1736, false, null),
  ('barcelona', 'barcelona-ciutadella', 'Parc de la Ciutadella', 'Park with a golden cascade fountain and a boating lake.', 'nature', 80, 41.3881, 2.1873, false, null),
  ('barcelona', 'barcelona-tibidabo', 'Tibidabo Summit', 'Mountain top with a vintage amusement park and a view of the whole city.', 'nature', 80, 41.422, 2.119, false, null),
  ('barcelona', 'barcelona-horta-labyrinth', 'Horta Labyrinth Park', 'Neoclassical garden with a cypress hedge maze.', 'nature', 80, 41.4398, 2.1464, false, null),
  ('barcelona', 'barcelona-montjuic-cable-car', 'Montjuïc Cable Car', 'Cable car up to the castle on Montjuïc.', 'travel', 80, 41.3717, 2.1659, false, null),
  ('barcelona', 'barcelona-port-cable-car', 'Port Vell Aerial Tramway', '1930s cable car swinging across the harbour.', 'travel', 80, 41.372, 2.189, false, null),
  ('paris', 'paris-eiffel', 'Eiffel Tower', 'Iron lattice tower that sparkles on the hour after dark.', 'heritage', 120, 48.8584, 2.2945, false, null),
  ('paris', 'paris-louvre', 'Louvre Museum', 'The world’s most visited museum, behind a glass pyramid.', 'culture', 100, 48.8606, 2.3376, false, null),
  ('paris', 'paris-notre-dame', 'Notre-Dame de Paris', 'Gothic cathedral on the Île de la Cité, restored after the 2019 fire.', 'heritage', 120, 48.853, 2.3499, false, null),
  ('paris', 'paris-sacre-coeur', 'Sacré-Cœur', 'White basilica on top of Montmartre.', 'heritage', 120, 48.8867, 2.3431, false, null),
  ('paris', 'paris-luxembourg', 'Luxembourg Gardens', 'Palace gardens with toy sailboats on the pond.', 'nature', 80, 48.8462, 2.3372, false, null),
  ('paris', 'paris-orsay', 'Musée d’Orsay', 'Impressionist paintings inside a former railway station.', 'culture', 100, 48.86, 2.3266, false, null),
  ('paris', 'paris-cremieux', 'Rue Crémieux', 'A short cobbled street of pastel-painted houses.', 'other', 60, 48.847, 2.3709, true, null),
  ('paris', 'paris-orangerie', 'Musée de l’Orangerie', 'Monet’s Water Lilies wrap around two oval rooms.', 'art', 100, 48.8638, 2.3227, false, null),
  ('paris', 'paris-pompidou', 'Centre Pompidou', 'Inside-out building full of modern art.', 'art', 100, 48.8606, 2.3522, false, null),
  ('paris', 'paris-rodin', 'Musée Rodin', 'The Thinker sits in a rose garden.', 'art', 100, 48.8553, 2.3159, false, null),
  ('paris', 'paris-garnier', 'Palais Garnier', 'Gilded opera house with a Chagall ceiling.', 'culture', 100, 48.872, 2.3316, false, null),
  ('paris', 'paris-pantheon', 'Panthéon', 'Domed resting place of France’s great names.', 'culture', 100, 48.8462, 2.346, false, null),
  ('paris', 'paris-buttes-chaumont', 'Parc des Buttes-Chaumont', 'Cliffs, a waterfall and a temple on an island.', 'nature', 80, 48.8809, 2.3828, false, null),
  ('paris', 'paris-jardin-des-plantes', 'Jardin des Plantes', 'Botanic garden with glasshouses and a small zoo.', 'nature', 80, 48.844, 2.359, false, null),
  ('paris', 'paris-coulee-verte', 'Coulée Verte', 'Garden walk along an old railway viaduct.', 'nature', 80, 48.8486, 2.3747, false, null),
  ('paris', 'paris-gare-de-lyon', 'Gare de Lyon Clock Tower', 'Grand station with a clock tower and the ornate Le Train Bleu.', 'travel', 80, 48.8443, 2.3735, false, null),
  ('paris', 'paris-montmartre-funicular', 'Montmartre Funicular', 'Little funicular up to Sacré-Cœur.', 'travel', 80, 48.8851, 2.3434, false, null),
  ('rome', 'rome-colosseum', 'Colosseum', 'Amphitheatre that held 50,000 spectators.', 'heritage', 120, 41.8902, 12.4922, false, null),
  ('rome', 'rome-pantheon', 'Pantheon', 'Two-thousand-year-old temple with an open eye in its dome.', 'heritage', 120, 41.8986, 12.4769, false, null),
  ('rome', 'rome-trevi', 'Trevi Fountain', 'Throw a coin over your shoulder to return to Rome.', 'heritage', 120, 41.9009, 12.4833, false, null),
  ('rome', 'rome-forum', 'Roman Forum', 'The ruins of ancient Rome’s public square.', 'heritage', 120, 41.8925, 12.4853, false, null),
  ('rome', 'rome-borghese', 'Villa Borghese Gardens', 'Rome’s central park, with a lake temple and a view from the Pincio.', 'nature', 80, 41.9142, 12.4923, false, null),
  ('rome', 'rome-vatican-museums', 'Vatican Museums', 'Miles of galleries ending at the Sistine Chapel.', 'culture', 100, 41.9065, 12.4536, false, null),
  ('rome', 'rome-aventine-keyhole', 'Aventine Keyhole', 'Peek through a garden door’s keyhole to see St Peter’s dome framed perfectly.', 'other', 60, 41.8833, 12.4797, true, null),
  ('rome', 'rome-doria-pamphilj', 'Galleria Doria Pamphilj', 'A family palace still full of its Caravaggios and Velázquez.', 'art', 100, 41.8979, 12.4813, false, null),
  ('rome', 'rome-capitoline', 'Capitoline Museums', 'The world’s oldest public museum, with the bronze she-wolf.', 'art', 100, 41.8933, 12.4828, false, null),
  ('rome', 'rome-ostiense-murals', 'Ostiense Street Art', 'Building-sized murals in Rome’s old industrial quarter.', 'art', 100, 41.8695, 12.4795, false, null),
  ('rome', 'rome-castel-sant-angelo', 'Castel Sant’Angelo', 'Emperor’s tomb turned papal fortress.', 'culture', 100, 41.9031, 12.4663, false, null),
  ('rome', 'rome-spanish-steps', 'Spanish Steps', 'Baroque stairway climbing to Trinità dei Monti.', 'culture', 100, 41.906, 12.4826, false, null),
  ('rome', 'rome-orange-garden', 'Orange Garden', 'Bitter-orange trees and a terrace over the rooftops.', 'nature', 80, 41.8848, 12.479, false, null),
  ('rome', 'rome-doria-pamphili-park', 'Villa Doria Pamphili', 'Rome’s biggest park, with umbrella pines and fountains.', 'nature', 80, 41.885, 12.452, false, null),
  ('rome', 'rome-janiculum', 'Janiculum Terrace', 'Hilltop view where a cannon fires at noon.', 'nature', 80, 41.892, 12.461, false, null),
  ('rome', 'rome-termini', 'Roma Termini', 'Modernist station hall with a flowing concrete roof.', 'travel', 80, 41.901, 12.5016, false, null),
  ('rome', 'rome-piramide', 'Pyramid and Porta San Paolo', 'An ancient pyramid beside the station for the train to Ostia.', 'travel', 80, 41.8763, 12.4808, false, null),
  ('florence', 'florence-duomo', 'Florence Cathedral', 'Brunelleschi’s dome still dominates the skyline.', 'heritage', 120, 43.7731, 11.256, false, null),
  ('florence', 'florence-uffizi', 'Uffizi Gallery', 'Botticelli’s Venus and the Renaissance masters.', 'culture', 100, 43.7678, 11.2553, false, null),
  ('florence', 'florence-ponte-vecchio', 'Ponte Vecchio', 'Medieval bridge lined with goldsmiths’ shops.', 'heritage', 120, 43.768, 11.2531, false, null),
  ('florence', 'florence-michelangelo', 'Piazzale Michelangelo', 'The classic sunset view over Florence.', 'nature', 80, 43.7629, 11.265, false, null),
  ('florence', 'florence-boboli', 'Boboli Gardens', 'Terraced Medici gardens full of statues and grottoes.', 'nature', 80, 43.7625, 11.2484, false, null),
  ('florence', 'florence-rose-garden', 'Rose Garden', 'Quiet terraced rose garden just below the famous viewpoint.', 'nature', 80, 43.7638, 11.2626, true, null),
  ('florence', 'florence-accademia', 'Galleria dell’Accademia', 'Michelangelo’s David.', 'art', 100, 43.7768, 11.2586, false, null),
  ('florence', 'florence-bargello', 'Bargello Museum', 'Renaissance sculpture in a medieval prison.', 'art', 100, 43.7704, 11.2581, false, null),
  ('florence', 'florence-palatine', 'Palatine Gallery, Palazzo Pitti', 'Raphael and Titian in the Medici family palace.', 'art', 100, 43.7651, 11.25, false, null),
  ('florence', 'florence-palazzo-vecchio', 'Palazzo Vecchio', 'Fortress-like town hall with secret passages.', 'culture', 100, 43.7693, 11.2558, false, null),
  ('florence', 'florence-santa-croce', 'Basilica of Santa Croce', 'Burial place of Michelangelo and Galileo.', 'culture', 100, 43.7686, 11.2622, false, null),
  ('florence', 'florence-bardini', 'Bardini Garden', 'Wisteria tunnel with a view of the Duomo.', 'nature', 80, 43.765, 11.258, false, null),
  ('florence', 'florence-cascine', 'Cascine Park', 'Long riverside park, once the Medici farm.', 'nature', 80, 43.782, 11.22, false, null),
  ('florence', 'florence-fiesole', 'Fiesole Viewpoint', 'Hill town with a view down to Florence.', 'nature', 80, 43.8066, 11.2934, false, null),
  ('florence', 'florence-santa-maria-novella', 'Santa Maria Novella Station', '1930s modernist station, a design icon.', 'travel', 80, 43.7764, 11.248, false, null),
  ('florence', 'florence-renaioli', 'Renaioli Boats on the Arno', 'Traditional flat boats punted along the river at sunset.', 'travel', 80, 43.768, 11.2575, false, null),
  ('amsterdam', 'amsterdam-rijksmuseum', 'Rijksmuseum', 'Rembrandt’s Night Watch and the Dutch Golden Age.', 'culture', 100, 52.36, 4.8852, false, null),
  ('amsterdam', 'amsterdam-anne-frank', 'Anne Frank House', 'The canal house where Anne Frank wrote her diary.', 'heritage', 120, 52.3752, 4.884, false, null),
  ('amsterdam', 'amsterdam-vondelpark', 'Vondelpark', 'The city’s favourite park for cycling and picnics.', 'nature', 80, 52.358, 4.8686, false, null),
  ('amsterdam', 'amsterdam-van-gogh', 'Van Gogh Museum', 'The largest collection of Van Gogh’s work.', 'culture', 100, 52.3584, 4.8811, false, null),
  ('amsterdam', 'amsterdam-dam', 'Royal Palace on Dam Square', 'Seventeenth-century town hall turned royal palace.', 'heritage', 120, 52.3731, 4.8913, false, null),
  ('amsterdam', 'amsterdam-concertgebouw', 'Concertgebouw', 'Concert hall famous for its near-perfect acoustics.', 'music_events', 100, 52.3563, 4.8789, false, '[{"days": [0, 1, 2, 3, 4, 5, 6], "open": "10:00", "close": "23:00"}]'::jsonb),
  ('amsterdam', 'amsterdam-begijnhof', 'Begijnhof', 'Hidden courtyard of almshouses behind an unmarked door.', 'heritage', 120, 52.3693, 4.8901, true, null),
  ('amsterdam', 'amsterdam-rembrandt-house', 'Rembrandt House', 'Rembrandt’s home and studio, set up as in his day.', 'art', 100, 52.3694, 4.9012, false, null),
  ('amsterdam', 'amsterdam-hart', 'H’ART Museum', 'Art exhibitions in a 17th-century almshouse on the Amstel.', 'art', 100, 52.3653, 4.9024, false, null),
  ('amsterdam', 'amsterdam-ndsm', 'NDSM Wharf Street Art', 'Shipyard turned art city of graffiti and studios.', 'art', 100, 52.401, 4.892, false, null),
  ('amsterdam', 'amsterdam-maritime', 'National Maritime Museum', 'Seafaring history with a replica East India ship.', 'culture', 100, 52.3716, 4.915, false, null),
  ('amsterdam', 'amsterdam-oude-kerk', 'Oude Kerk', 'Amsterdam’s oldest building.', 'culture', 100, 52.3743, 4.8983, false, null),
  ('amsterdam', 'amsterdam-hortus', 'Hortus Botanicus', 'One of the oldest botanic gardens in the world.', 'nature', 80, 52.3667, 4.9081, false, null),
  ('amsterdam', 'amsterdam-amsterdamse-bos', 'Amsterdamse Bos', 'Forest three times the size of Central Park, with a goat farm.', 'nature', 80, 52.33, 4.835, false, null),
  ('amsterdam', 'amsterdam-westerpark', 'Westerpark', 'Park and old gasworks turned cultural park.', 'nature', 80, 52.387, 4.877, false, null),
  ('amsterdam', 'amsterdam-centraal', 'Amsterdam Centraal', 'Neo-Renaissance station on an artificial island.', 'travel', 80, 52.3791, 4.9003, false, null),
  ('amsterdam', 'amsterdam-adam-lookout', 'A’DAM Lookout and IJ Ferries', 'Free ferries across the IJ to a tower with a rooftop swing.', 'travel', 80, 52.3842, 4.902, false, null),
  ('berlin', 'berlin-brandenburg', 'Brandenburg Gate', 'Neoclassical gate and symbol of reunified Germany.', 'heritage', 120, 52.5163, 13.3777, false, null),
  ('berlin', 'berlin-reichstag', 'Reichstag Dome', 'Glass dome on the parliament building with a spiral walkway.', 'heritage', 120, 52.5186, 13.3762, false, null),
  ('berlin', 'berlin-east-side-gallery', 'East Side Gallery', 'The longest surviving stretch of the Berlin Wall, covered in murals.', 'culture', 100, 52.505, 13.4397, false, null),
  ('berlin', 'berlin-museum-island', 'Museum Island', 'Five world-class museums on an island in the Spree.', 'culture', 100, 52.5169, 13.4019, false, null),
  ('berlin', 'berlin-tiergarten', 'Tiergarten', 'Huge park in the centre of Berlin.', 'nature', 80, 52.5145, 13.3501, false, null),
  ('berlin', 'berlin-wall-memorial', 'Berlin Wall Memorial', 'The preserved death strip on Bernauer Strasse.', 'heritage', 120, 52.5351, 13.3903, false, null),
  ('berlin', 'berlin-schwarzenberg', 'Haus Schwarzenberg Courtyard', 'Street-art-covered courtyard just off a busy street.', 'culture', 100, 52.5245, 13.4022, true, null),
  ('berlin', 'berlin-hamburger-bahnhof', 'Hamburger Bahnhof', 'Contemporary art in a former railway station.', 'art', 100, 52.5284, 13.372, false, null),
  ('berlin', 'berlin-berlinische-galerie', 'Berlinische Galerie', 'Berlin’s museum of modern art, photography and architecture.', 'art', 100, 52.5031, 13.397, false, null),
  ('berlin', 'berlin-raw', 'RAW-Gelände', 'Old railway repair yard covered in street art.', 'art', 100, 52.507, 13.454, false, null),
  ('berlin', 'berlin-topography', 'Topography of Terror', 'Exhibition on the site of the former Gestapo headquarters.', 'culture', 100, 52.5067, 13.3837, false, null),
  ('berlin', 'berlin-gendarmenmarkt', 'Gendarmenmarkt', 'Square framed by twin domed churches and a concert hall.', 'culture', 100, 52.5136, 13.3927, false, null),
  ('berlin', 'berlin-tempelhof', 'Tempelhofer Feld', 'Former airport turned into a huge park on its runways.', 'nature', 80, 52.473, 13.401, false, null),
  ('berlin', 'berlin-treptower', 'Treptower Park', 'Riverside park with boats and a Soviet memorial.', 'nature', 80, 52.488, 13.47, false, null),
  ('berlin', 'berlin-viktoriapark', 'Viktoriapark', 'Hill park with a waterfall in the middle of Kreuzberg.', 'nature', 80, 52.488, 13.381, false, null),
  ('berlin', 'berlin-hauptbahnhof', 'Berlin Hauptbahnhof', 'Glass station where trains cross on several levels.', 'travel', 80, 52.5251, 13.3694, false, null),
  ('berlin', 'berlin-oberbaum', 'Oberbaum Bridge', 'Red-brick bridge with the U-Bahn running over the top.', 'travel', 80, 52.5016, 13.4458, false, null),
  ('prague', 'prague-charles-bridge', 'Charles Bridge', 'Gothic stone bridge lined with thirty statues.', 'heritage', 120, 50.0865, 14.4114, false, null),
  ('prague', 'prague-castle', 'Prague Castle', 'The largest ancient castle complex in the world.', 'heritage', 120, 50.0909, 14.4005, false, null),
  ('prague', 'prague-old-town', 'Old Town Square', 'Home of the astronomical clock that has ticked since 1410.', 'heritage', 120, 50.087, 14.4207, false, null),
  ('prague', 'prague-petrin', 'Petřín Hill', 'Wooded hill with a mini Eiffel Tower and orchards.', 'nature', 80, 50.0833, 14.395, false, null),
  ('prague', 'prague-dancing-house', 'Dancing House', 'Curvy building nicknamed Fred and Ginger.', 'culture', 100, 50.0755, 14.4141, false, null),
  ('prague', 'prague-lennon-wall', 'Lennon Wall', 'A wall of ever-changing graffiti and messages of peace.', 'culture', 100, 50.0862, 14.4067, true, null),
  ('prague', 'prague-dox', 'DOX Centre for Contemporary Art', 'Art centre with a giant wooden airship on its roof.', 'art', 100, 50.1066, 14.4485, false, null),
  ('prague', 'prague-mucha', 'Mucha Museum', 'Art Nouveau posters by Alphonse Mucha.', 'art', 100, 50.0848, 14.4245, false, null),
  ('prague', 'prague-kafka-head', 'Kafka’s Rotating Head', 'David Černý’s shining head of Kafka, turning in 42 layers.', 'art', 100, 50.082, 14.4205, false, null),
  ('prague', 'prague-national-museum', 'National Museum', 'Grand museum at the top of Wenceslas Square.', 'culture', 100, 50.079, 14.431, false, null),
  ('prague', 'prague-estates-theatre', 'Estates Theatre', 'Where Mozart premiered Don Giovanni.', 'culture', 100, 50.0857, 14.4231, false, null),
  ('prague', 'prague-letna', 'Letná Park', 'Hilltop park with a beer garden and bridge views.', 'nature', 80, 50.096, 14.419, false, null),
  ('prague', 'prague-vysehrad', 'Vyšehrad', 'Fortress park above the river, quieter than the castle.', 'nature', 80, 50.0645, 14.418, false, null),
  ('prague', 'prague-stromovka', 'Stromovka Park', 'Former royal hunting grounds, with ponds and meadows.', 'nature', 80, 50.106, 14.425, false, null),
  ('prague', 'prague-petrin-funicular', 'Petřín Funicular', 'Funicular up through the orchards of Petřín Hill.', 'travel', 80, 50.0815, 14.4055, false, null),
  ('prague', 'prague-fanta-building', 'Prague Main Station Fanta Hall', 'Art Nouveau station hall with a domed café.', 'travel', 80, 50.0832, 14.435, false, null),
  ('vienna', 'vienna-schonbrunn', 'Schönbrunn Palace', 'Habsburg summer palace with formal gardens and a hilltop arcade.', 'heritage', 120, 48.1845, 16.3122, false, null),
  ('vienna', 'vienna-stephansdom', 'St Stephen’s Cathedral', 'Gothic cathedral with a glazed-tile roof.', 'heritage', 120, 48.2085, 16.3731, false, null),
  ('vienna', 'vienna-belvedere', 'Belvedere', 'Baroque palace that holds Klimt’s The Kiss.', 'culture', 100, 48.1915, 16.3809, false, null),
  ('vienna', 'vienna-opera', 'Vienna State Opera', 'One of the world’s great opera houses.', 'music_events', 100, 48.203, 16.369, false, '[{"days": [0, 1, 2, 3, 4, 5, 6], "open": "10:00", "close": "23:00"}]'::jsonb),
  ('vienna', 'vienna-prater', 'Prater Giant Wheel', 'Ferris wheel turning above the Prater since 1897.', 'other', 60, 48.2166, 16.3958, false, null),
  ('vienna', 'vienna-naschmarkt', 'Naschmarkt', 'Vienna’s most popular market, over a kilometre long.', 'other', 60, 48.1985, 16.3632, false, '[{"days": [1, 2, 3, 4, 5, 6], "open": "06:00", "close": "19:30"}]'::jsonb),
  ('vienna', 'vienna-hundertwasser', 'Hundertwasser House', 'A wavy, colourful apartment block with trees growing on its roof.', 'culture', 100, 48.2072, 16.394, true, null),
  ('vienna', 'vienna-albertina', 'Albertina', 'From Dürer’s hare to Monet and Picasso.', 'art', 100, 48.2045, 16.3681, false, null),
  ('vienna', 'vienna-leopold', 'Leopold Museum', 'The world’s largest Egon Schiele collection.', 'art', 100, 48.2032, 16.3592, false, null),
  ('vienna', 'vienna-secession', 'Secession Building', 'Golden-domed temple of Art Nouveau with Klimt’s frieze.', 'art', 100, 48.2006, 16.3657, false, null),
  ('vienna', 'vienna-kunsthistorisches', 'Kunsthistorisches Museum', 'Bruegels and a café under the dome.', 'culture', 100, 48.2038, 16.3617, false, null),
  ('vienna', 'vienna-hofburg', 'Hofburg Palace', 'Imperial palace, home of the Spanish Riding School.', 'culture', 100, 48.2066, 16.3655, false, null),
  ('vienna', 'vienna-stadtpark', 'Stadtpark', 'Park with the golden statue of Johann Strauss.', 'nature', 80, 48.2049, 16.3797, false, null),
  ('vienna', 'vienna-kahlenberg', 'Kahlenberg', 'Hill in the Vienna Woods with vineyards and a city view.', 'nature', 80, 48.2757, 16.3333, false, null),
  ('vienna', 'vienna-donauinsel', 'Danube Island', 'Twenty-one kilometres of island for swimming and cycling.', 'nature', 80, 48.23, 16.415, false, null),
  ('vienna', 'vienna-ring-tram', 'Ring Tram at Schwedenplatz', 'Trams circling the grand Ringstrasse.', 'travel', 80, 48.2115, 16.3782, false, null),
  ('vienna', 'vienna-karlsplatz-pavilions', 'Otto Wagner Pavilions, Karlsplatz', 'Golden-flowered Jugendstil station buildings.', 'travel', 80, 48.2004, 16.3696, false, null),
  ('edinburgh', 'edinburgh-castle', 'Edinburgh Castle', 'Fortress on an extinct volcano above the city.', 'heritage', 120, 55.9486, -3.1999, false, null),
  ('edinburgh', 'edinburgh-arthurs-seat', 'Arthur’s Seat', 'Ancient volcano you can climb for a view over the Firth of Forth.', 'nature', 80, 55.9441, -3.1618, false, null),
  ('edinburgh', 'edinburgh-st-giles', 'St Giles’ Cathedral', 'Crowned spire on the Royal Mile.', 'heritage', 120, 55.9495, -3.1909, false, null),
  ('edinburgh', 'edinburgh-calton-hill', 'Calton Hill', 'Hill of monuments with the best sunset view in town.', 'nature', 80, 55.9553, -3.1827, false, null),
  ('edinburgh', 'edinburgh-national-museum', 'National Museum of Scotland', 'From Dolly the sheep to Pictish stones.', 'culture', 100, 55.9469, -3.19, false, null),
  ('edinburgh', 'edinburgh-portobello', 'Portobello Beach', 'Sandy beach with a Victorian promenade.', 'coast', 80, 55.9541, -3.11, false, null),
  ('edinburgh', 'edinburgh-dean-village', 'Dean Village', 'Old mill village beside the Water of Leith, minutes from Princes Street.', 'other', 60, 55.9522, -3.2161, true, null),
  ('edinburgh', 'edinburgh-national-gallery', 'Scottish National Gallery', 'Old masters in a temple on The Mound.', 'art', 100, 55.9509, -3.1959, false, null),
  ('edinburgh', 'edinburgh-modern-art', 'National Gallery of Modern Art', 'Modern art set in landscaped grounds.', 'art', 100, 55.9509, -3.228, false, null),
  ('edinburgh', 'edinburgh-leith-murals', 'Leith Murals', 'Colourful murals along Leith Walk.', 'art', 100, 55.969, -3.172, false, null),
  ('edinburgh', 'edinburgh-holyrood', 'Palace of Holyroodhouse', 'The King’s official residence in Scotland.', 'culture', 100, 55.9527, -3.1722, false, null),
  ('edinburgh', 'edinburgh-writers-museum', 'Writers’ Museum', 'Burns, Scott and Stevenson in a close off the Royal Mile.', 'culture', 100, 55.9493, -3.1945, false, null),
  ('edinburgh', 'edinburgh-botanic', 'Royal Botanic Garden', 'Glasshouses and a rock garden with skyline views.', 'nature', 80, 55.9658, -3.209, false, null),
  ('edinburgh', 'edinburgh-water-of-leith', 'Water of Leith Walkway', 'Riverside path from Stockbridge to Dean Village.', 'nature', 80, 55.9585, -3.2085, false, null),
  ('edinburgh', 'edinburgh-blackford-hill', 'Blackford Hill', 'Quiet hill with views to the castle and Arthur’s Seat.', 'nature', 80, 55.927, -3.19, false, null),
  ('edinburgh', 'edinburgh-waverley', 'Edinburgh Waverley', 'Station in a valley between the Old and New Towns.', 'travel', 80, 55.952, -3.189, false, null),
  ('edinburgh', 'edinburgh-britannia', 'Royal Yacht Britannia', 'The royal family’s former floating palace, moored in Leith.', 'travel', 80, 55.982, -3.177, false, null)
) as v(region, source_id, name, description, category, base_points, lat, lng, hidden, hours)
join public.regions r on r.slug = v.region
on conflict (source, source_id) do nothing;

insert into public.place_stats (place_id)
select id from public.places
on conflict (place_id) do nothing;

-- 30 days of daily challenges starting today (Lisbon), rotating themes.
insert into public.daily_challenges (challenge_date, title, description, category, bonus_points)
select d::date,
       (array['Find a hidden viewpoint', 'Step into history', 'Culture hunt', 'Follow the coastline',
              'Art attack', 'All aboard', 'Wander anywhere new'])[1 + (i % 7)],
       (array['Discover any nature spot today.', 'Discover any heritage site today.',
              'Discover a museum or cultural place today.', 'Discover any beach or coastal spot today.',
              'Discover a gallery, mural or piece of street art today.',
              'Discover a famous station, tram, funicular or cable car today.',
              'Discover any place you have never visited.'])[1 + (i % 7)],
       (array['nature', 'heritage', 'culture', 'coast', 'art', 'travel', null])[1 + (i % 7)]::public.place_category,
       75
from generate_series(0, 29) as i,
     lateral (select (now() at time zone 'Europe/Lisbon')::date + i as d) x
on conflict (challenge_date) do nothing;

-- Curated collections (Phase 4).
with r as (select id from public.regions where slug = 'sintra')
insert into public.collections (slug, title, description, region_id, completion_bonus)
select v.slug, v.title, v.description, r.id, 50
from r, (values
  ('sintra-palaces', 'Sintra''s palaces', 'Romantic palaces, castles and estates in the hills.'),
  ('wild-coast', 'The wild coast', 'Cliffs, coves and the westernmost point of Europe.'),
  ('forest-secrets', 'Forest secrets', 'Quiet corners of the Sintra hills.')
) as v(slug, title, description)
on conflict (slug) do nothing;

insert into public.collection_places (collection_id, place_id, position)
select c.id, p.id, v.pos
from (values
  ('sintra-palaces', 'pena', 1), ('sintra-palaces', 'regaleira', 2), ('sintra-palaces', 'mouros', 3),
  ('sintra-palaces', 'monserrate', 4),
  ('wild-coast', 'cabo-da-roca', 1), ('wild-coast', 'adraga', 2),
  ('forest-secrets', 'capuchos', 1), ('forest-secrets', 'cruz-alta', 2)
) as v(slug, source_id, pos)
join public.collections c on c.slug = v.slug
join public.places p on p.source = 'seed' and p.source_id = v.source_id
on conflict do nothing;

-- City sets: 5 places each, mirrored from CITY_SETS in packages/shared/src/sets.ts (sets.test.ts checks).
insert into public.collections (slug, title, description, region_id, completion_bonus)
select v.slug, v.title, v.description, r.id, 50
from (values
  ('lisbon-icons', 'lisbon', 'Lisbon icons', 'The landmarks everyone talks about.'),
  ('lisbon-art-rails', 'lisbon', 'Lisbon art & rails', 'Three works of art and two rides worth taking.'),
  ('porto-icons', 'porto', 'Porto icons', 'The landmarks everyone talks about.'),
  ('porto-art-rails', 'porto', 'Porto art & rails', 'Three works of art and two rides worth taking.'),
  ('madrid-icons', 'madrid', 'Madrid icons', 'The landmarks everyone talks about.'),
  ('madrid-art-rails', 'madrid', 'Madrid art & rails', 'Three works of art and two rides worth taking.'),
  ('barcelona-icons', 'barcelona', 'Barcelona icons', 'The landmarks everyone talks about.'),
  ('barcelona-art-rails', 'barcelona', 'Barcelona art & rails', 'Three works of art and two rides worth taking.'),
  ('paris-icons', 'paris', 'Paris icons', 'The landmarks everyone talks about.'),
  ('paris-art-rails', 'paris', 'Paris art & rails', 'Three works of art and two rides worth taking.'),
  ('rome-icons', 'rome', 'Rome icons', 'The landmarks everyone talks about.'),
  ('rome-art-rails', 'rome', 'Rome art & rails', 'Three works of art and two rides worth taking.'),
  ('florence-icons', 'florence', 'Florence icons', 'The landmarks everyone talks about.'),
  ('florence-art-rails', 'florence', 'Florence art & rails', 'Three works of art and two rides worth taking.'),
  ('amsterdam-icons', 'amsterdam', 'Amsterdam icons', 'The landmarks everyone talks about.'),
  ('amsterdam-art-rails', 'amsterdam', 'Amsterdam art & rails', 'Three works of art and two rides worth taking.'),
  ('berlin-icons', 'berlin', 'Berlin icons', 'The landmarks everyone talks about.'),
  ('berlin-art-rails', 'berlin', 'Berlin art & rails', 'Three works of art and two rides worth taking.'),
  ('prague-icons', 'prague', 'Prague icons', 'The landmarks everyone talks about.'),
  ('prague-art-rails', 'prague', 'Prague art & rails', 'Three works of art and two rides worth taking.'),
  ('vienna-icons', 'vienna', 'Vienna icons', 'The landmarks everyone talks about.'),
  ('vienna-art-rails', 'vienna', 'Vienna art & rails', 'Three works of art and two rides worth taking.'),
  ('edinburgh-icons', 'edinburgh', 'Edinburgh icons', 'The landmarks everyone talks about.'),
  ('edinburgh-art-rails', 'edinburgh', 'Edinburgh art & rails', 'Three works of art and two rides worth taking.')
) as v(slug, region, title, description)
join public.regions r on r.slug = v.region
on conflict (slug) do nothing;

insert into public.collection_places (collection_id, place_id, position)
select c.id, p.id, v.pos
from (values
('lisbon-icons', 'lisbon-belem-tower', 1),
('lisbon-icons', 'lisbon-jeronimos', 2),
('lisbon-icons', 'lisbon-sao-jorge', 3),
('lisbon-icons', 'lisbon-gulbenkian', 4),
('lisbon-icons', 'lisbon-azulejo', 5),
('lisbon-art-rails', 'lisbon-maat', 1),
('lisbon-art-rails', 'lisbon-berardo', 2),
('lisbon-art-rails', 'lisbon-crono-murals', 3),
('lisbon-art-rails', 'lisbon-tram-28', 4),
('lisbon-art-rails', 'lisbon-santa-justa', 5),
('porto-icons', 'porto-ribeira', 1),
('porto-icons', 'porto-lello', 2),
('porto-icons', 'porto-dom-luis', 3),
('porto-icons', 'porto-clerigos', 4),
('porto-icons', 'porto-bolsa', 5),
('porto-art-rails', 'porto-serralves', 1),
('porto-art-rails', 'porto-soares-dos-reis', 2),
('porto-art-rails', 'porto-half-rabbit', 3),
('porto-art-rails', 'porto-sao-bento', 4),
('porto-art-rails', 'porto-guindais', 5),
('madrid-icons', 'madrid-royal-palace', 1),
('madrid-icons', 'madrid-prado', 2),
('madrid-icons', 'madrid-plaza-mayor', 3),
('madrid-icons', 'madrid-retiro', 4),
('madrid-icons', 'madrid-san-miguel', 5),
('madrid-art-rails', 'madrid-reina-sofia', 1),
('madrid-art-rails', 'madrid-thyssen', 2),
('madrid-art-rails', 'madrid-caixaforum', 3),
('madrid-art-rails', 'madrid-atocha', 4),
('madrid-art-rails', 'madrid-teleferico', 5),
('barcelona-icons', 'barcelona-sagrada-familia', 1),
('barcelona-icons', 'barcelona-pedrera', 2),
('barcelona-icons', 'barcelona-park-guell', 3),
('barcelona-icons', 'barcelona-casa-batllo', 4),
('barcelona-icons', 'barcelona-ciutadella', 5),
('barcelona-art-rails', 'barcelona-picasso', 1),
('barcelona-art-rails', 'barcelona-miro', 2),
('barcelona-art-rails', 'barcelona-macba', 3),
('barcelona-art-rails', 'barcelona-montjuic-cable-car', 4),
('barcelona-art-rails', 'barcelona-port-cable-car', 5),
('paris-icons', 'paris-eiffel', 1),
('paris-icons', 'paris-louvre', 2),
('paris-icons', 'paris-notre-dame', 3),
('paris-icons', 'paris-sacre-coeur', 4),
('paris-icons', 'paris-garnier', 5),
('paris-art-rails', 'paris-orangerie', 1),
('paris-art-rails', 'paris-pompidou', 2),
('paris-art-rails', 'paris-rodin', 3),
('paris-art-rails', 'paris-gare-de-lyon', 4),
('paris-art-rails', 'paris-montmartre-funicular', 5),
('rome-icons', 'rome-colosseum', 1),
('rome-icons', 'rome-trevi', 2),
('rome-icons', 'rome-spanish-steps', 3),
('rome-icons', 'rome-pantheon', 4),
('rome-icons', 'rome-vatican-museums', 5),
('rome-art-rails', 'rome-doria-pamphilj', 1),
('rome-art-rails', 'rome-capitoline', 2),
('rome-art-rails', 'rome-ostiense-murals', 3),
('rome-art-rails', 'rome-termini', 4),
('rome-art-rails', 'rome-piramide', 5),
('florence-icons', 'florence-duomo', 1),
('florence-icons', 'florence-ponte-vecchio', 2),
('florence-icons', 'florence-uffizi', 3),
('florence-icons', 'florence-palazzo-vecchio', 4),
('florence-icons', 'florence-michelangelo', 5),
('florence-art-rails', 'florence-accademia', 1),
('florence-art-rails', 'florence-bargello', 2),
('florence-art-rails', 'florence-palatine', 3),
('florence-art-rails', 'florence-santa-maria-novella', 4),
('florence-art-rails', 'florence-renaioli', 5),
('amsterdam-icons', 'amsterdam-rijksmuseum', 1),
('amsterdam-icons', 'amsterdam-anne-frank', 2),
('amsterdam-icons', 'amsterdam-van-gogh', 3),
('amsterdam-icons', 'amsterdam-dam', 4),
('amsterdam-icons', 'amsterdam-vondelpark', 5),
('amsterdam-art-rails', 'amsterdam-rembrandt-house', 1),
('amsterdam-art-rails', 'amsterdam-hart', 2),
('amsterdam-art-rails', 'amsterdam-ndsm', 3),
('amsterdam-art-rails', 'amsterdam-centraal', 4),
('amsterdam-art-rails', 'amsterdam-adam-lookout', 5),
('berlin-icons', 'berlin-brandenburg', 1),
('berlin-icons', 'berlin-reichstag', 2),
('berlin-icons', 'berlin-east-side-gallery', 3),
('berlin-icons', 'berlin-museum-island', 4),
('berlin-icons', 'berlin-gendarmenmarkt', 5),
('berlin-art-rails', 'berlin-hamburger-bahnhof', 1),
('berlin-art-rails', 'berlin-berlinische-galerie', 2),
('berlin-art-rails', 'berlin-raw', 3),
('berlin-art-rails', 'berlin-hauptbahnhof', 4),
('berlin-art-rails', 'berlin-oberbaum', 5),
('prague-icons', 'prague-charles-bridge', 1),
('prague-icons', 'prague-old-town', 2),
('prague-icons', 'prague-castle', 3),
('prague-icons', 'prague-dancing-house', 4),
('prague-icons', 'prague-national-museum', 5),
('prague-art-rails', 'prague-dox', 1),
('prague-art-rails', 'prague-mucha', 2),
('prague-art-rails', 'prague-kafka-head', 3),
('prague-art-rails', 'prague-petrin-funicular', 4),
('prague-art-rails', 'prague-fanta-building', 5),
('vienna-icons', 'vienna-schonbrunn', 1),
('vienna-icons', 'vienna-stephansdom', 2),
('vienna-icons', 'vienna-hofburg', 3),
('vienna-icons', 'vienna-kunsthistorisches', 4),
('vienna-icons', 'vienna-belvedere', 5),
('vienna-art-rails', 'vienna-albertina', 1),
('vienna-art-rails', 'vienna-leopold', 2),
('vienna-art-rails', 'vienna-secession', 3),
('vienna-art-rails', 'vienna-ring-tram', 4),
('vienna-art-rails', 'vienna-karlsplatz-pavilions', 5),
('edinburgh-icons', 'edinburgh-castle', 1),
('edinburgh-icons', 'edinburgh-st-giles', 2),
('edinburgh-icons', 'edinburgh-national-museum', 3),
('edinburgh-icons', 'edinburgh-arthurs-seat', 4),
('edinburgh-icons', 'edinburgh-calton-hill', 5),
('edinburgh-art-rails', 'edinburgh-national-gallery', 1),
('edinburgh-art-rails', 'edinburgh-modern-art', 2),
('edinburgh-art-rails', 'edinburgh-leith-murals', 3),
('edinburgh-art-rails', 'edinburgh-waverley', 4),
('edinburgh-art-rails', 'edinburgh-britannia', 5)
) as v(slug, source_id, pos)
join public.collections c on c.slug = v.slug
join public.places p on p.source = 'seed' and p.source_id = v.source_id
on conflict do nothing;
