import { placeIn } from './place-in';
import { EUROPE_QUESTS } from './quests';
import type { Place } from './types';

/** Curated landmarks for the launch cities. `hidden` ones stay off the map until you're within 200 m. */
const LAUNCH_PLACES: Place[] = [
  placeIn(
    'sintra',
    'sintra-fonte-mourisca',
    'Moorish Fountain',
    'heritage',
    38.7983,
    -9.3858,
    3,
    'Neo-Moorish fountain tiled in green and white, tucked into a bend of the old road.',
    { hidden: true },
  ),
  placeIn(
    'sintra',
    'sintra-peninha',
    'Peninha Sanctuary',
    'nature',
    38.7686,
    -9.4589,
    9,
    'Hermit chapel on a granite crag with the whole coast below it.',
    { hidden: true },
  ),
  placeIn(
    'sintra',
    'sintra-musa',
    'MU.SA – Sintra Arts Museum',
    'art',
    38.7988,
    -9.3826,
    140,
    'Modern and contemporary art in the old casino building, a short walk from the palace.',
  ),
  placeIn(
    'sintra',
    'sintra-anjos-teixeira',
    'Anjos Teixeira Sculpture Museum',
    'art',
    38.795,
    -9.392,
    35,
    'Father-and-son sculptor’s studio, tucked beside the stream below the town.',
  ),
  placeIn(
    'sintra',
    'sintra-leal-da-camara',
    'Leal da Câmara House-Museum',
    'art',
    38.7826,
    -9.334,
    20,
    'Caricatures and posters by a cartoonist who mocked kings and politicians.',
  ),
  placeIn(
    'sintra',
    'sintra-national-palace',
    'Sintra National Palace',
    'culture',
    38.7976,
    -9.3906,
    3800,
    'Medieval royal palace crowned by two giant white chimneys.',
  ),
  placeIn(
    'sintra',
    'sintra-ferreira-de-castro',
    'Ferreira de Castro House-Museum',
    'culture',
    38.7962,
    -9.3913,
    45,
    'The study and library of one of Portugal’s great novelists.',
  ),
  placeIn(
    'sintra',
    'sintra-valley-of-lakes',
    'Valley of the Lakes, Pena Park',
    'nature',
    38.786,
    -9.392,
    600,
    'Chain of ponds with a little duck castle, deep in the palace gardens.',
  ),
  placeIn(
    'sintra',
    'sintra-lagoa-azul',
    'Lagoa Azul',
    'nature',
    38.771,
    -9.418,
    90,
    'Quiet blue lake in the pine forest on the road to the coast.',
  ),
  placeIn(
    'sintra',
    'sintra-pedra-amarela',
    'Pedra Amarela',
    'nature',
    38.781,
    -9.431,
    55,
    'Granite outcrop with a sweeping view over the hills to the sea.',
  ),
  placeIn(
    'sintra',
    'sintra-station',
    'Sintra Station',
    'travel',
    38.7988,
    -9.378,
    1500,
    'Tiled 19th-century terminus where the train from Lisbon ends.',
  ),
  placeIn(
    'sintra',
    'sintra-tram',
    'Sintra Tram at Praia das Maçãs',
    'travel',
    38.8226,
    -9.4664,
    260,
    'Vintage tram that rattles from the hills down to the beach.',
  ),
  placeIn(
    'lisbon',
    'lisbon-belem-tower',
    'Belém Tower',
    'heritage',
    38.6916,
    -9.216,
    4200,
    'Sixteenth-century fortress that guarded the mouth of the Tagus.',
  ),
  placeIn(
    'lisbon',
    'lisbon-jeronimos',
    'Jerónimos Monastery',
    'heritage',
    38.6979,
    -9.2068,
    3900,
    'Manueline monastery carved with ropes, shells and sea creatures.',
  ),
  placeIn(
    'lisbon',
    'lisbon-sao-jorge',
    'São Jorge Castle',
    'heritage',
    38.7139,
    -9.1335,
    3600,
    'Hilltop castle whose ramparts look over the red roofs of Alfama.',
  ),
  placeIn(
    'lisbon',
    'lisbon-senhora-do-monte',
    'Senhora do Monte Viewpoint',
    'nature',
    38.7193,
    -9.1326,
    420,
    'The highest viewpoint in Lisbon, under umbrella pines.',
  ),
  placeIn(
    'lisbon',
    'lisbon-lx-factory',
    'LX Factory',
    'culture',
    38.7037,
    -9.1785,
    1300,
    'Old textile mill turned into studios, bookshops and street art.',
  ),
  placeIn(
    'lisbon',
    'lisbon-fado-alfama',
    'Alfama Fado House',
    'music_events',
    38.7106,
    -9.1305,
    260,
    'Candle-lit room where fado is sung most nights.',
    { hours: [{ days: [0, 1, 2, 3, 4, 5, 6], open: '20:00', close: '01:00' }] },
  ),
  placeIn(
    'lisbon',
    'lisbon-sao-cristovao-steps',
    'São Cristóvão Steps',
    'other',
    38.7128,
    -9.1351,
    6,
    'Stairway painted with a mural of the fado singers who lived here.',
    { hidden: true },
  ),
  placeIn(
    'lisbon',
    'lisbon-maat',
    'MAAT',
    'art',
    38.6956,
    -9.195,
    2100,
    'Wave-shaped museum of art, architecture and technology you can walk on top of.',
  ),
  placeIn(
    'lisbon',
    'lisbon-berardo',
    'Berardo Collection at CCB',
    'art',
    38.6957,
    -9.2083,
    1700,
    'Modern art from Picasso to Warhol in the Belém Cultural Centre.',
  ),
  placeIn(
    'lisbon',
    'lisbon-crono-murals',
    'Crono Project Murals',
    'art',
    38.7315,
    -9.1468,
    380,
    'Giant murals painted across a row of abandoned buildings.',
  ),
  placeIn(
    'lisbon',
    'lisbon-gulbenkian',
    'Calouste Gulbenkian Museum',
    'culture',
    38.7372,
    -9.1545,
    2400,
    'From Egyptian treasures to Lalique jewels, in a modernist garden.',
  ),
  placeIn(
    'lisbon',
    'lisbon-azulejo',
    'National Tile Museum',
    'culture',
    38.7247,
    -9.1137,
    1300,
    'Five centuries of Portuguese tiles in a gilded convent.',
  ),
  placeIn(
    'lisbon',
    'lisbon-monsanto',
    'Monsanto Panoramic',
    'nature',
    38.73,
    -9.1835,
    210,
    'Abandoned hilltop restaurant in the forest with a 360° view.',
  ),
  placeIn(
    'lisbon',
    'lisbon-estufa-fria',
    'Estufa Fria',
    'nature',
    38.7287,
    -9.153,
    900,
    'Shaded greenhouse jungle of ferns, ponds and palms.',
  ),
  placeIn(
    'lisbon',
    'lisbon-estrela',
    'Estrela Garden',
    'nature',
    38.714,
    -9.1595,
    800,
    'Romantic park with a bandstand, ducks and a café by the lake.',
  ),
  placeIn(
    'lisbon',
    'lisbon-tram-28',
    'Tram 28 at Martim Moniz',
    'travel',
    38.716,
    -9.1365,
    4000,
    'Start of the famous yellow tram that climbs through Graça and Alfama.',
  ),
  placeIn(
    'lisbon',
    'lisbon-santa-justa',
    'Santa Justa Lift',
    'travel',
    38.7121,
    -9.1393,
    3500,
    'Neo-Gothic iron lift linking the Baixa to the Carmo ruins.',
  ),
  placeIn(
    'porto',
    'porto-ribeira',
    'Ribeira Waterfront',
    'heritage',
    41.1407,
    -8.6131,
    3100,
    'Stacked, colourful houses along the Douro quay.',
  ),
  placeIn(
    'porto',
    'porto-lello',
    'Livraria Lello',
    'culture',
    41.1469,
    -8.6149,
    2800,
    'Neo-Gothic bookshop with a crimson staircase.',
  ),
  placeIn(
    'porto',
    'porto-clerigos',
    'Clérigos Tower',
    'heritage',
    41.1457,
    -8.6146,
    2400,
    'Baroque bell tower with 240 steps to the top.',
  ),
  placeIn(
    'porto',
    'porto-dom-luis',
    'Dom Luís I Bridge',
    'heritage',
    41.1399,
    -8.6094,
    2600,
    'Double-decker iron bridge you can walk across at rooftop height.',
  ),
  placeIn(
    'porto',
    'porto-palacio-cristal',
    'Crystal Palace Gardens',
    'nature',
    41.1479,
    -8.6255,
    700,
    'Romantic gardens with peacocks and river views.',
  ),
  placeIn(
    'porto',
    'porto-foz',
    'Foz do Douro Beach',
    'coast',
    41.1497,
    -8.6764,
    500,
    'Where the Douro meets the Atlantic, with a lighthouse pier.',
  ),
  placeIn(
    'porto',
    'porto-virtudes',
    'Virtudes Terraces',
    'nature',
    41.1438,
    -8.6188,
    11,
    'Sloping garden where locals watch the sun set over the river.',
    { hidden: true },
  ),
  placeIn(
    'porto',
    'porto-serralves',
    'Serralves Museum',
    'art',
    41.1597,
    -8.6598,
    1500,
    'White Siza Vieira museum of contemporary art.',
  ),
  placeIn(
    'porto',
    'porto-soares-dos-reis',
    'Soares dos Reis Museum',
    'art',
    41.1475,
    -8.6215,
    600,
    'Portugal’s oldest public art museum, in a neoclassical palace.',
  ),
  placeIn(
    'porto',
    'porto-half-rabbit',
    'Bordalo II’s Half Rabbit',
    'art',
    41.1372,
    -8.6095,
    700,
    'Huge rabbit sculpted from street rubbish on a Gaia wall.',
  ),
  placeIn(
    'porto',
    'porto-bolsa',
    'Palácio da Bolsa',
    'culture',
    41.1414,
    -8.6156,
    2100,
    'Stock exchange palace with a dazzling Arab Room.',
  ),
  placeIn(
    'porto',
    'porto-wow',
    'World of Wine',
    'culture',
    41.1355,
    -8.6143,
    1200,
    'Museums about wine, cork and chocolate in old port cellars.',
  ),
  placeIn(
    'porto',
    'porto-serralves-park',
    'Serralves Park',
    'nature',
    41.1585,
    -8.661,
    1000,
    'Gardens, woods and a giant red trowel sculpture.',
  ),
  placeIn(
    'porto',
    'porto-city-park',
    'Porto City Park',
    'nature',
    41.1705,
    -8.678,
    500,
    'The biggest urban park in Portugal, running down to the sea.',
  ),
  placeIn(
    'porto',
    'porto-passeio-alegre',
    'Passeio Alegre Garden',
    'nature',
    41.148,
    -8.672,
    180,
    'Palm-lined promenade where the river meets the ocean.',
  ),
  placeIn(
    'porto',
    'porto-sao-bento',
    'São Bento Station',
    'travel',
    41.1456,
    -8.6106,
    3900,
    'Station hall covered in 20,000 blue-and-white tiles.',
  ),
  placeIn(
    'porto',
    'porto-guindais',
    'Guindais Funicular',
    'travel',
    41.1407,
    -8.6084,
    900,
    'Funicular that climbs the old city walls from the river.',
  ),
  placeIn(
    'madrid',
    'madrid-royal-palace',
    'Royal Palace of Madrid',
    'heritage',
    40.418,
    -3.7143,
    3500,
    'One of the largest palaces in Europe, with 3,400 rooms.',
  ),
  placeIn(
    'madrid',
    'madrid-prado',
    'Prado Museum',
    'culture',
    40.4138,
    -3.6921,
    3300,
    'Velázquez, Goya and Bosch under one roof.',
  ),
  placeIn(
    'madrid',
    'madrid-retiro',
    'Retiro Park',
    'nature',
    40.4153,
    -3.6845,
    2900,
    'Rowing lake, rose garden and a glass palace.',
  ),
  placeIn(
    'madrid',
    'madrid-plaza-mayor',
    'Plaza Mayor',
    'heritage',
    40.4155,
    -3.7074,
    3000,
    'Arcaded seventeenth-century square at the heart of old Madrid.',
  ),
  placeIn(
    'madrid',
    'madrid-debod',
    'Temple of Debod',
    'heritage',
    40.424,
    -3.7178,
    1500,
    'Ancient Egyptian temple rebuilt on a hill above the city.',
  ),
  placeIn(
    'madrid',
    'madrid-san-miguel',
    'San Miguel Market',
    'other',
    40.4154,
    -3.709,
    1800,
    'Iron-and-glass market hall full of tapas stalls.',
    { hours: [{ days: [0, 1, 2, 3, 4, 5, 6], open: '10:00', close: '00:00' }] },
  ),
  placeIn(
    'madrid',
    'madrid-anglona',
    'Prince of Anglona Garden',
    'nature',
    40.4127,
    -3.7118,
    8,
    'A tiny walled garden from the 1700s, easy to walk past.',
    { hidden: true },
  ),
  placeIn(
    'madrid',
    'madrid-reina-sofia',
    'Reina Sofía Museum',
    'art',
    40.408,
    -3.6946,
    3200,
    'Home of Picasso’s Guernica.',
  ),
  placeIn(
    'madrid',
    'madrid-thyssen',
    'Thyssen-Bornemisza Museum',
    'art',
    40.416,
    -3.6949,
    2400,
    'Seven centuries of painting in one private collection.',
  ),
  placeIn(
    'madrid',
    'madrid-caixaforum',
    'CaixaForum Madrid',
    'art',
    40.4113,
    -3.6934,
    1500,
    'Art centre beside a living wall of 15,000 plants.',
  ),
  placeIn(
    'madrid',
    'madrid-archaeological',
    'National Archaeological Museum',
    'culture',
    40.4235,
    -3.6893,
    1100,
    'Iberian treasures, including the mysterious Lady of Elche.',
  ),
  placeIn(
    'madrid',
    'madrid-teatro-real',
    'Teatro Real',
    'culture',
    40.4184,
    -3.711,
    1300,
    'Madrid’s grand opera house, facing the Royal Palace.',
  ),
  placeIn(
    'madrid',
    'madrid-botanic',
    'Royal Botanic Garden',
    'nature',
    40.4114,
    -3.691,
    1200,
    'Eighteenth-century terraces of plants and glasshouses.',
  ),
  placeIn(
    'madrid',
    'madrid-casa-de-campo',
    'Casa de Campo Lake',
    'nature',
    40.4196,
    -3.736,
    700,
    'Rowing lake in Madrid’s huge former royal hunting ground.',
  ),
  placeIn(
    'madrid',
    'madrid-rosaleda',
    'Rose Garden of Parque del Oeste',
    'nature',
    40.4291,
    -3.7225,
    400,
    'Hundreds of rose varieties, at their best in May.',
  ),
  placeIn(
    'madrid',
    'madrid-atocha',
    'Atocha Station Garden',
    'travel',
    40.407,
    -3.6905,
    2600,
    'Old train shed turned into a tropical garden with turtles.',
  ),
  placeIn(
    'madrid',
    'madrid-teleferico',
    'Madrid Cable Car',
    'travel',
    40.4268,
    -3.7203,
    600,
    'Cable car gliding over the trees of Casa de Campo.',
  ),
  placeIn(
    'barcelona',
    'barcelona-sagrada-familia',
    'Sagrada Família',
    'heritage',
    41.4036,
    2.1744,
    4500,
    'Gaudí’s basilica, still being built after more than a century.',
  ),
  placeIn(
    'barcelona',
    'barcelona-park-guell',
    'Park Güell',
    'nature',
    41.4145,
    2.1527,
    3400,
    'Mosaic terraces and gingerbread houses above the city.',
  ),
  placeIn(
    'barcelona',
    'barcelona-casa-batllo',
    'Casa Batlló',
    'culture',
    41.3917,
    2.1649,
    2700,
    'A house with a dragon’s back for a roof.',
  ),
  placeIn(
    'barcelona',
    'barcelona-barceloneta',
    'Barceloneta Beach',
    'coast',
    41.3784,
    2.1925,
    2200,
    'The city’s beach, a short walk from the old town.',
  ),
  placeIn(
    'barcelona',
    'barcelona-cathedral',
    'Barcelona Cathedral',
    'heritage',
    41.3839,
    2.1762,
    2500,
    'Gothic cathedral whose cloister is home to thirteen geese.',
  ),
  placeIn(
    'barcelona',
    'barcelona-palau-musica',
    'Palau de la Música Catalana',
    'music_events',
    41.3875,
    2.1753,
    900,
    'Modernista concert hall lit by a stained-glass skylight.',
    { hours: [{ days: [0, 1, 2, 3, 4, 5, 6], open: '10:00', close: '23:00' }] },
  ),
  placeIn(
    'barcelona',
    'barcelona-bunkers',
    'Carmel Bunkers',
    'nature',
    41.4192,
    2.1617,
    12,
    'Old anti-aircraft battery with a 360° view of Barcelona.',
    { hidden: true },
  ),
  placeIn(
    'barcelona',
    'barcelona-picasso',
    'Picasso Museum',
    'art',
    41.3852,
    2.1809,
    3600,
    'Picasso’s early years, in five medieval palaces.',
  ),
  placeIn(
    'barcelona',
    'barcelona-miro',
    'Fundació Joan Miró',
    'art',
    41.3685,
    2.16,
    1800,
    'Bright Miró paintings and sculptures on Montjuïc hill.',
  ),
  placeIn(
    'barcelona',
    'barcelona-macba',
    'MACBA',
    'art',
    41.3833,
    2.1668,
    1400,
    'White contemporary art museum, with skaters on the square outside.',
  ),
  placeIn(
    'barcelona',
    'barcelona-pedrera',
    'Casa Milà (La Pedrera)',
    'culture',
    41.3954,
    2.1619,
    3700,
    'Gaudí’s wavy apartment block with warrior-like chimneys.',
  ),
  placeIn(
    'barcelona',
    'barcelona-liceu',
    'Gran Teatre del Liceu',
    'culture',
    41.3803,
    2.1736,
    1300,
    'Red-and-gold opera house on La Rambla.',
  ),
  placeIn(
    'barcelona',
    'barcelona-ciutadella',
    'Parc de la Ciutadella',
    'nature',
    41.3881,
    2.1873,
    2600,
    'Park with a golden cascade fountain and a boating lake.',
  ),
  placeIn(
    'barcelona',
    'barcelona-tibidabo',
    'Tibidabo Summit',
    'nature',
    41.422,
    2.119,
    1600,
    'Mountain top with a vintage amusement park and a view of the whole city.',
  ),
  placeIn(
    'barcelona',
    'barcelona-horta-labyrinth',
    'Horta Labyrinth Park',
    'nature',
    41.4398,
    2.1464,
    500,
    'Neoclassical garden with a cypress hedge maze.',
  ),
  placeIn(
    'barcelona',
    'barcelona-montjuic-cable-car',
    'Montjuïc Cable Car',
    'travel',
    41.3717,
    2.1659,
    1400,
    'Cable car up to the castle on Montjuïc.',
  ),
  placeIn(
    'barcelona',
    'barcelona-port-cable-car',
    'Port Vell Aerial Tramway',
    'travel',
    41.372,
    2.189,
    1100,
    '1930s cable car swinging across the harbour.',
  ),
  placeIn(
    'paris',
    'paris-eiffel',
    'Eiffel Tower',
    'heritage',
    48.8584,
    2.2945,
    5000,
    'Iron lattice tower that sparkles on the hour after dark.',
  ),
  placeIn(
    'paris',
    'paris-louvre',
    'Louvre Museum',
    'culture',
    48.8606,
    2.3376,
    4800,
    'The world’s most visited museum, behind a glass pyramid.',
  ),
  placeIn(
    'paris',
    'paris-notre-dame',
    'Notre-Dame de Paris',
    'heritage',
    48.853,
    2.3499,
    4400,
    'Gothic cathedral on the Île de la Cité, restored after the 2019 fire.',
  ),
  placeIn(
    'paris',
    'paris-sacre-coeur',
    'Sacré-Cœur',
    'heritage',
    48.8867,
    2.3431,
    3800,
    'White basilica on top of Montmartre.',
  ),
  placeIn(
    'paris',
    'paris-luxembourg',
    'Luxembourg Gardens',
    'nature',
    48.8462,
    2.3372,
    2600,
    'Palace gardens with toy sailboats on the pond.',
  ),
  placeIn(
    'paris',
    'paris-orsay',
    'Musée d’Orsay',
    'culture',
    48.86,
    2.3266,
    3200,
    'Impressionist paintings inside a former railway station.',
  ),
  placeIn(
    'paris',
    'paris-cremieux',
    'Rue Crémieux',
    'other',
    48.847,
    2.3709,
    14,
    'A short cobbled street of pastel-painted houses.',
    { hidden: true },
  ),
  placeIn(
    'paris',
    'paris-orangerie',
    'Musée de l’Orangerie',
    'art',
    48.8638,
    2.3227,
    2800,
    'Monet’s Water Lilies wrap around two oval rooms.',
  ),
  placeIn(
    'paris',
    'paris-pompidou',
    'Centre Pompidou',
    'art',
    48.8606,
    2.3522,
    3500,
    'Inside-out building full of modern art.',
  ),
  placeIn(
    'paris',
    'paris-rodin',
    'Musée Rodin',
    'art',
    48.8553,
    2.3159,
    2300,
    'The Thinker sits in a rose garden.',
  ),
  placeIn(
    'paris',
    'paris-garnier',
    'Palais Garnier',
    'culture',
    48.872,
    2.3316,
    3300,
    'Gilded opera house with a Chagall ceiling.',
  ),
  placeIn(
    'paris',
    'paris-pantheon',
    'Panthéon',
    'culture',
    48.8462,
    2.346,
    2500,
    'Domed resting place of France’s great names.',
  ),
  placeIn(
    'paris',
    'paris-buttes-chaumont',
    'Parc des Buttes-Chaumont',
    'nature',
    48.8809,
    2.3828,
    1400,
    'Cliffs, a waterfall and a temple on an island.',
  ),
  placeIn(
    'paris',
    'paris-jardin-des-plantes',
    'Jardin des Plantes',
    'nature',
    48.844,
    2.359,
    1900,
    'Botanic garden with glasshouses and a small zoo.',
  ),
  placeIn(
    'paris',
    'paris-coulee-verte',
    'Coulée Verte',
    'nature',
    48.8486,
    2.3747,
    600,
    'Garden walk along an old railway viaduct.',
  ),
  placeIn(
    'paris',
    'paris-gare-de-lyon',
    'Gare de Lyon Clock Tower',
    'travel',
    48.8443,
    2.3735,
    2200,
    'Grand station with a clock tower and the ornate Le Train Bleu.',
  ),
  placeIn(
    'paris',
    'paris-montmartre-funicular',
    'Montmartre Funicular',
    'travel',
    48.8851,
    2.3434,
    2600,
    'Little funicular up to Sacré-Cœur.',
  ),
  placeIn(
    'rome',
    'rome-colosseum',
    'Colosseum',
    'heritage',
    41.8902,
    12.4922,
    5000,
    'Amphitheatre that held 50,000 spectators.',
  ),
  placeIn(
    'rome',
    'rome-pantheon',
    'Pantheon',
    'heritage',
    41.8986,
    12.4769,
    4300,
    'Two-thousand-year-old temple with an open eye in its dome.',
  ),
  placeIn(
    'rome',
    'rome-trevi',
    'Trevi Fountain',
    'heritage',
    41.9009,
    12.4833,
    4600,
    'Throw a coin over your shoulder to return to Rome.',
  ),
  placeIn(
    'rome',
    'rome-forum',
    'Roman Forum',
    'heritage',
    41.8925,
    12.4853,
    3500,
    'The ruins of ancient Rome’s public square.',
  ),
  placeIn(
    'rome',
    'rome-borghese',
    'Villa Borghese Gardens',
    'nature',
    41.9142,
    12.4923,
    1900,
    'Rome’s central park, with a lake temple and a view from the Pincio.',
  ),
  placeIn(
    'rome',
    'rome-vatican-museums',
    'Vatican Museums',
    'culture',
    41.9065,
    12.4536,
    4100,
    'Miles of galleries ending at the Sistine Chapel.',
  ),
  placeIn(
    'rome',
    'rome-aventine-keyhole',
    'Aventine Keyhole',
    'other',
    41.8833,
    12.4797,
    10,
    'Peek through a garden door’s keyhole to see St Peter’s dome framed perfectly.',
    { hidden: true },
  ),
  placeIn(
    'rome',
    'rome-doria-pamphilj',
    'Galleria Doria Pamphilj',
    'art',
    41.8979,
    12.4813,
    700,
    'A family palace still full of its Caravaggios and Velázquez.',
  ),
  placeIn(
    'rome',
    'rome-capitoline',
    'Capitoline Museums',
    'art',
    41.8933,
    12.4828,
    2400,
    'The world’s oldest public museum, with the bronze she-wolf.',
  ),
  placeIn(
    'rome',
    'rome-ostiense-murals',
    'Ostiense Street Art',
    'art',
    41.8695,
    12.4795,
    250,
    'Building-sized murals in Rome’s old industrial quarter.',
  ),
  placeIn(
    'rome',
    'rome-castel-sant-angelo',
    'Castel Sant’Angelo',
    'culture',
    41.9031,
    12.4663,
    3500,
    'Emperor’s tomb turned papal fortress.',
  ),
  placeIn(
    'rome',
    'rome-spanish-steps',
    'Spanish Steps',
    'culture',
    41.906,
    12.4826,
    4500,
    'Baroque stairway climbing to Trinità dei Monti.',
  ),
  placeIn(
    'rome',
    'rome-orange-garden',
    'Orange Garden',
    'nature',
    41.8848,
    12.479,
    1600,
    'Bitter-orange trees and a terrace over the rooftops.',
  ),
  placeIn(
    'rome',
    'rome-doria-pamphili-park',
    'Villa Doria Pamphili',
    'nature',
    41.885,
    12.452,
    600,
    'Rome’s biggest park, with umbrella pines and fountains.',
  ),
  placeIn(
    'rome',
    'rome-janiculum',
    'Janiculum Terrace',
    'nature',
    41.892,
    12.461,
    1100,
    'Hilltop view where a cannon fires at noon.',
  ),
  placeIn(
    'rome',
    'rome-termini',
    'Roma Termini',
    'travel',
    41.901,
    12.5016,
    3000,
    'Modernist station hall with a flowing concrete roof.',
  ),
  placeIn(
    'rome',
    'rome-piramide',
    'Pyramid and Porta San Paolo',
    'travel',
    41.8763,
    12.4808,
    800,
    'An ancient pyramid beside the station for the train to Ostia.',
  ),
  placeIn(
    'florence',
    'florence-duomo',
    'Florence Cathedral',
    'heritage',
    43.7731,
    11.256,
    4200,
    'Brunelleschi’s dome still dominates the skyline.',
  ),
  placeIn(
    'florence',
    'florence-uffizi',
    'Uffizi Gallery',
    'culture',
    43.7678,
    11.2553,
    3700,
    'Botticelli’s Venus and the Renaissance masters.',
  ),
  placeIn(
    'florence',
    'florence-ponte-vecchio',
    'Ponte Vecchio',
    'heritage',
    43.768,
    11.2531,
    3900,
    'Medieval bridge lined with goldsmiths’ shops.',
  ),
  placeIn(
    'florence',
    'florence-michelangelo',
    'Piazzale Michelangelo',
    'nature',
    43.7629,
    11.265,
    2600,
    'The classic sunset view over Florence.',
  ),
  placeIn(
    'florence',
    'florence-boboli',
    'Boboli Gardens',
    'nature',
    43.7625,
    11.2484,
    1700,
    'Terraced Medici gardens full of statues and grottoes.',
  ),
  placeIn(
    'florence',
    'florence-rose-garden',
    'Rose Garden',
    'nature',
    43.7638,
    11.2626,
    7,
    'Quiet terraced rose garden just below the famous viewpoint.',
    { hidden: true },
  ),
  placeIn(
    'florence',
    'florence-accademia',
    'Galleria dell’Accademia',
    'art',
    43.7768,
    11.2586,
    4200,
    'Michelangelo’s David.',
  ),
  placeIn(
    'florence',
    'florence-bargello',
    'Bargello Museum',
    'art',
    43.7704,
    11.2581,
    1400,
    'Renaissance sculpture in a medieval prison.',
  ),
  placeIn(
    'florence',
    'florence-palatine',
    'Palatine Gallery, Palazzo Pitti',
    'art',
    43.7651,
    11.25,
    1900,
    'Raphael and Titian in the Medici family palace.',
  ),
  placeIn(
    'florence',
    'florence-palazzo-vecchio',
    'Palazzo Vecchio',
    'culture',
    43.7693,
    11.2558,
    3600,
    'Fortress-like town hall with secret passages.',
  ),
  placeIn(
    'florence',
    'florence-santa-croce',
    'Basilica of Santa Croce',
    'culture',
    43.7686,
    11.2622,
    2600,
    'Burial place of Michelangelo and Galileo.',
  ),
  placeIn(
    'florence',
    'florence-bardini',
    'Bardini Garden',
    'nature',
    43.765,
    11.258,
    500,
    'Wisteria tunnel with a view of the Duomo.',
  ),
  placeIn(
    'florence',
    'florence-cascine',
    'Cascine Park',
    'nature',
    43.782,
    11.22,
    400,
    'Long riverside park, once the Medici farm.',
  ),
  placeIn(
    'florence',
    'florence-fiesole',
    'Fiesole Viewpoint',
    'nature',
    43.8066,
    11.2934,
    900,
    'Hill town with a view down to Florence.',
  ),
  placeIn(
    'florence',
    'florence-santa-maria-novella',
    'Santa Maria Novella Station',
    'travel',
    43.7764,
    11.248,
    2500,
    '1930s modernist station, a design icon.',
  ),
  placeIn(
    'florence',
    'florence-renaioli',
    'Renaioli Boats on the Arno',
    'travel',
    43.768,
    11.2575,
    150,
    'Traditional flat boats punted along the river at sunset.',
  ),
  placeIn(
    'amsterdam',
    'amsterdam-rijksmuseum',
    'Rijksmuseum',
    'culture',
    52.36,
    4.8852,
    3600,
    'Rembrandt’s Night Watch and the Dutch Golden Age.',
  ),
  placeIn(
    'amsterdam',
    'amsterdam-anne-frank',
    'Anne Frank House',
    'heritage',
    52.3752,
    4.884,
    3300,
    'The canal house where Anne Frank wrote her diary.',
  ),
  placeIn(
    'amsterdam',
    'amsterdam-vondelpark',
    'Vondelpark',
    'nature',
    52.358,
    4.8686,
    2400,
    'The city’s favourite park for cycling and picnics.',
  ),
  placeIn(
    'amsterdam',
    'amsterdam-van-gogh',
    'Van Gogh Museum',
    'culture',
    52.3584,
    4.8811,
    3100,
    'The largest collection of Van Gogh’s work.',
  ),
  placeIn(
    'amsterdam',
    'amsterdam-dam',
    'Royal Palace on Dam Square',
    'heritage',
    52.3731,
    4.8913,
    2700,
    'Seventeenth-century town hall turned royal palace.',
  ),
  placeIn(
    'amsterdam',
    'amsterdam-concertgebouw',
    'Concertgebouw',
    'music_events',
    52.3563,
    4.8789,
    800,
    'Concert hall famous for its near-perfect acoustics.',
    { hours: [{ days: [0, 1, 2, 3, 4, 5, 6], open: '10:00', close: '23:00' }] },
  ),
  placeIn(
    'amsterdam',
    'amsterdam-begijnhof',
    'Begijnhof',
    'heritage',
    52.3693,
    4.8901,
    13,
    'Hidden courtyard of almshouses behind an unmarked door.',
    { hidden: true },
  ),
  placeIn(
    'amsterdam',
    'amsterdam-rembrandt-house',
    'Rembrandt House',
    'art',
    52.3694,
    4.9012,
    2100,
    'Rembrandt’s home and studio, set up as in his day.',
  ),
  placeIn(
    'amsterdam',
    'amsterdam-hart',
    'H’ART Museum',
    'art',
    52.3653,
    4.9024,
    900,
    'Art exhibitions in a 17th-century almshouse on the Amstel.',
  ),
  placeIn(
    'amsterdam',
    'amsterdam-ndsm',
    'NDSM Wharf Street Art',
    'art',
    52.401,
    4.892,
    600,
    'Shipyard turned art city of graffiti and studios.',
  ),
  placeIn(
    'amsterdam',
    'amsterdam-maritime',
    'National Maritime Museum',
    'culture',
    52.3716,
    4.915,
    1500,
    'Seafaring history with a replica East India ship.',
  ),
  placeIn(
    'amsterdam',
    'amsterdam-oude-kerk',
    'Oude Kerk',
    'culture',
    52.3743,
    4.8983,
    1300,
    'Amsterdam’s oldest building.',
  ),
  placeIn(
    'amsterdam',
    'amsterdam-hortus',
    'Hortus Botanicus',
    'nature',
    52.3667,
    4.9081,
    1100,
    'One of the oldest botanic gardens in the world.',
  ),
  placeIn(
    'amsterdam',
    'amsterdam-amsterdamse-bos',
    'Amsterdamse Bos',
    'nature',
    52.33,
    4.835,
    500,
    'Forest three times the size of Central Park, with a goat farm.',
  ),
  placeIn(
    'amsterdam',
    'amsterdam-westerpark',
    'Westerpark',
    'nature',
    52.387,
    4.877,
    700,
    'Park and old gasworks turned cultural park.',
  ),
  placeIn(
    'amsterdam',
    'amsterdam-centraal',
    'Amsterdam Centraal',
    'travel',
    52.3791,
    4.9003,
    3500,
    'Neo-Renaissance station on an artificial island.',
  ),
  placeIn(
    'amsterdam',
    'amsterdam-adam-lookout',
    'A’DAM Lookout and IJ Ferries',
    'travel',
    52.3842,
    4.902,
    1600,
    'Free ferries across the IJ to a tower with a rooftop swing.',
  ),
  placeIn(
    'berlin',
    'berlin-brandenburg',
    'Brandenburg Gate',
    'heritage',
    52.5163,
    13.3777,
    4400,
    'Neoclassical gate and symbol of reunified Germany.',
  ),
  placeIn(
    'berlin',
    'berlin-reichstag',
    'Reichstag Dome',
    'heritage',
    52.5186,
    13.3762,
    3200,
    'Glass dome on the parliament building with a spiral walkway.',
  ),
  placeIn(
    'berlin',
    'berlin-east-side-gallery',
    'East Side Gallery',
    'culture',
    52.505,
    13.4397,
    3000,
    'The longest surviving stretch of the Berlin Wall, covered in murals.',
  ),
  placeIn(
    'berlin',
    'berlin-museum-island',
    'Museum Island',
    'culture',
    52.5169,
    13.4019,
    2900,
    'Five world-class museums on an island in the Spree.',
  ),
  placeIn(
    'berlin',
    'berlin-tiergarten',
    'Tiergarten',
    'nature',
    52.5145,
    13.3501,
    2100,
    'Huge park in the centre of Berlin.',
  ),
  placeIn(
    'berlin',
    'berlin-wall-memorial',
    'Berlin Wall Memorial',
    'heritage',
    52.5351,
    13.3903,
    1900,
    'The preserved death strip on Bernauer Strasse.',
  ),
  placeIn(
    'berlin',
    'berlin-schwarzenberg',
    'Haus Schwarzenberg Courtyard',
    'culture',
    52.5245,
    13.4022,
    15,
    'Street-art-covered courtyard just off a busy street.',
    { hidden: true },
  ),
  placeIn(
    'berlin',
    'berlin-hamburger-bahnhof',
    'Hamburger Bahnhof',
    'art',
    52.5284,
    13.372,
    1200,
    'Contemporary art in a former railway station.',
  ),
  placeIn(
    'berlin',
    'berlin-berlinische-galerie',
    'Berlinische Galerie',
    'art',
    52.5031,
    13.397,
    700,
    'Berlin’s museum of modern art, photography and architecture.',
  ),
  placeIn(
    'berlin',
    'berlin-raw',
    'RAW-Gelände',
    'art',
    52.507,
    13.454,
    800,
    'Old railway repair yard covered in street art.',
  ),
  placeIn(
    'berlin',
    'berlin-topography',
    'Topography of Terror',
    'culture',
    52.5067,
    13.3837,
    2000,
    'Exhibition on the site of the former Gestapo headquarters.',
  ),
  placeIn(
    'berlin',
    'berlin-gendarmenmarkt',
    'Gendarmenmarkt',
    'culture',
    52.5136,
    13.3927,
    2600,
    'Square framed by twin domed churches and a concert hall.',
  ),
  placeIn(
    'berlin',
    'berlin-tempelhof',
    'Tempelhofer Feld',
    'nature',
    52.473,
    13.401,
    1800,
    'Former airport turned into a huge park on its runways.',
  ),
  placeIn(
    'berlin',
    'berlin-treptower',
    'Treptower Park',
    'nature',
    52.488,
    13.47,
    800,
    'Riverside park with boats and a Soviet memorial.',
  ),
  placeIn(
    'berlin',
    'berlin-viktoriapark',
    'Viktoriapark',
    'nature',
    52.488,
    13.381,
    600,
    'Hill park with a waterfall in the middle of Kreuzberg.',
  ),
  placeIn(
    'berlin',
    'berlin-hauptbahnhof',
    'Berlin Hauptbahnhof',
    'travel',
    52.5251,
    13.3694,
    2900,
    'Glass station where trains cross on several levels.',
  ),
  placeIn(
    'berlin',
    'berlin-oberbaum',
    'Oberbaum Bridge',
    'travel',
    52.5016,
    13.4458,
    1700,
    'Red-brick bridge with the U-Bahn running over the top.',
  ),
  placeIn(
    'prague',
    'prague-charles-bridge',
    'Charles Bridge',
    'heritage',
    50.0865,
    14.4114,
    4300,
    'Gothic stone bridge lined with thirty statues.',
  ),
  placeIn(
    'prague',
    'prague-castle',
    'Prague Castle',
    'heritage',
    50.0909,
    14.4005,
    4000,
    'The largest ancient castle complex in the world.',
  ),
  placeIn(
    'prague',
    'prague-old-town',
    'Old Town Square',
    'heritage',
    50.087,
    14.4207,
    4200,
    'Home of the astronomical clock that has ticked since 1410.',
  ),
  placeIn(
    'prague',
    'prague-petrin',
    'Petřín Hill',
    'nature',
    50.0833,
    14.395,
    1500,
    'Wooded hill with a mini Eiffel Tower and orchards.',
  ),
  placeIn(
    'prague',
    'prague-dancing-house',
    'Dancing House',
    'culture',
    50.0755,
    14.4141,
    1800,
    'Curvy building nicknamed Fred and Ginger.',
  ),
  placeIn(
    'prague',
    'prague-lennon-wall',
    'Lennon Wall',
    'culture',
    50.0862,
    14.4067,
    16,
    'A wall of ever-changing graffiti and messages of peace.',
    { hidden: true },
  ),
  placeIn(
    'prague',
    'prague-dox',
    'DOX Centre for Contemporary Art',
    'art',
    50.1066,
    14.4485,
    500,
    'Art centre with a giant wooden airship on its roof.',
  ),
  placeIn(
    'prague',
    'prague-mucha',
    'Mucha Museum',
    'art',
    50.0848,
    14.4245,
    1600,
    'Art Nouveau posters by Alphonse Mucha.',
  ),
  placeIn(
    'prague',
    'prague-kafka-head',
    'Kafka’s Rotating Head',
    'art',
    50.082,
    14.4205,
    1400,
    'David Černý’s shining head of Kafka, turning in 42 layers.',
  ),
  placeIn(
    'prague',
    'prague-national-museum',
    'National Museum',
    'culture',
    50.079,
    14.431,
    1800,
    'Grand museum at the top of Wenceslas Square.',
  ),
  placeIn(
    'prague',
    'prague-estates-theatre',
    'Estates Theatre',
    'culture',
    50.0857,
    14.4231,
    900,
    'Where Mozart premiered Don Giovanni.',
  ),
  placeIn(
    'prague',
    'prague-letna',
    'Letná Park',
    'nature',
    50.096,
    14.419,
    1300,
    'Hilltop park with a beer garden and bridge views.',
  ),
  placeIn(
    'prague',
    'prague-vysehrad',
    'Vyšehrad',
    'nature',
    50.0645,
    14.418,
    1200,
    'Fortress park above the river, quieter than the castle.',
  ),
  placeIn(
    'prague',
    'prague-stromovka',
    'Stromovka Park',
    'nature',
    50.106,
    14.425,
    500,
    'Former royal hunting grounds, with ponds and meadows.',
  ),
  placeIn(
    'prague',
    'prague-petrin-funicular',
    'Petřín Funicular',
    'travel',
    50.0815,
    14.4055,
    1500,
    'Funicular up through the orchards of Petřín Hill.',
  ),
  placeIn(
    'prague',
    'prague-fanta-building',
    'Prague Main Station Fanta Hall',
    'travel',
    50.0832,
    14.435,
    900,
    'Art Nouveau station hall with a domed café.',
  ),
  placeIn(
    'vienna',
    'vienna-schonbrunn',
    'Schönbrunn Palace',
    'heritage',
    48.1845,
    16.3122,
    3800,
    'Habsburg summer palace with formal gardens and a hilltop arcade.',
  ),
  placeIn(
    'vienna',
    'vienna-stephansdom',
    'St Stephen’s Cathedral',
    'heritage',
    48.2085,
    16.3731,
    3500,
    'Gothic cathedral with a glazed-tile roof.',
  ),
  placeIn(
    'vienna',
    'vienna-belvedere',
    'Belvedere',
    'culture',
    48.1915,
    16.3809,
    2600,
    'Baroque palace that holds Klimt’s The Kiss.',
  ),
  placeIn(
    'vienna',
    'vienna-opera',
    'Vienna State Opera',
    'music_events',
    48.203,
    16.369,
    2200,
    'One of the world’s great opera houses.',
    { hours: [{ days: [0, 1, 2, 3, 4, 5, 6], open: '10:00', close: '23:00' }] },
  ),
  placeIn(
    'vienna',
    'vienna-prater',
    'Prater Giant Wheel',
    'other',
    48.2166,
    16.3958,
    2000,
    'Ferris wheel turning above the Prater since 1897.',
  ),
  placeIn(
    'vienna',
    'vienna-naschmarkt',
    'Naschmarkt',
    'other',
    48.1985,
    16.3632,
    1600,
    'Vienna’s most popular market, over a kilometre long.',
    { hours: [{ days: [1, 2, 3, 4, 5, 6], open: '06:00', close: '19:30' }] },
  ),
  placeIn(
    'vienna',
    'vienna-hundertwasser',
    'Hundertwasser House',
    'culture',
    48.2072,
    16.394,
    17,
    'A wavy, colourful apartment block with trees growing on its roof.',
    { hidden: true },
  ),
  placeIn(
    'vienna',
    'vienna-albertina',
    'Albertina',
    'art',
    48.2045,
    16.3681,
    2600,
    'From Dürer’s hare to Monet and Picasso.',
  ),
  placeIn(
    'vienna',
    'vienna-leopold',
    'Leopold Museum',
    'art',
    48.2032,
    16.3592,
    2000,
    'The world’s largest Egon Schiele collection.',
  ),
  placeIn(
    'vienna',
    'vienna-secession',
    'Secession Building',
    'art',
    48.2006,
    16.3657,
    1400,
    'Golden-domed temple of Art Nouveau with Klimt’s frieze.',
  ),
  placeIn(
    'vienna',
    'vienna-kunsthistorisches',
    'Kunsthistorisches Museum',
    'culture',
    48.2038,
    16.3617,
    2900,
    'Bruegels and a café under the dome.',
  ),
  placeIn(
    'vienna',
    'vienna-hofburg',
    'Hofburg Palace',
    'culture',
    48.2066,
    16.3655,
    3000,
    'Imperial palace, home of the Spanish Riding School.',
  ),
  placeIn(
    'vienna',
    'vienna-stadtpark',
    'Stadtpark',
    'nature',
    48.2049,
    16.3797,
    1500,
    'Park with the golden statue of Johann Strauss.',
  ),
  placeIn(
    'vienna',
    'vienna-kahlenberg',
    'Kahlenberg',
    'nature',
    48.2757,
    16.3333,
    700,
    'Hill in the Vienna Woods with vineyards and a city view.',
  ),
  placeIn(
    'vienna',
    'vienna-donauinsel',
    'Danube Island',
    'nature',
    48.23,
    16.415,
    600,
    'Twenty-one kilometres of island for swimming and cycling.',
  ),
  placeIn(
    'vienna',
    'vienna-ring-tram',
    'Ring Tram at Schwedenplatz',
    'travel',
    48.2115,
    16.3782,
    1100,
    'Trams circling the grand Ringstrasse.',
  ),
  placeIn(
    'vienna',
    'vienna-karlsplatz-pavilions',
    'Otto Wagner Pavilions, Karlsplatz',
    'travel',
    48.2004,
    16.3696,
    700,
    'Golden-flowered Jugendstil station buildings.',
  ),
  placeIn(
    'edinburgh',
    'edinburgh-castle',
    'Edinburgh Castle',
    'heritage',
    55.9486,
    -3.1999,
    3900,
    'Fortress on an extinct volcano above the city.',
  ),
  placeIn(
    'edinburgh',
    'edinburgh-arthurs-seat',
    'Arthur’s Seat',
    'nature',
    55.9441,
    -3.1618,
    2300,
    'Ancient volcano you can climb for a view over the Firth of Forth.',
  ),
  placeIn(
    'edinburgh',
    'edinburgh-st-giles',
    'St Giles’ Cathedral',
    'heritage',
    55.9495,
    -3.1909,
    2600,
    'Crowned spire on the Royal Mile.',
  ),
  placeIn(
    'edinburgh',
    'edinburgh-calton-hill',
    'Calton Hill',
    'nature',
    55.9553,
    -3.1827,
    2000,
    'Hill of monuments with the best sunset view in town.',
  ),
  placeIn(
    'edinburgh',
    'edinburgh-national-museum',
    'National Museum of Scotland',
    'culture',
    55.9469,
    -3.19,
    2400,
    'From Dolly the sheep to Pictish stones.',
  ),
  placeIn(
    'edinburgh',
    'edinburgh-portobello',
    'Portobello Beach',
    'coast',
    55.9541,
    -3.11,
    900,
    'Sandy beach with a Victorian promenade.',
  ),
  placeIn(
    'edinburgh',
    'edinburgh-dean-village',
    'Dean Village',
    'other',
    55.9522,
    -3.2161,
    18,
    'Old mill village beside the Water of Leith, minutes from Princes Street.',
    { hidden: true },
  ),
  placeIn(
    'edinburgh',
    'edinburgh-national-gallery',
    'Scottish National Gallery',
    'art',
    55.9509,
    -3.1959,
    2300,
    'Old masters in a temple on The Mound.',
  ),
  placeIn(
    'edinburgh',
    'edinburgh-modern-art',
    'National Gallery of Modern Art',
    'art',
    55.9509,
    -3.228,
    700,
    'Modern art set in landscaped grounds.',
  ),
  placeIn(
    'edinburgh',
    'edinburgh-leith-murals',
    'Leith Murals',
    'art',
    55.969,
    -3.172,
    200,
    'Colourful murals along Leith Walk.',
  ),
  placeIn(
    'edinburgh',
    'edinburgh-holyrood',
    'Palace of Holyroodhouse',
    'culture',
    55.9527,
    -3.1722,
    2000,
    'The King’s official residence in Scotland.',
  ),
  placeIn(
    'edinburgh',
    'edinburgh-writers-museum',
    'Writers’ Museum',
    'culture',
    55.9493,
    -3.1945,
    500,
    'Burns, Scott and Stevenson in a close off the Royal Mile.',
  ),
  placeIn(
    'edinburgh',
    'edinburgh-botanic',
    'Royal Botanic Garden',
    'nature',
    55.9658,
    -3.209,
    1400,
    'Glasshouses and a rock garden with skyline views.',
  ),
  placeIn(
    'edinburgh',
    'edinburgh-water-of-leith',
    'Water of Leith Walkway',
    'nature',
    55.9585,
    -3.2085,
    500,
    'Riverside path from Stockbridge to Dean Village.',
  ),
  placeIn(
    'edinburgh',
    'edinburgh-blackford-hill',
    'Blackford Hill',
    'nature',
    55.927,
    -3.19,
    300,
    'Quiet hill with views to the castle and Arthur’s Seat.',
  ),
  placeIn(
    'edinburgh',
    'edinburgh-waverley',
    'Edinburgh Waverley',
    'travel',
    55.952,
    -3.189,
    2800,
    'Station in a valley between the Old and New Towns.',
  ),
  placeIn(
    'edinburgh',
    'edinburgh-britannia',
    'Royal Yacht Britannia',
    'travel',
    55.982,
    -3.177,
    1300,
    'The royal family’s former floating palace, moored in Leith.',
  ),
];

/** Launch places plus the side quests: 5+ per category in every city. */
export const EUROPE_PLACES: Place[] = [...LAUNCH_PLACES, ...EUROPE_QUESTS];
