import { placeIn } from './place-in';
import { EUROPE_QUESTS } from './quests';
import type { Place } from './types';

/** Curated landmarks for the launch cities. `hidden` ones stay off the map until you're within 200 m. */
const LAUNCH_PLACES: Place[] = [
  placeIn(
    'sintra',
    'sintra-fonte-mourisca',
    'Moorish Fountain',
    'heritage',
    38.7983,
    -9.3858,
    3,
    'Neo-Moorish fountain tiled in green and white, tucked into a bend of the old road.',
    { hidden: true },
  ),
  placeIn(
    'sintra',
    'sintra-peninha',
    'Peninha Sanctuary',
    'nature',
    38.7686,
    -9.4589,
    9,
    'Hermit chapel on a granite crag with the whole coast below it.',
    { hidden: true },
  ),
  placeIn(
    'sintra',
    'sintra-musa',
    'MU.SA – Sintra Arts Museum',
    'art',
    38.7988,
    -9.3826,
    140,
    'Modern and contemporary art in the old casino building, a short walk from the palace.',
  ),
  placeIn(
    'sintra',
    'sintra-anjos-teixeira',
    'Anjos Teixeira Sculpture Museum',
    'art',
    38.795,
    -9.392,
    35,
    'Father-and-son sculptor’s studio, tucked beside the stream below the town.',
  ),
  placeIn(
    'sintra',
    'sintra-leal-da-camara',
    'Leal da Câmara House-Museum',
    'art',
    38.7826,
    -9.334,
    20,
    'Caricatures and posters by a cartoonist who mocked kings and politicians.',
  ),
  placeIn(
    'sintra',
    'sintra-national-palace',
    'Sintra National Palace',
    'culture',
    38.7976,
    -9.3906,
    3800,
    'Medieval royal palace crowned by two giant white chimneys.',
  ),
  placeIn(
    'sintra',
    'sintra-ferreira-de-castro',
    'Ferreira de Castro House-Museum',
    'culture',
    38.7962,
    -9.3913,
    45,
    'The study and library of one of Portugal’s great novelists.',
  ),
  placeIn(
    'sintra',
    'sintra-valley-of-lakes',
    'Valley of the Lakes, Pena Park',
    'nature',
    38.786,
    -9.392,
    600,
    'Chain of ponds with a little duck castle, deep in the palace gardens.',
  ),
  placeIn(
    'sintra',
    'sintra-lagoa-azul',
    'Lagoa Azul',
    'nature',
    38.771,
    -9.418,
    90,
    'Quiet blue lake in the pine forest on the road to the coast.',
  ),
  placeIn(
    'sintra',
    'sintra-pedra-amarela',
    'Pedra Amarela',
    'nature',
    38.781,
    -9.431,
    55,
    'Granite outcrop with a sweeping view over the hills to the sea.',
  ),
  placeIn(
    'sintra',
    'sintra-station',
    'Sintra Station',
    'travel',
    38.7988,
    -9.378,
    1500,
    'Tiled 19th-century terminus where the train from Lisbon ends.',
  ),
  placeIn(
    'sintra',
    'sintra-tram',
    'Sintra Tram at Praia das Maçãs',
    'travel',
    38.8226,
    -9.4664,
    260,
    'Vintage tram that rattles from the hills down to the beach.',
  ),
  placeIn(
    'lisbon',
    'lisbon-belem-tower',
    'Belém Tower',
    'heritage',
    38.6916,
    -9.216,
    4200,
    'Sixteenth-century fortress that guarded the mouth of the Tagus.',
  ),
  placeIn(
    'lisbon',
    'lisbon-jeronimos',
    'Jerónimos Monastery',
    'heritage',
    38.6979,
    -9.2068,
    3900,
    'Manueline monastery carved with ropes, shells and sea creatures.',
  ),
  placeIn(
    'lisbon',
    'lisbon-sao-jorge',
    'São Jorge Castle',
    'heritage',
    38.7139,
    -9.1335,
    3600,
    'Hilltop castle whose ramparts look over the red roofs of Alfama.',
  ),
  placeIn(
    'lisbon',
    'lisbon-senhora-do-monte',
    'Senhora do Monte Viewpoint',
    'nature',
    38.7193,
    -9.1326,
    420,
    'The highest viewpoint in Lisbon, under umbrella pines.',
  ),
  placeIn(
    'lisbon',
    'lisbon-lx-factory',
    'LX Factory',
    'culture',
    38.7037,
    -9.1785,
    1300,
    'Old textile mill turned into studios, bookshops and street art.',
  ),
  placeIn(
    'lisbon',
    'lisbon-fado-alfama',
    'Alfama Fado House',
    'music_events',
    38.7106,
    -9.1305,
    260,
    'Candle-lit room where fado is sung most nights.',
    { hours: [{ days: [0, 1, 2, 3, 4, 5, 6], open: '20:00', close: '01:00' }] },
  ),
  placeIn(
    'lisbon',
    'lisbon-sao-cristovao-steps',
    'São Cristóvão Steps',
    'other',
    38.7128,
    -9.1351,
    6,
    'Stairway painted with a mural of the fado singers who lived here.',
    { hidden: true },
  ),
  placeIn(
    'lisbon',
    'lisbon-maat',
    'MAAT',
    'art',
    38.6956,
    -9.195,
    2100,
    'Wave-shaped museum of art, architecture and technology you can walk on top of.',
  ),
  placeIn(
    'lisbon',
    'lisbon-berardo',
    'Berardo Collection at CCB',
    'art',
    38.6957,
    -9.2083,
    1700,
    'Modern art from Picasso to Warhol in the Belém Cultural Centre.',
  ),
  placeIn(
    'lisbon',
    'lisbon-crono-murals',
    'Crono Project Murals',
    'art',
    38.7315,
    -9.1468,
    380,
    'Giant murals painted across a row of abandoned buildings.',
  ),
  placeIn(
    'lisbon',
    'lisbon-gulbenkian',
    'Calouste Gulbenkian Museum',
    'culture',
    38.7372,
    -9.1545,
    2400,
    'From Egyptian treasures to Lalique jewels, in a modernist garden.',
  ),
  placeIn(
    'lisbon',
    'lisbon-azulejo',
    'National Tile Museum',
    'culture',
    38.7247,
    -9.1137,
    1300,
    'Five centuries of Portuguese tiles in a gilded convent.',
  ),
  placeIn(
    'lisbon',
    'lisbon-monsanto',
    'Monsanto Panoramic',
    'nature',
    38.73,
    -9.1835,
    210,
    'Abandoned hilltop restaurant in the forest with a 360° view.',
  ),
  placeIn(
    'lisbon',
    'lisbon-estufa-fria',
    'Estufa Fria',
    'nature',
    38.7287,
    -9.153,
    900,
    'Shaded greenhouse jungle of ferns, ponds and palms.',
  ),
  placeIn(
    'lisbon',
    'lisbon-estrela',
    'Estrela Garden',
    'nature',
    38.714,
    -9.1595,
    800,
    'Romantic park with a bandstand, ducks and a café by the lake.',
  ),
  placeIn(
    'lisbon',
    'lisbon-tram-28',
    'Tram 28 at Martim Moniz',
    'travel',
    38.716,
    -9.1365,
    4000,
    'Start of the famous yellow tram that climbs through Graça and Alfama.',
  ),
  placeIn(
    'lisbon',
    'lisbon-santa-justa',
    'Santa Justa Lift',
    'travel',
    38.7121,
    -9.1393,
    3500,
    'Neo-Gothic iron lift linking the Baixa to the Carmo ruins.',
  ),
  placeIn(
    'porto',
    'porto-ribeira',
    'Ribeira Waterfront',
    'heritage',
    41.1407,
    -8.6131,
    3100,
    'Stacked, colourful houses along the Douro quay.',
  ),
  placeIn(
    'porto',
    'porto-lello',
    'Livraria Lello',
    'culture',
    41.1469,
    -8.6149,
    2800,
    'Neo-Gothic bookshop with a crimson staircase.',
  ),
  placeIn(
    'porto',
    'porto-clerigos',
    'Clérigos Tower',
    'heritage',
    41.1457,
    -8.6146,
    2400,
    'Baroque bell tower with 240 steps to the top.',
  ),
  placeIn(
    'porto',
    'porto-dom-luis',
    'Dom Luís I Bridge',
    'heritage',
    41.1399,
    -8.6094,
    2600,
    'Double-decker iron bridge you can walk across at rooftop height.',
  ),
  placeIn(
    'porto',
    'porto-palacio-cristal',
    'Crystal Palace Gardens',
    'nature',
    41.1479,
    -8.6255,
    700,
    'Romantic gardens with peacocks and river views.',
  ),
  placeIn(
    'porto',
    'porto-foz',
    'Foz do Douro Beach',
    'coast',
    41.1497,
    -8.6764,
    500,
    'Where the Douro meets the Atlantic, with a lighthouse pier.',
  ),
  placeIn(
    'porto',
    'porto-virtudes',
    'Virtudes Terraces',
    'nature',
    41.1438,
    -8.6188,
    11,
    'Sloping garden where locals watch the sun set over the river.',
    { hidden: true },
  ),
  placeIn(
    'porto',
    'porto-serralves',
    'Serralves Museum',
    'art',
    41.1597,
    -8.6598,
    1500,
    'White Siza Vieira museum of contemporary art.',
  ),
  placeIn(
    'porto',
    'porto-soares-dos-reis',
    'Soares dos Reis Museum',
    'art',
    41.1475,
    -8.6215,
    600,
    'Portugal’s oldest public art museum, in a neoclassical palace.',
  ),
  placeIn(
    'porto',
    'porto-half-rabbit',
    'Bordalo II’s Half Rabbit',
    'art',
    41.1372,
    -8.6095,
    700,
    'Huge rabbit sculpted from street rubbish on a Gaia wall.',
  ),
  placeIn(
    'porto',
    'porto-bolsa',
    'Palácio da Bolsa',
    'culture',
    41.1414,
    -8.6156,
    2100,
    'Stock exchange palace with a dazzling Arab Room.',
  ),
  placeIn(
    'porto',
    'porto-wow',
    'World of Wine',
    'culture',
    41.1355,
    -8.6143,
    1200,
    'Museums about wine, cork and chocolate in old port cellars.',
  ),
  placeIn(
    'porto',
    'porto-serralves-park',
    'Serralves Park',
    'nature',
    41.1585,
    -8.661,
    1000,
    'Gardens, woods and a giant red trowel sculpture.',
  ),
  placeIn(
    'porto',
    'porto-city-park',
    'Porto City Park',
    'nature',
    41.1705,
    -8.678,
    500,
    'The biggest urban park in Portugal, running down to the sea.',
  ),
  placeIn(
    'porto',
    'porto-passeio-alegre',
    'Passeio Alegre Garden',
    'nature',
    41.148,
    -8.672,
    180,
    'Palm-lined promenade where the river meets the ocean.',
  ),
  placeIn(
    'porto',
    'porto-sao-bento',
    'São Bento Station',
    'travel',
    41.1456,
    -8.6106,
    3900,
    'Station hall covered in 20,000 blue-and-white tiles.',
  ),
  placeIn(
    'porto',
    'porto-guindais',
    'Guindais Funicular',
    'travel',
    41.1407,
    -8.6084,
    900,
    'Funicular that climbs the old city walls from the river.',
  ),
];

/** Launch places plus the side quests: 5+ per category in every city. */
export const EUROPE_PLACES: Place[] = [...LAUNCH_PLACES, ...EUROPE_QUESTS];
