import { BASE_POINTS, DEFAULT_GEOFENCE_RADIUS_M } from './constants';
import type { Category, OpeningSlot, Place } from './types';

function placeIn(
  region: string,
  id: string,
  name: string,
  category: Category,
  lat: number,
  lng: number,
  uniqueVisitors: number,
  description: string,
  opts: { hidden?: boolean; hours?: OpeningSlot[] } = {},
): Place {
  return {
    id: `demo-${id}`,
    region,
    name,
    description,
    category,
    lat,
    lng,
    geofenceRadiusM: DEFAULT_GEOFENCE_RADIUS_M,
    basePoints: BASE_POINTS[category],
    uniqueVisitors,
    ...(opts.hidden && { hidden: true }),
    ...(opts.hours && { hours: opts.hours }),
  };
}

/** Curated landmarks for the launch cities. `hidden` ones stay off the map until you're within 200 m. */
export const EUROPE_PLACES: Place[] = [
  placeIn(
    'sintra',
    'sintra-fonte-mourisca',
    'Moorish Fountain',
    'heritage',
    38.7983,
    -9.3858,
    3,
    'Neo-Moorish fountain tiled in green and white, tucked into a bend of the old road.',
    { hidden: true },
  ),
  placeIn(
    'sintra',
    'sintra-peninha',
    'Peninha Sanctuary',
    'nature',
    38.7686,
    -9.4589,
    9,
    'Hermit chapel on a granite crag with the whole coast below it.',
    { hidden: true },
  ),
  placeIn(
    'lisbon',
    'lisbon-belem-tower',
    'Belém Tower',
    'heritage',
    38.6916,
    -9.216,
    4200,
    'Sixteenth-century fortress that guarded the mouth of the Tagus.',
  ),
  placeIn(
    'lisbon',
    'lisbon-jeronimos',
    'Jerónimos Monastery',
    'heritage',
    38.6979,
    -9.2068,
    3900,
    'Manueline monastery carved with ropes, shells and sea creatures.',
  ),
  placeIn(
    'lisbon',
    'lisbon-sao-jorge',
    'São Jorge Castle',
    'heritage',
    38.7139,
    -9.1335,
    3600,
    'Hilltop castle whose ramparts look over the red roofs of Alfama.',
  ),
  placeIn(
    'lisbon',
    'lisbon-senhora-do-monte',
    'Senhora do Monte Viewpoint',
    'nature',
    38.7193,
    -9.1326,
    420,
    'The highest viewpoint in Lisbon, under umbrella pines.',
  ),
  placeIn(
    'lisbon',
    'lisbon-lx-factory',
    'LX Factory',
    'culture',
    38.7037,
    -9.1785,
    1300,
    'Old textile mill turned into studios, bookshops and street art.',
  ),
  placeIn(
    'lisbon',
    'lisbon-fado-alfama',
    'Alfama Fado House',
    'music_events',
    38.7106,
    -9.1305,
    260,
    'Candle-lit room where fado is sung most nights.',
    { hours: [{ days: [0, 1, 2, 3, 4, 5, 6], open: '20:00', close: '01:00' }] },
  ),
  placeIn(
    'lisbon',
    'lisbon-sao-cristovao-steps',
    'São Cristóvão Steps',
    'other',
    38.7128,
    -9.1351,
    6,
    'Stairway painted with a mural of the fado singers who lived here.',
    { hidden: true },
  ),
  placeIn(
    'porto',
    'porto-ribeira',
    'Ribeira Waterfront',
    'heritage',
    41.1407,
    -8.6131,
    3100,
    'Stacked, colourful houses along the Douro quay.',
  ),
  placeIn(
    'porto',
    'porto-lello',
    'Livraria Lello',
    'culture',
    41.1469,
    -8.6149,
    2800,
    'Neo-Gothic bookshop with a crimson staircase.',
  ),
  placeIn(
    'porto',
    'porto-clerigos',
    'Clérigos Tower',
    'heritage',
    41.1457,
    -8.6146,
    2400,
    'Baroque bell tower with 240 steps to the top.',
  ),
  placeIn(
    'porto',
    'porto-dom-luis',
    'Dom Luís I Bridge',
    'heritage',
    41.1399,
    -8.6094,
    2600,
    'Double-decker iron bridge you can walk across at rooftop height.',
  ),
  placeIn(
    'porto',
    'porto-palacio-cristal',
    'Crystal Palace Gardens',
    'nature',
    41.1479,
    -8.6255,
    700,
    'Romantic gardens with peacocks and river views.',
  ),
  placeIn(
    'porto',
    'porto-foz',
    'Foz do Douro Beach',
    'coast',
    41.1497,
    -8.6764,
    500,
    'Where the Douro meets the Atlantic, with a lighthouse pier.',
  ),
  placeIn(
    'porto',
    'porto-virtudes',
    'Virtudes Terraces',
    'nature',
    41.1438,
    -8.6188,
    11,
    'Sloping garden where locals watch the sun set over the river.',
    { hidden: true },
  ),
  placeIn(
    'madrid',
    'madrid-royal-palace',
    'Royal Palace of Madrid',
    'heritage',
    40.418,
    -3.7143,
    3500,
    'One of the largest palaces in Europe, with 3,400 rooms.',
  ),
  placeIn(
    'madrid',
    'madrid-prado',
    'Prado Museum',
    'culture',
    40.4138,
    -3.6921,
    3300,
    'Velázquez, Goya and Bosch under one roof.',
  ),
  placeIn(
    'madrid',
    'madrid-retiro',
    'Retiro Park',
    'nature',
    40.4153,
    -3.6845,
    2900,
    'Rowing lake, rose garden and a glass palace.',
  ),
  placeIn(
    'madrid',
    'madrid-plaza-mayor',
    'Plaza Mayor',
    'heritage',
    40.4155,
    -3.7074,
    3000,
    'Arcaded seventeenth-century square at the heart of old Madrid.',
  ),
  placeIn(
    'madrid',
    'madrid-debod',
    'Temple of Debod',
    'heritage',
    40.424,
    -3.7178,
    1500,
    'Ancient Egyptian temple rebuilt on a hill above the city.',
  ),
  placeIn(
    'madrid',
    'madrid-san-miguel',
    'San Miguel Market',
    'other',
    40.4154,
    -3.709,
    1800,
    'Iron-and-glass market hall full of tapas stalls.',
    { hours: [{ days: [0, 1, 2, 3, 4, 5, 6], open: '10:00', close: '00:00' }] },
  ),
  placeIn(
    'madrid',
    'madrid-anglona',
    'Prince of Anglona Garden',
    'nature',
    40.4127,
    -3.7118,
    8,
    'A tiny walled garden from the 1700s, easy to walk past.',
    { hidden: true },
  ),
  placeIn(
    'barcelona',
    'barcelona-sagrada-familia',
    'Sagrada Família',
    'heritage',
    41.4036,
    2.1744,
    4500,
    'Gaudí’s basilica, still being built after more than a century.',
  ),
  placeIn(
    'barcelona',
    'barcelona-park-guell',
    'Park Güell',
    'nature',
    41.4145,
    2.1527,
    3400,
    'Mosaic terraces and gingerbread houses above the city.',
  ),
  placeIn(
    'barcelona',
    'barcelona-casa-batllo',
    'Casa Batlló',
    'culture',
    41.3917,
    2.1649,
    2700,
    'A house with a dragon’s back for a roof.',
  ),
  placeIn(
    'barcelona',
    'barcelona-barceloneta',
    'Barceloneta Beach',
    'coast',
    41.3784,
    2.1925,
    2200,
    'The city’s beach, a short walk from the old town.',
  ),
  placeIn(
    'barcelona',
    'barcelona-cathedral',
    'Barcelona Cathedral',
    'heritage',
    41.3839,
    2.1762,
    2500,
    'Gothic cathedral whose cloister is home to thirteen geese.',
  ),
  placeIn(
    'barcelona',
    'barcelona-palau-musica',
    'Palau de la Música Catalana',
    'music_events',
    41.3875,
    2.1753,
    900,
    'Modernista concert hall lit by a stained-glass skylight.',
    { hours: [{ days: [0, 1, 2, 3, 4, 5, 6], open: '10:00', close: '23:00' }] },
  ),
  placeIn(
    'barcelona',
    'barcelona-bunkers',
    'Carmel Bunkers',
    'nature',
    41.4192,
    2.1617,
    12,
    'Old anti-aircraft battery with a 360° view of Barcelona.',
    { hidden: true },
  ),
  placeIn(
    'paris',
    'paris-eiffel',
    'Eiffel Tower',
    'heritage',
    48.8584,
    2.2945,
    5000,
    'Iron lattice tower that sparkles on the hour after dark.',
  ),
  placeIn(
    'paris',
    'paris-louvre',
    'Louvre Museum',
    'culture',
    48.8606,
    2.3376,
    4800,
    'The world’s most visited museum, behind a glass pyramid.',
  ),
  placeIn(
    'paris',
    'paris-notre-dame',
    'Notre-Dame de Paris',
    'heritage',
    48.853,
    2.3499,
    4400,
    'Gothic cathedral on the Île de la Cité, restored after the 2019 fire.',
  ),
  placeIn(
    'paris',
    'paris-sacre-coeur',
    'Sacré-Cœur',
    'heritage',
    48.8867,
    2.3431,
    3800,
    'White basilica on top of Montmartre.',
  ),
  placeIn(
    'paris',
    'paris-luxembourg',
    'Luxembourg Gardens',
    'nature',
    48.8462,
    2.3372,
    2600,
    'Palace gardens with toy sailboats on the pond.',
  ),
  placeIn(
    'paris',
    'paris-orsay',
    'Musée d’Orsay',
    'culture',
    48.86,
    2.3266,
    3200,
    'Impressionist paintings inside a former railway station.',
  ),
  placeIn(
    'paris',
    'paris-cremieux',
    'Rue Crémieux',
    'other',
    48.847,
    2.3709,
    14,
    'A short cobbled street of pastel-painted houses.',
    { hidden: true },
  ),
  placeIn(
    'rome',
    'rome-colosseum',
    'Colosseum',
    'heritage',
    41.8902,
    12.4922,
    5000,
    'Amphitheatre that held 50,000 spectators.',
  ),
  placeIn(
    'rome',
    'rome-pantheon',
    'Pantheon',
    'heritage',
    41.8986,
    12.4769,
    4300,
    'Two-thousand-year-old temple with an open eye in its dome.',
  ),
  placeIn(
    'rome',
    'rome-trevi',
    'Trevi Fountain',
    'heritage',
    41.9009,
    12.4833,
    4600,
    'Throw a coin over your shoulder to return to Rome.',
  ),
  placeIn(
    'rome',
    'rome-forum',
    'Roman Forum',
    'heritage',
    41.8925,
    12.4853,
    3500,
    'The ruins of ancient Rome’s public square.',
  ),
  placeIn(
    'rome',
    'rome-borghese',
    'Villa Borghese Gardens',
    'nature',
    41.9142,
    12.4923,
    1900,
    'Rome’s central park, with a lake temple and a view from the Pincio.',
  ),
  placeIn(
    'rome',
    'rome-vatican-museums',
    'Vatican Museums',
    'culture',
    41.9065,
    12.4536,
    4100,
    'Miles of galleries ending at the Sistine Chapel.',
  ),
  placeIn(
    'rome',
    'rome-aventine-keyhole',
    'Aventine Keyhole',
    'other',
    41.8833,
    12.4797,
    10,
    'Peek through a garden door’s keyhole to see St Peter’s dome framed perfectly.',
    { hidden: true },
  ),
  placeIn(
    'florence',
    'florence-duomo',
    'Florence Cathedral',
    'heritage',
    43.7731,
    11.256,
    4200,
    'Brunelleschi’s dome still dominates the skyline.',
  ),
  placeIn(
    'florence',
    'florence-uffizi',
    'Uffizi Gallery',
    'culture',
    43.7678,
    11.2553,
    3700,
    'Botticelli’s Venus and the Renaissance masters.',
  ),
  placeIn(
    'florence',
    'florence-ponte-vecchio',
    'Ponte Vecchio',
    'heritage',
    43.768,
    11.2531,
    3900,
    'Medieval bridge lined with goldsmiths’ shops.',
  ),
  placeIn(
    'florence',
    'florence-michelangelo',
    'Piazzale Michelangelo',
    'nature',
    43.7629,
    11.265,
    2600,
    'The classic sunset view over Florence.',
  ),
  placeIn(
    'florence',
    'florence-boboli',
    'Boboli Gardens',
    'nature',
    43.7625,
    11.2484,
    1700,
    'Terraced Medici gardens full of statues and grottoes.',
  ),
  placeIn(
    'florence',
    'florence-rose-garden',
    'Rose Garden',
    'nature',
    43.7638,
    11.2626,
    7,
    'Quiet terraced rose garden just below the famous viewpoint.',
    { hidden: true },
  ),
  placeIn(
    'amsterdam',
    'amsterdam-rijksmuseum',
    'Rijksmuseum',
    'culture',
    52.36,
    4.8852,
    3600,
    'Rembrandt’s Night Watch and the Dutch Golden Age.',
  ),
  placeIn(
    'amsterdam',
    'amsterdam-anne-frank',
    'Anne Frank House',
    'heritage',
    52.3752,
    4.884,
    3300,
    'The canal house where Anne Frank wrote her diary.',
  ),
  placeIn(
    'amsterdam',
    'amsterdam-vondelpark',
    'Vondelpark',
    'nature',
    52.358,
    4.8686,
    2400,
    'The city’s favourite park for cycling and picnics.',
  ),
  placeIn(
    'amsterdam',
    'amsterdam-van-gogh',
    'Van Gogh Museum',
    'culture',
    52.3584,
    4.8811,
    3100,
    'The largest collection of Van Gogh’s work.',
  ),
  placeIn(
    'amsterdam',
    'amsterdam-dam',
    'Royal Palace on Dam Square',
    'heritage',
    52.3731,
    4.8913,
    2700,
    'Seventeenth-century town hall turned royal palace.',
  ),
  placeIn(
    'amsterdam',
    'amsterdam-concertgebouw',
    'Concertgebouw',
    'music_events',
    52.3563,
    4.8789,
    800,
    'Concert hall famous for its near-perfect acoustics.',
    { hours: [{ days: [0, 1, 2, 3, 4, 5, 6], open: '10:00', close: '23:00' }] },
  ),
  placeIn(
    'amsterdam',
    'amsterdam-begijnhof',
    'Begijnhof',
    'heritage',
    52.3693,
    4.8901,
    13,
    'Hidden courtyard of almshouses behind an unmarked door.',
    { hidden: true },
  ),
  placeIn(
    'berlin',
    'berlin-brandenburg',
    'Brandenburg Gate',
    'heritage',
    52.5163,
    13.3777,
    4400,
    'Neoclassical gate and symbol of reunified Germany.',
  ),
  placeIn(
    'berlin',
    'berlin-reichstag',
    'Reichstag Dome',
    'heritage',
    52.5186,
    13.3762,
    3200,
    'Glass dome on the parliament building with a spiral walkway.',
  ),
  placeIn(
    'berlin',
    'berlin-east-side-gallery',
    'East Side Gallery',
    'culture',
    52.505,
    13.4397,
    3000,
    'The longest surviving stretch of the Berlin Wall, covered in murals.',
  ),
  placeIn(
    'berlin',
    'berlin-museum-island',
    'Museum Island',
    'culture',
    52.5169,
    13.4019,
    2900,
    'Five world-class museums on an island in the Spree.',
  ),
  placeIn(
    'berlin',
    'berlin-tiergarten',
    'Tiergarten',
    'nature',
    52.5145,
    13.3501,
    2100,
    'Huge park in the centre of Berlin.',
  ),
  placeIn(
    'berlin',
    'berlin-wall-memorial',
    'Berlin Wall Memorial',
    'heritage',
    52.5351,
    13.3903,
    1900,
    'The preserved death strip on Bernauer Strasse.',
  ),
  placeIn(
    'berlin',
    'berlin-schwarzenberg',
    'Haus Schwarzenberg Courtyard',
    'culture',
    52.5245,
    13.4022,
    15,
    'Street-art-covered courtyard just off a busy street.',
    { hidden: true },
  ),
  placeIn(
    'prague',
    'prague-charles-bridge',
    'Charles Bridge',
    'heritage',
    50.0865,
    14.4114,
    4300,
    'Gothic stone bridge lined with thirty statues.',
  ),
  placeIn(
    'prague',
    'prague-castle',
    'Prague Castle',
    'heritage',
    50.0909,
    14.4005,
    4000,
    'The largest ancient castle complex in the world.',
  ),
  placeIn(
    'prague',
    'prague-old-town',
    'Old Town Square',
    'heritage',
    50.087,
    14.4207,
    4200,
    'Home of the astronomical clock that has ticked since 1410.',
  ),
  placeIn(
    'prague',
    'prague-petrin',
    'Petřín Hill',
    'nature',
    50.0833,
    14.395,
    1500,
    'Wooded hill with a mini Eiffel Tower and orchards.',
  ),
  placeIn(
    'prague',
    'prague-dancing-house',
    'Dancing House',
    'culture',
    50.0755,
    14.4141,
    1800,
    'Curvy building nicknamed Fred and Ginger.',
  ),
  placeIn(
    'prague',
    'prague-lennon-wall',
    'Lennon Wall',
    'culture',
    50.0862,
    14.4067,
    16,
    'A wall of ever-changing graffiti and messages of peace.',
    { hidden: true },
  ),
  placeIn(
    'vienna',
    'vienna-schonbrunn',
    'Schönbrunn Palace',
    'heritage',
    48.1845,
    16.3122,
    3800,
    'Habsburg summer palace with formal gardens and a hilltop arcade.',
  ),
  placeIn(
    'vienna',
    'vienna-stephansdom',
    'St Stephen’s Cathedral',
    'heritage',
    48.2085,
    16.3731,
    3500,
    'Gothic cathedral with a glazed-tile roof.',
  ),
  placeIn(
    'vienna',
    'vienna-belvedere',
    'Belvedere',
    'culture',
    48.1915,
    16.3809,
    2600,
    'Baroque palace that holds Klimt’s The Kiss.',
  ),
  placeIn(
    'vienna',
    'vienna-opera',
    'Vienna State Opera',
    'music_events',
    48.203,
    16.369,
    2200,
    'One of the world’s great opera houses.',
    { hours: [{ days: [0, 1, 2, 3, 4, 5, 6], open: '10:00', close: '23:00' }] },
  ),
  placeIn(
    'vienna',
    'vienna-prater',
    'Prater Giant Wheel',
    'other',
    48.2166,
    16.3958,
    2000,
    'Ferris wheel turning above the Prater since 1897.',
  ),
  placeIn(
    'vienna',
    'vienna-naschmarkt',
    'Naschmarkt',
    'other',
    48.1985,
    16.3632,
    1600,
    'Vienna’s most popular market, over a kilometre long.',
    { hours: [{ days: [1, 2, 3, 4, 5, 6], open: '06:00', close: '19:30' }] },
  ),
  placeIn(
    'vienna',
    'vienna-hundertwasser',
    'Hundertwasser House',
    'culture',
    48.2072,
    16.394,
    17,
    'A wavy, colourful apartment block with trees growing on its roof.',
    { hidden: true },
  ),
  placeIn(
    'edinburgh',
    'edinburgh-castle',
    'Edinburgh Castle',
    'heritage',
    55.9486,
    -3.1999,
    3900,
    'Fortress on an extinct volcano above the city.',
  ),
  placeIn(
    'edinburgh',
    'edinburgh-arthurs-seat',
    'Arthur’s Seat',
    'nature',
    55.9441,
    -3.1618,
    2300,
    'Ancient volcano you can climb for a view over the Firth of Forth.',
  ),
  placeIn(
    'edinburgh',
    'edinburgh-st-giles',
    'St Giles’ Cathedral',
    'heritage',
    55.9495,
    -3.1909,
    2600,
    'Crowned spire on the Royal Mile.',
  ),
  placeIn(
    'edinburgh',
    'edinburgh-calton-hill',
    'Calton Hill',
    'nature',
    55.9553,
    -3.1827,
    2000,
    'Hill of monuments with the best sunset view in town.',
  ),
  placeIn(
    'edinburgh',
    'edinburgh-national-museum',
    'National Museum of Scotland',
    'culture',
    55.9469,
    -3.19,
    2400,
    'From Dolly the sheep to Pictish stones.',
  ),
  placeIn(
    'edinburgh',
    'edinburgh-portobello',
    'Portobello Beach',
    'coast',
    55.9541,
    -3.11,
    900,
    'Sandy beach with a Victorian promenade.',
  ),
  placeIn(
    'edinburgh',
    'edinburgh-dean-village',
    'Dean Village',
    'other',
    55.9522,
    -3.2161,
    18,
    'Old mill village beside the Water of Leith, minutes from Princes Street.',
    { hidden: true },
  ),
];
