// Generated by `pnpm --filter importer photos` from Wikidata and Wikimedia Commons.
// Do not edit by hand: rerun the script. Every photo keeps its author, licence and source page.

export interface PlacePhoto {
  url: string;
  author: string;
  license: string;
  source: string;
}

export const PLACE_PHOTOS: Record<string, PlacePhoto> = {};
