import { haversineMeters, type LatLng, type Place } from '@wandro/shared';

export interface Candidate extends LatLng {
  qid: string;
  /** Commons file name from Wikidata P18. */
  image: string;
}

export interface FoundPhoto {
  url: string;
  author: string;
  license: string;
  source: string;
}

/** Same-named things elsewhere (a "Royal Botanic Garden" in another city) are further than this. */
export const MATCH_RADIUS_M = 1500;

/** The candidate nearest the place, if any is within MATCH_RADIUS_M. */
export function pickCandidate(place: LatLng, candidates: Candidate[]): Candidate | null {
  let best: Candidate | null = null;
  let bestD = MATCH_RADIUS_M;
  for (const c of candidates) {
    const d = haversineMeters(place, c);
    if (d <= bestD) {
      best = c;
      bestD = d;
    }
  }
  return best;
}

/** Commons' Artist field is HTML (links, spans); keep the readable name. */
export function stripHtml(html: string): string {
  return html
    .replace(/<[^>]*>/g, '')
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#0?39;/g, "'")
    .replace(/&nbsp;/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

export function photosModule(photos: Record<string, FoundPhoto>): string {
  const entries = Object.keys(photos)
    .sort()
    .map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(photos[id])},`);
  return `// Generated by \`pnpm --filter importer photos\` from Wikidata and Wikimedia Commons.
// Do not edit by hand: rerun the script. Every photo keeps its author, licence and source page.

export interface PlacePhoto {
  url: string;
  author: string;
  license: string;
  source: string;
}

export const PLACE_PHOTOS: Record<string, PlacePhoto> = {
${entries.join('\n')}
};
`;
}

const BEGIN = '-- BEGIN generated place photos (pnpm --filter importer photos)';
const END = '-- END generated place photos';
const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

/** Replaces (or appends) the generated photo block in the dev seed. Matches places by city + name. */
export function photoSeedSql(
  seed: string,
  photos: Record<string, FoundPhoto>,
  places: Place[],
): string {
  const rows = places.flatMap((p) => {
    const ph = photos[p.id];
    return ph && p.region
      ? [`  (${[p.region, p.name, ph.url, ph.author, ph.license, ph.source].map(q).join(', ')})`]
      : [];
  });
  const block = rows.length
    ? `${BEGIN}
insert into public.place_photos (place_id, external_url, author, license, source_url, is_primary, status)
select p.id, v.url, v.author, v.license, v.source, true, 'approved'
from (values
${rows.join(',\n')}
) as v(region, name, url, author, license, source)
join public.regions r on r.slug = v.region
join public.places p on p.region_id = r.id and p.name = v.name
on conflict do nothing;
${END}`
    : `${BEGIN}\n${END}`;
  const start = seed.indexOf(BEGIN);
  if (start === -1) return `${seed.trimEnd()}\n\n${block}\n`;
  const end = seed.indexOf(END, start) + END.length;
  return seed.slice(0, start) + block + seed.slice(end);
}
